// SPDX-FileCopyrightText: 2026 Alexey Zhokhov
// SPDX-License-Identifier: Apache-2.0
// GENERATED from registry/ — do not hand-edit. Regenerate: cargo xtask telemetry-registry --generate.

// registry: kind=internal; attributes=cli.command.name:recommended,cli.invocation.id:recommended,error.type:recommended,outcome:recommended,process.exit.code:recommended,session.id:recommended
pub const APP_SHUTDOWN: &str = "app.shutdown";
pub const APP_SHUTDOWN_DEF: super::SpanMetadata = super::SpanMetadata {
    name: APP_SHUTDOWN,
    description: "Bounded application shutdown.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.command.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "load",
                "hardline",
                "eject",
                "exile",
                "purge",
                "prewarm",
                "prune",
                "console",
                "role",
                "workspace",
                "config",
                "daemon",
                "doctor",
                "diagnostics",
                "status",
                "usage",
                "help",
                "role.validate",
                "role.migrate",
                "role.create",
                "role.construct-version",
                "role.published-image",
                "role.published-image-repository",
                "role.publish-labels",
                "daemon.serve",
                "daemon.install",
                "daemon.uninstall",
                "daemon.start",
                "daemon.stop",
                "daemon.restart",
                "daemon.status",
                "diagnostics.validate",
                "workspace.create",
                "workspace.list",
                "workspace.show",
                "workspace.edit",
                "workspace.prune",
                "workspace.remove",
                "workspace.env",
                "workspace.env.set",
                "workspace.env.unset",
                "workspace.env.list",
                "workspace.claude-token",
                "workspace.claude-token.setup",
                "workspace.claude-token.rotate",
                "workspace.claude-token.revoke",
                "workspace.claude-token.doctor",
                "config.mount",
                "config.mount.add",
                "config.mount.remove",
                "config.mount.list",
                "config.trust",
                "config.trust.grant",
                "config.trust.revoke",
                "config.trust.list",
                "config.auth",
                "config.auth.set",
                "config.auth.show",
                "config.env",
                "config.env.set",
                "config.env.unset",
                "config.env.list",
                "config.git",
                "config.git.coauthor-trailer",
                "config.git.coauthor-trailer.enable",
                "config.git.coauthor-trailer.disable",
                "config.git.dco",
                "config.git.dco.enable",
                "config.git.dco.disable",
                "prune.roles",
                "prune.cache",
                "prune.images",
                "prune.instances",
                "prune.system",
                "usage.accounts",
                "usage.verify",
            ],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "process.exit.code",
            value_type: super::ValueType::Integer,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=cli.command.name:recommended,cli.invocation.id:recommended,error.type:recommended,outcome:recommended,process.exit.code:recommended,session.id:recommended
pub const APP_STARTUP: &str = "app.startup";
pub const APP_STARTUP_DEF: super::SpanMetadata = super::SpanMetadata {
    name: APP_STARTUP,
    description: "Bounded application startup.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.command.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "load",
                "hardline",
                "eject",
                "exile",
                "purge",
                "prewarm",
                "prune",
                "console",
                "role",
                "workspace",
                "config",
                "daemon",
                "doctor",
                "diagnostics",
                "status",
                "usage",
                "help",
                "role.validate",
                "role.migrate",
                "role.create",
                "role.construct-version",
                "role.published-image",
                "role.published-image-repository",
                "role.publish-labels",
                "daemon.serve",
                "daemon.install",
                "daemon.uninstall",
                "daemon.start",
                "daemon.stop",
                "daemon.restart",
                "daemon.status",
                "diagnostics.validate",
                "workspace.create",
                "workspace.list",
                "workspace.show",
                "workspace.edit",
                "workspace.prune",
                "workspace.remove",
                "workspace.env",
                "workspace.env.set",
                "workspace.env.unset",
                "workspace.env.list",
                "workspace.claude-token",
                "workspace.claude-token.setup",
                "workspace.claude-token.rotate",
                "workspace.claude-token.revoke",
                "workspace.claude-token.doctor",
                "config.mount",
                "config.mount.add",
                "config.mount.remove",
                "config.mount.list",
                "config.trust",
                "config.trust.grant",
                "config.trust.revoke",
                "config.trust.list",
                "config.auth",
                "config.auth.set",
                "config.auth.show",
                "config.env",
                "config.env.set",
                "config.env.unset",
                "config.env.list",
                "config.git",
                "config.git.coauthor-trailer",
                "config.git.coauthor-trailer.enable",
                "config.git.coauthor-trailer.disable",
                "config.git.dco",
                "config.git.dco.enable",
                "config.git.dco.disable",
                "prune.roles",
                "prune.cache",
                "prune.images",
                "prune.instances",
                "prune.system",
                "usage.accounts",
                "usage.verify",
            ],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "process.exit.code",
            value_type: super::ValueType::Integer,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=background.cycle.name:required,cli.invocation.id:recommended,error.type:recommended,outcome:recommended,session.id:recommended
pub const BACKGROUND_CYCLE: &str = "background.cycle";
pub const BACKGROUND_CYCLE_DEF: super::SpanMetadata = super::SpanMetadata {
    name: BACKGROUND_CYCLE,
    description: "One periodic cycle.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "background.cycle.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "branch_context",
                "pr_context",
                "usage_account",
                "provider_probe",
                "instance_refresh",
                "agent_status",
            ],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=cli.command.name:required,cli.invocation.id:required,error.type:recommended,outcome:recommended,process.exit.code:recommended,session.id:recommended
pub const CLI_COMMAND: &str = "cli.command";
pub const CLI_COMMAND_DEF: super::SpanMetadata = super::SpanMetadata {
    name: CLI_COMMAND,
    description: "Bounded CLI command.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.command.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "load",
                "hardline",
                "eject",
                "exile",
                "purge",
                "prewarm",
                "prune",
                "console",
                "role",
                "workspace",
                "config",
                "daemon",
                "doctor",
                "diagnostics",
                "status",
                "usage",
                "help",
                "role.validate",
                "role.migrate",
                "role.create",
                "role.construct-version",
                "role.published-image",
                "role.published-image-repository",
                "role.publish-labels",
                "daemon.serve",
                "daemon.install",
                "daemon.uninstall",
                "daemon.start",
                "daemon.stop",
                "daemon.restart",
                "daemon.status",
                "diagnostics.validate",
                "workspace.create",
                "workspace.list",
                "workspace.show",
                "workspace.edit",
                "workspace.prune",
                "workspace.remove",
                "workspace.env",
                "workspace.env.set",
                "workspace.env.unset",
                "workspace.env.list",
                "workspace.claude-token",
                "workspace.claude-token.setup",
                "workspace.claude-token.rotate",
                "workspace.claude-token.revoke",
                "workspace.claude-token.doctor",
                "config.mount",
                "config.mount.add",
                "config.mount.remove",
                "config.mount.list",
                "config.trust",
                "config.trust.grant",
                "config.trust.revoke",
                "config.trust.list",
                "config.auth",
                "config.auth.set",
                "config.auth.show",
                "config.env",
                "config.env.set",
                "config.env.unset",
                "config.env.list",
                "config.git",
                "config.git.coauthor-trailer",
                "config.git.coauthor-trailer.enable",
                "config.git.coauthor-trailer.disable",
                "config.git.dco",
                "config.git.dco.enable",
                "config.git.dco.disable",
                "prune.roles",
                "prune.cache",
                "prune.images",
                "prune.instances",
                "prune.system",
                "usage.accounts",
                "usage.verify",
            ],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "process.exit.code",
            value_type: super::ValueType::Integer,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=client; attributes=cli.invocation.id:recommended,connection.peer.type:required,error.type:recommended,outcome:recommended,session.id:recommended
pub const CONNECTION_ATTEMPT: &str = "connection.attempt";
pub const CONNECTION_ATTEMPT_DEF: super::SpanMetadata = super::SpanMetadata {
    name: CONNECTION_ATTEMPT,
    description: "One connection attempt.",
    kind: super::SpanKind::Client,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "connection.peer.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "host_daemon",
                "capsule_control",
                "capsule_attach",
                "docker",
                "provider",
                "parallax",
            ],
        },
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=client; attributes=cli.invocation.id:recommended,db.operation.name:required,db.system.name:required,outcome:recommended,session.id:recommended
pub const DB_CLIENT: &str = "db.client";
pub const DB_CLIENT_DEF: super::SpanMetadata = super::SpanMetadata {
    name: DB_CLIENT,
    description: "One bounded database client operation.",
    kind: super::SpanKind::Client,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "db.operation.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "connect", "begin", "commit", "rollback", "select", "insert", "upsert", "update",
                "delete",
            ],
        },
        super::AttributeRequirement {
            name: "db.system.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=client; attributes=cli.invocation.id:recommended,container.id:recommended,gen_ai.provider.name:recommended,http.request.method:required,outcome:recommended,server.address:recommended,session.id:recommended,url.template:required
pub const HTTP_CLIENT: &str = "http.client";
pub const HTTP_CLIENT_DEF: super::SpanMetadata = super::SpanMetadata {
    name: HTTP_CLIENT,
    description: "One bounded HTTP client request.",
    kind: super::SpanKind::Client,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "container.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "gen_ai.provider.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "anthropic",
                "openai",
                "amp",
                "xai",
                "zai",
                "minimax",
                "kimi",
            ],
        },
        super::AttributeRequirement {
            name: "http.request.method",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "server.address",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "url.template",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=cli.invocation.id:recommended,launch.target.kind:required,outcome:recommended,session.id:recommended
pub const LAUNCH: &str = "launch";
pub const LAUNCH_DEF: super::SpanMetadata = super::SpanMetadata {
    name: LAUNCH,
    description: "One bounded launch pipeline.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "launch.target.kind",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &["workspace", "directory"],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=cli.invocation.id:recommended,launch.stage.name:required,outcome:recommended,session.id:recommended
pub const LAUNCH_STAGE: &str = "launch.stage";
pub const LAUNCH_STAGE_DEF: super::SpanMetadata = super::SpanMetadata {
    name: LAUNCH_STAGE,
    description: "One bounded launch pipeline stage.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "launch.stage.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "identity",
                "role",
                "credentials",
                "construct",
                "agent_binaries",
                "derived_image",
                "workspace",
                "network",
                "sidecar",
                "capsule",
                "hardline",
            ],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=consumer; attributes=cli.invocation.id:recommended,job.id:recommended,job.type:recommended,outcome:recommended,session.id:recommended
pub const PREWARM_ATTEMPT: &str = "prewarm.attempt";
pub const PREWARM_ATTEMPT_DEF: super::SpanMetadata = super::SpanMetadata {
    name: PREWARM_ATTEMPT,
    description: "Detached prewarm job attempt.",
    kind: super::SpanKind::Consumer,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "job.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "job.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &["image_prewarm", "sidecar_prewarm"],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=producer; attributes=cli.invocation.id:recommended,job.id:recommended,job.type:recommended,outcome:recommended,session.id:recommended
pub const PREWARM_SCHEDULE: &str = "prewarm.schedule";
pub const PREWARM_SCHEDULE_DEF: super::SpanMetadata = super::SpanMetadata {
    name: PREWARM_SCHEDULE,
    description: "Detached prewarm job scheduling decision.",
    kind: super::SpanKind::Producer,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "job.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "job.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &["image_prewarm", "sidecar_prewarm"],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=client; attributes=cli.invocation.id:recommended,outcome:recommended,process.executable.name:recommended,process.exit.code:recommended,session.id:recommended
pub const PROCESS_COMMAND: &str = "process.command";
pub const PROCESS_COMMAND_DEF: super::SpanMetadata = super::SpanMetadata {
    name: PROCESS_COMMAND,
    description: "One subprocess command.",
    kind: super::SpanKind::Client,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "process.executable.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "jackin",
                "jackin-daemon",
                "jackin-capsule",
                "jackin-role",
                "git",
                "gh",
                "op",
                "docker",
                "container",
                "mise",
                "ps",
                "osascript",
                "sh",
                "caffeinate",
                "kill",
                "less",
                "more",
                "bat",
                "claude",
                "codex",
                "amp",
                "kimi",
                "opencode",
                "grok",
                "configured_command",
                "other",
            ],
        },
        super::AttributeRequirement {
            name: "process.exit.code",
            value_type: super::ValueType::Integer,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=client; attributes=cli.invocation.id:recommended,outcome:recommended,rpc.method:required,rpc.system.name:required,session.id:recommended
pub const RPC_CLIENT: &str = "rpc.client";
pub const RPC_CLIENT_DEF: super::SpanMetadata = super::SpanMetadata {
    name: RPC_CLIENT,
    description: "One bounded RPC client request.",
    kind: super::SpanKind::Client,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "rpc.method",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "jackin.capsule.Control/Status",
                "jackin.capsule.Control/TelemetryHealth",
                "jackin.capsule.Control/Snapshot",
                "jackin.capsule.Control/Agents",
                "jackin.capsule.Control/ReportRuntimeEvent",
                "jackin.capsule.Control/StatusCapture",
                "jackin.capsule.Control/UsageFocused",
                "jackin.capsule.Control/UsageRefreshFocused",
                "jackin.capsule.Control/UsageAccountList",
                "jackin.capsule.Control/ExecCommand",
                "jackin.capsule.Control/TokenUsage",
                "jackin.capsule.Control/Unknown",
                "jackin.capsule.Attach/Handshake",
                "jackin.capsule.Attach/Detach",
                "jackin.capsule.Attach/Focus",
                "jackin.capsule.Attach/ClipboardImageTransfer",
                "jackin.host.Credentials/Resolve",
                "jackin.host.Daemon/Hello",
                "jackin.host.Daemon/Status",
                "jackin.host.Daemon/TelemetryHealth",
                "jackin.host.Daemon/AttentionSnapshot",
                "jackin.host.Daemon/Shutdown",
                "initialize",
                "initialized",
                "account/rateLimits/read",
                "account/read",
                "x.ai/billing",
            ],
        },
        super::AttributeRequirement {
            name: "rpc.system.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &["jackin", "codex.app-server", "grok.acp"],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=server; attributes=cli.invocation.id:recommended,outcome:recommended,rpc.method:required,rpc.system.name:required,session.id:recommended
pub const RPC_SERVER: &str = "rpc.server";
pub const RPC_SERVER_DEF: super::SpanMetadata = super::SpanMetadata {
    name: RPC_SERVER,
    description: "One bounded RPC server request.",
    kind: super::SpanKind::Server,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "rpc.method",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "jackin.capsule.Control/Status",
                "jackin.capsule.Control/TelemetryHealth",
                "jackin.capsule.Control/Snapshot",
                "jackin.capsule.Control/Agents",
                "jackin.capsule.Control/ReportRuntimeEvent",
                "jackin.capsule.Control/StatusCapture",
                "jackin.capsule.Control/UsageFocused",
                "jackin.capsule.Control/UsageRefreshFocused",
                "jackin.capsule.Control/UsageAccountList",
                "jackin.capsule.Control/ExecCommand",
                "jackin.capsule.Control/TokenUsage",
                "jackin.capsule.Control/Unknown",
                "jackin.capsule.Attach/Handshake",
                "jackin.capsule.Attach/Detach",
                "jackin.capsule.Attach/Focus",
                "jackin.capsule.Attach/ClipboardImageTransfer",
                "jackin.host.Credentials/Resolve",
                "jackin.host.Daemon/Hello",
                "jackin.host.Daemon/Status",
                "jackin.host.Daemon/TelemetryHealth",
                "jackin.host.Daemon/AttentionSnapshot",
                "jackin.host.Daemon/Shutdown",
                "initialize",
                "initialized",
                "account/rateLimits/read",
                "account/read",
                "x.ai/billing",
            ],
        },
        super::AttributeRequirement {
            name: "rpc.system.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &["jackin", "codex.app-server", "grok.acp"],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=error.type:recommended,outcome:recommended,session.id:recommended,stream.operation:required
pub const STREAM_OPERATION: &str = "stream.operation";
pub const STREAM_OPERATION_DEF: super::SpanMetadata = super::SpanMetadata {
    name: STREAM_OPERATION,
    description: "One bounded stream lifecycle phase.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "error.type",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "stream.operation",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &["open", "close"],
        },
    ],
};
// registry: kind=internal; attributes=cli.invocation.id:recommended,outcome:recommended,session.id:recommended
pub const TELEMETRY_VALIDATE: &str = "telemetry.validate";
pub const TELEMETRY_VALIDATE_DEF: super::SpanMetadata = super::SpanMetadata {
    name: TELEMETRY_VALIDATE,
    description: "Telemetry delivery validation.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=app.screen.id:recommended,app.screen.name:recommended,app.widget.id:recommended,app.widget.name:recommended,cli.invocation.id:recommended,outcome:recommended,session.id:recommended,ui.action.name:required
pub const UI_ACTION: &str = "ui.action";
pub const UI_ACTION_DEF: super::SpanMetadata = super::SpanMetadata {
    name: UI_ACTION,
    description: "Bounded semantic UI action.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "app.screen.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "workspace.list",
                "workspace.editor",
                "settings",
                "workspace.create",
                "launch.progress",
                "capsule",
            ],
        },
        super::AttributeRequirement {
            name: "app.screen.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "app.widget.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "app.widget.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "ui.action.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "workspace.open",
                "workspace.save",
                "workspace.launch",
                "settings.open",
                "settings.save",
                "dialog.confirm",
                "dialog.cancel",
                "agent.select",
                "agent.spawn",
                "tab.switch",
                "tab.rename",
                "tab.close",
                "pane.split",
                "pane.focus",
                "pane.resize",
                "pane.zoom",
                "pane.clear",
                "pane.close",
                "usage.refresh",
                "session.detach",
                "file.export",
                "image.stage",
                "link.open",
                "app.exit_request",
                "screen.back",
                "workspace.create",
                "workspace.delete",
                "instance.purge",
            ],
        },
    ],
};
// registry: kind=internal; attributes=app.screen.id:recommended,cli.invocation.id:recommended,outcome:recommended,session.id:recommended
pub const UI_RENDER: &str = "ui.render";
pub const UI_RENDER_DEF: super::SpanMetadata = super::SpanMetadata {
    name: UI_RENDER,
    description: "Bounded action-triggered render.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "app.screen.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "workspace.list",
                "workspace.editor",
                "settings",
                "workspace.create",
                "launch.progress",
                "capsule",
            ],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
    ],
};
// registry: kind=internal; attributes=app.screen.id:required,app.screen.name:required,cli.invocation.id:recommended,outcome:recommended,session.id:recommended,ui.transition.from_screen.id:required,ui.transition.reason:required
pub const UI_SCREEN_TRANSITION: &str = "ui.screen.transition";
pub const UI_SCREEN_TRANSITION_DEF: super::SpanMetadata = super::SpanMetadata {
    name: UI_SCREEN_TRANSITION,
    description: "Bounded screen transition.",
    kind: super::SpanKind::Internal,
    attributes: &[
        super::AttributeRequirement {
            name: "app.screen.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "workspace.list",
                "workspace.editor",
                "settings",
                "workspace.create",
                "launch.progress",
                "capsule",
            ],
        },
        super::AttributeRequirement {
            name: "app.screen.name",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "cli.invocation.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "outcome",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[
                "success",
                "failure",
                "error",
                "timeout",
                "skip",
                "cancellation",
            ],
        },
        super::AttributeRequirement {
            name: "session.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Recommended,
            allowed_values: &[],
        },
        super::AttributeRequirement {
            name: "ui.transition.from_screen.id",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "workspace.list",
                "workspace.editor",
                "settings",
                "workspace.create",
                "launch.progress",
                "capsule",
            ],
        },
        super::AttributeRequirement {
            name: "ui.transition.reason",
            value_type: super::ValueType::String,
            requirement: super::RequirementLevel::Required,
            allowed_values: &[
                "action",
                "launch",
                "attach",
                "detach",
                "back",
                "cancel",
                "completion",
                "failure",
                "shutdown",
            ],
        },
    ],
};

pub const ALL: &[&str] = &[
    APP_SHUTDOWN,
    APP_STARTUP,
    BACKGROUND_CYCLE,
    CLI_COMMAND,
    CONNECTION_ATTEMPT,
    DB_CLIENT,
    HTTP_CLIENT,
    LAUNCH,
    LAUNCH_STAGE,
    PREWARM_ATTEMPT,
    PREWARM_SCHEDULE,
    PROCESS_COMMAND,
    RPC_CLIENT,
    RPC_SERVER,
    STREAM_OPERATION,
    TELEMETRY_VALIDATE,
    UI_ACTION,
    UI_RENDER,
    UI_SCREEN_TRANSITION,
];

pub const DEFINITIONS: &[super::SpanMetadata] = &[
    APP_SHUTDOWN_DEF,
    APP_STARTUP_DEF,
    BACKGROUND_CYCLE_DEF,
    CLI_COMMAND_DEF,
    CONNECTION_ATTEMPT_DEF,
    DB_CLIENT_DEF,
    HTTP_CLIENT_DEF,
    LAUNCH_DEF,
    LAUNCH_STAGE_DEF,
    PREWARM_ATTEMPT_DEF,
    PREWARM_SCHEDULE_DEF,
    PROCESS_COMMAND_DEF,
    RPC_CLIENT_DEF,
    RPC_SERVER_DEF,
    STREAM_OPERATION_DEF,
    TELEMETRY_VALIDATE_DEF,
    UI_ACTION_DEF,
    UI_RENDER_DEF,
    UI_SCREEN_TRANSITION_DEF,
];

#[must_use]
pub fn definition(name: &str) -> Option<&'static super::SpanMetadata> {
    DEFINITIONS
        .iter()
        .find(|definition| definition.name == name)
}
