// SPDX-FileCopyrightText: 2026 Alexey Zhokhov
// SPDX-License-Identifier: Apache-2.0
//! CSI sequence classification: keys, arrows, focus, and mouse reports.

use super::{InputEvent, parse_csi_u_key, parse_xterm_modify_other_keys};

/// Decode a complete CSI sequence into a higher-level event when we
/// recognise it. Returns `None` to forward the bytes verbatim.
/// Outer return shape:
///   `None`            → not classified, caller emits the raw `Data`.
///   `Some(None)`      → classified as "suppress" — emit nothing
///                       (kitty key-release and terminal-report replies).
///   `Some(Some(ev))`  → classified, caller emits `ev`.
pub(crate) enum CsiClassification {
    Unknown,
    Suppress,
    Event(InputEvent),
}

pub(crate) fn classify_csi(seq: &[u8], palette_key: Option<u8>) -> CsiClassification {
    // Focus in / out.
    if seq == b"\x1b[I" {
        return CsiClassification::Event(InputEvent::FocusIn);
    }
    if seq == b"\x1b[O" {
        return CsiClassification::Event(InputEvent::FocusOut);
    }
    // Kitty / CSI-u Escape and control keys. Once a focused agent enables the
    // kitty keyboard protocol, many terminals encode Esc as `CSI 27 ... u`
    // instead of a bare `ESC`; dialogs must still receive the same byte their
    // dismiss logic matches. Release events are suppressed like kitty arrow
    // releases because dialog and agent paths only care about key press / repeat.
    // Control-byte press/repeat events (palette key, Ctrl+Q, etc.) are
    // dispatched through the global keymap before being forwarded to the agent.
    if let Some(rest) = seq
        .strip_prefix(b"\x1b[")
        .and_then(|body| body.strip_suffix(b"u"))
    {
        let Some((codepoint, modifier, event)) = parse_csi_u_key(rest) else {
            return CsiClassification::Unknown;
        };
        if event == Some(3) {
            return CsiClassification::Suppress;
        }
        if codepoint == 27 && modifier.unwrap_or(1) == 1 {
            return CsiClassification::Event(InputEvent::Data(b"\x1b".to_vec()));
        }
        if matches!(event, None | Some(1 | 2))
            && let Some(control) = csi_u_control_byte(codepoint, modifier)
        {
            return dispatch_control_byte(control, palette_key)
                .map_or(CsiClassification::Unknown, |event| {
                    CsiClassification::Event(event)
                });
        }
    }
    // Xterm window-report replies (`CSI ... t`) are generated by the
    // outer terminal, not typed by the operator. Ghostty emits them
    // while answering size queries such as `CSI 18t`; during a
    // resize burst those replies arrive on the attach client's stdin
    // and cannot be safely routed by "whatever pane is focused now".
    // Forwarding them to a shell leaks fragments like `8;40;135t` as
    // command text. Keep this paired with the output-side `CSI ... t`
    // passthrough suppression in `session::apply_passthrough_policy` for `UnhandledCsi`.
    if matches!(seq.last(), Some(b't')) {
        return CsiClassification::Suppress;
    }
    // Ghostty may emit xterm modifyOtherKeys for Shift+Enter as
    // `CSI 27 ; 2 ; 13 ~` before the focused agent has negotiated
    // CSI-u/kitty mode on the outer terminal. Codex treats CSI-u
    // `CSI 13 ; 2 u` as the multiline-entry key but ignores the
    // xterm form, so normalize this one editor-critical key while
    // leaving the rest of modifyOtherKeys byte-for-byte.
    if let Some((13, 2)) = parse_xterm_modify_other_keys(seq) {
        return CsiClassification::Event(InputEvent::Data(b"\x1b[13;2u".to_vec()));
    }
    // Other Ctrl+key combos (palette key, Ctrl+Q, …) encoded as xterm
    // modifyOtherKeys by terminals that haven't negotiated CSI-u mode — dispatch
    // through the same control-byte path as the CSI-u block above.
    if let Some((codepoint, modifier)) = parse_xterm_modify_other_keys(seq)
        && let Some(control) = csi_u_control_byte(codepoint, Some(modifier))
    {
        return dispatch_control_byte(control, palette_key)
            .map_or(CsiClassification::Unknown, |event| {
                CsiClassification::Event(event)
            });
    }
    // Arrow keys.
    //
    // Three encodings arrive at this parser depending on what the
    // operator's outer terminal has been told to emit:
    //   1. Legacy:        ESC [ A/B/C/D
    //   2. xterm modifier: ESC [ 1 ; <mod> A/B/C/D
    //   3. Kitty progressive enhancement:
    //        ESC [ 1 ; <mod> : <event> A/B/C/D
    //      where event 1 = press, 2 = repeat, 3 = release.
    //
    // Encoding (3) lands here whenever a focused agent has pushed the
    // kitty keyboard protocol (`CSI > 1 u`) via OSC passthrough and
    // the daemon mirrored it onto the outer terminal — Claude Code
    // does this — and the operator subsequently presses any arrow.
    //
    // The multiplexer's dialog and most agents only understand
    // encoding (1) for navigation, so this branch normalises the
    // unmodified-press case down to the legacy form and drops key-
    // release events outright (the only emitter is kitty mode, and
    // forwarding them surfaces as visible garbage at agent prompts).
    // Modified arrows keep the legacy `ESC [ 1 ; <mod> <final>` form
    // so agents that consume Alt+Arrow / Shift+Arrow / Ctrl+Arrow
    // still see them; Alt-Shift-Arrow (mod 4) is intercepted as
    // `ResizePane` regardless of encoding to keep the multiplexer's
    // tmux-style drag-resize shortcut working.
    //
    // `Alt-Shift-Arrow` is reserved for multiplexer pane resize so it
    // does not collide with agents that consume `Alt+Arrow` (word
    // navigation) or `Shift+Arrow` (selection extend).
    if let Some(rest) = seq.strip_prefix(b"\x1b[1;")
        && let Some(&final_byte) = rest.last()
        && matches!(final_byte, b'A' | b'B' | b'C' | b'D')
    {
        let body = &rest[..rest.len() - 1];
        let (mod_part, event) = match body.iter().position(|&b| b == b':') {
            Some(i) => {
                let ev = std::str::from_utf8(&body[i + 1..])
                    .ok()
                    .and_then(|s| s.parse::<u32>().ok())
                    .unwrap_or(1);
                (&body[..i], ev)
            }
            None => (body, 1u32),
        };
        let modifier: u32 = std::str::from_utf8(mod_part)
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(1);

        // Drop kitty key-release entirely. Press (1) and repeat (2)
        // map to actions; anything else is treated as a press for
        // safety since older or non-conformant terminals may omit the
        // event tag.
        if event == 3 {
            return CsiClassification::Suppress;
        }

        if modifier == 4 {
            let action = match final_byte {
                b'A' => crate::tui::keymap::ResizePaneAction::Up,
                b'B' => crate::tui::keymap::ResizePaneAction::Down,
                b'C' => crate::tui::keymap::ResizePaneAction::Right,
                b'D' => crate::tui::keymap::ResizePaneAction::Left,
                _ => unreachable!("kitty arrow parser only calls resize mapping for arrow bytes"),
            };
            return CsiClassification::Event(action.to_input_event());
        }

        // No modifier and an event tag was present (kitty form) →
        // strip the kitty wrapper and emit legacy `ESC [ A/B/C/D`
        // so the dialog navigator and non-kitty agents match. When
        // the event tag was absent we leave the legacy `ESC [ 1 ; 1
        // <final>` shape alone — that form already round-trips
        // through every agent path tested.
        if modifier == 1 && body.contains(&b':') {
            let mut plain = b"\x1b[".to_vec();
            plain.push(final_byte);
            return CsiClassification::Event(InputEvent::Data(plain));
        }
    }
    // SGR mouse: ESC [ < ... M/m
    if let Some(rest) = seq.strip_prefix(b"\x1b[<")
        && let Some(final_byte) = rest.last()
        && matches!(final_byte, b'M' | b'm')
    {
        let body = &rest[..rest.len() - 1];
        let params: Option<Vec<u32>> = body
            .split(|&b| b == b';')
            .map(|p| std::str::from_utf8(p).ok().and_then(|s| s.parse().ok()))
            .collect();
        if let Some(p) = params
            && p.len() >= 3
        {
            let button = u8::try_from(p[0]).unwrap_or(u8::MAX);
            let col = u16::try_from(p[1]).unwrap_or(u16::MAX).saturating_sub(1);
            let row = u16::try_from(p[2]).unwrap_or(u16::MAX).saturating_sub(1);
            if *final_byte == b'M' {
                return CsiClassification::Event(InputEvent::MousePress { col, row, button });
            }
            return CsiClassification::Event(InputEvent::MouseRelease { col, row, button });
        }
    }
    CsiClassification::Unknown
}

/// Dispatch a bare control byte through the capsule-level keymap. Returns the
/// mapped `InputEvent` (palette open, request-exit, pane-resize, …) or `None`
/// when the byte has no capsule binding and should pass through to the agent.
pub(crate) fn dispatch_control_byte(control: u8, palette_key: Option<u8>) -> Option<InputEvent> {
    if Some(control) == palette_key {
        return Some(InputEvent::OpenPalette);
    }
    if let Some(chord) = crate::tui::keymap::raw_bytes_to_chord(&[control])
        && let Some(action) = crate::tui::keymap::CAPSULE_GLOBAL_KEYMAP.dispatch(chord)
    {
        return Some(action.to_input_event());
    }
    None
}

/// Map a CSI-u codepoint+modifier pair to a bare control byte (0x00–0x1F), or
/// `None` when the key is not a control byte. C0 codepoints pass through
/// directly. For printable codepoints, Ctrl must be held — CSI-u encodes
/// modifiers as a 1-based bitmask, so bit 2 of `modifier − 1` is the Ctrl bit.
pub(crate) fn csi_u_control_byte(codepoint: u32, modifier: Option<u32>) -> Option<u8> {
    if (0x00..=0x1f).contains(&codepoint) {
        return u8::try_from(codepoint).ok();
    }
    let modifier = modifier?;
    let ctrl_held = modifier.saturating_sub(1) & 0b100 != 0;
    if !ctrl_held {
        return None;
    }
    match u8::try_from(codepoint).ok()? {
        byte @ (b'a'..=b'z' | b'A'..=b'Z') => Some(byte.to_ascii_lowercase() - b'a' + 1),
        b'\\' => Some(0x1C),
        b']' => Some(0x1D),
        b'^' => Some(0x1E),
        b'_' => Some(0x1F),
        _ => None,
    }
}

pub(crate) fn classify_x10_mouse(seq: &[u8]) -> Option<InputEvent> {
    if seq.len() != 6 || !seq.starts_with(b"\x1b[M") {
        return None;
    }
    let button = seq[3].checked_sub(32)?;
    let col = u16::from(seq[4]).checked_sub(33)?;
    let row = u16::from(seq[5]).checked_sub(33)?;
    if button & 0b11 == 3 && button & 0b10_0000 == 0 {
        return Some(InputEvent::MouseRelease {
            col,
            row,
            button: 0,
        });
    }
    Some(InputEvent::MousePress { col, row, button })
}
