// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(jackin_usage_ffiFFI)
import jackin_usage_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jackin_usage_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jackin_usage_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJackinUsageFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Process-scoped `UniFFI` facade over the host usage runtime.
 */
public protocol UsageMenuBarBridgeProtocol: AnyObject, Sendable {
    
    /**
     * Short status-item label (worst enabled surface; remaining % by default).
     */
    func compactStatusBarLabel() throws  -> String
    
    /**
     * Pinned-surface compact status-item label.
     */
    func compactStatusBarLabelFor(surfaceId: String) throws  -> String?
    
    /**
     * Worst-first multi-surface compact strip (joined with ` · `).
     */
    func compactStatusBarStrip(max: UInt32) throws  -> String
    
    /**
     * List known accounts for one surface (`Some`) or all surfaces (`None`).
     */
    func listAccounts(surfaceId: String?) throws  -> [AccountDescriptorDto]
    
    /**
     * List all host surfaces with enable flags.
     */
    func listSurfaces() throws  -> [SurfaceDescriptorDto]
    
    /**
     * Merged menu-bar text for all enabled surfaces.
     */
    func mergedStatusBarLabel() throws  -> String
    
    /**
     * Poll events after `cursor` (exclusive).
     *
     * Always returns `Ok` for a valid open runtime. When the client cursor is
     * behind the retained log, `resync_required` is true on the batch (do not
     * turn that into an error — presentation must reset the cursor).
     */
    func nextEvents(cursor: UInt64, max: UInt32) throws  -> UsageEventBatchDto
    
    /**
     * Next network refresh label (`Next update in …` / `Next update due`).
     */
    func nextRefreshLabel() throws  -> String
    
    /**
     * Open the host runtime (paths + enable set). Idempotent replace.
     */
    func openRuntime(config: OpenConfig) throws 
    
    /**
     * Overview rows for every enabled surface (popover + Usage window).
     */
    func overviewRows() throws  -> [OverviewRowDto]
    
    /**
     * Intentional panic probe for containment tests (never call from product UI).
     */
    func panicProbe() throws 
    
    /**
     * Refresh one surface (`surface_id`) or all enabled (`None`).
     *
     * When `force` is false, respects the runtime refresh floor (poll-safe).
     * When `force` is true, bypasses the floor (manual Refresh).
     */
    func refresh(surfaceId: String?, force: Bool) throws 
    
    /**
     * Whether a non-forced refresh would probe the network.
     */
    func refreshDue() throws  -> Bool
    
    /**
     * Refresh floor seconds (clamped policy).
     */
    func refreshFloorSecs() throws  -> UInt64
    
    /**
     * Enable or disable a surface for bar + refresh.
     */
    func setEnabled(surfaceId: String, enabled: Bool) throws 
    
    /**
     * Presentation-time format prefs (`left`/`used`, `countdown`/`exact_clock`).
     */
    func setFormatPrefs(prefs: UsageFormatPrefsDto) throws 
    
    /**
     * Set refresh floor seconds (clamped ≥ 60 in Rust).
     */
    func setRefreshFloorSecs(secs: UInt64) throws 
    
    /**
     * Select which account drives snapshot/detail for a surface (persisted).
     */
    func setSelectedAccount(surfaceId: String, accountKey: String) throws 
    
    /**
     * Shutdown; idempotent.
     */
    func shutdown() throws 
    
    /**
     * Snapshot for one enabled surface (selected multi-account when set).
     */
    func snapshot(surfaceId: String) throws  -> UsageViewDto
    
    /**
     * Compact bar label for one surface.
     */
    func statusBarLabel(surfaceId: String) throws  -> String?
    
}
/**
 * Process-scoped `UniFFI` facade over the host usage runtime.
 */
open class UsageMenuBarBridge: UsageMenuBarBridgeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_jackin_usage_ffi_fn_clone_usagemenubarbridge(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_jackin_usage_ffi_fn_free_usagemenubarbridge(handle, $0) }
    }

    
    /**
     * Construct a closed bridge.
     */
public static func create() -> UsageMenuBarBridge  {
    return try!  FfiConverterTypeUsageMenuBarBridge_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_constructor_usagemenubarbridge_create(uniffiCallStatus
    )
})
}
    

    
    /**
     * Short status-item label (worst enabled surface; remaining % by default).
     */
open func compactStatusBarLabel()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_compact_status_bar_label(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Pinned-surface compact status-item label.
     */
open func compactStatusBarLabelFor(surfaceId: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_compact_status_bar_label_for(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(surfaceId),uniffiCallStatus
    )
})
}
    
    /**
     * Worst-first multi-surface compact strip (joined with ` · `).
     */
open func compactStatusBarStrip(max: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_compact_status_bar_strip(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(max),uniffiCallStatus
    )
})
}
    
    /**
     * List known accounts for one surface (`Some`) or all surfaces (`None`).
     */
open func listAccounts(surfaceId: String?)throws  -> [AccountDescriptorDto]  {
    return try  FfiConverterSequenceTypeAccountDescriptorDto.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_list_accounts(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(surfaceId),uniffiCallStatus
    )
})
}
    
    /**
     * List all host surfaces with enable flags.
     */
open func listSurfaces()throws  -> [SurfaceDescriptorDto]  {
    return try  FfiConverterSequenceTypeSurfaceDescriptorDto.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_list_surfaces(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Merged menu-bar text for all enabled surfaces.
     */
open func mergedStatusBarLabel()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_merged_status_bar_label(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Poll events after `cursor` (exclusive).
     *
     * Always returns `Ok` for a valid open runtime. When the client cursor is
     * behind the retained log, `resync_required` is true on the batch (do not
     * turn that into an error — presentation must reset the cursor).
     */
open func nextEvents(cursor: UInt64, max: UInt32)throws  -> UsageEventBatchDto  {
    return try  FfiConverterTypeUsageEventBatchDto_lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_next_events(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(cursor),
        FfiConverterUInt32.lower(max),uniffiCallStatus
    )
})
}
    
    /**
     * Next network refresh label (`Next update in …` / `Next update due`).
     */
open func nextRefreshLabel()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_next_refresh_label(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Open the host runtime (paths + enable set). Idempotent replace.
     */
open func openRuntime(config: OpenConfig)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_open_runtime(
            self.uniffiCloneHandle(),
        FfiConverterTypeOpenConfig_lower(config),uniffiCallStatus
    )
}
}
    
    /**
     * Overview rows for every enabled surface (popover + Usage window).
     */
open func overviewRows()throws  -> [OverviewRowDto]  {
    return try  FfiConverterSequenceTypeOverviewRowDto.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_overview_rows(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Intentional panic probe for containment tests (never call from product UI).
     */
open func panicProbe()throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_panic_probe(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Refresh one surface (`surface_id`) or all enabled (`None`).
     *
     * When `force` is false, respects the runtime refresh floor (poll-safe).
     * When `force` is true, bypasses the floor (manual Refresh).
     */
open func refresh(surfaceId: String?, force: Bool)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_refresh(
            self.uniffiCloneHandle(),
        FfiConverterOptionString.lower(surfaceId),
        FfiConverterBool.lower(force),uniffiCallStatus
    )
}
}
    
    /**
     * Whether a non-forced refresh would probe the network.
     */
open func refreshDue()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_refresh_due(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Refresh floor seconds (clamped policy).
     */
open func refreshFloorSecs()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_refresh_floor_secs(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Enable or disable a surface for bar + refresh.
     */
open func setEnabled(surfaceId: String, enabled: Bool)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_set_enabled(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(surfaceId),
        FfiConverterBool.lower(enabled),uniffiCallStatus
    )
}
}
    
    /**
     * Presentation-time format prefs (`left`/`used`, `countdown`/`exact_clock`).
     */
open func setFormatPrefs(prefs: UsageFormatPrefsDto)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_set_format_prefs(
            self.uniffiCloneHandle(),
        FfiConverterTypeUsageFormatPrefsDto_lower(prefs),uniffiCallStatus
    )
}
}
    
    /**
     * Set refresh floor seconds (clamped ≥ 60 in Rust).
     */
open func setRefreshFloorSecs(secs: UInt64)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_set_refresh_floor_secs(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(secs),uniffiCallStatus
    )
}
}
    
    /**
     * Select which account drives snapshot/detail for a surface (persisted).
     */
open func setSelectedAccount(surfaceId: String, accountKey: String)throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_set_selected_account(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(surfaceId),
        FfiConverterString.lower(accountKey),uniffiCallStatus
    )
}
}
    
    /**
     * Shutdown; idempotent.
     */
open func shutdown()throws   {try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_shutdown(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Snapshot for one enabled surface (selected multi-account when set).
     */
open func snapshot(surfaceId: String)throws  -> UsageViewDto  {
    return try  FfiConverterTypeUsageViewDto_lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_snapshot(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(surfaceId),uniffiCallStatus
    )
})
}
    
    /**
     * Compact bar label for one surface.
     */
open func statusBarLabel(surfaceId: String)throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeUsageBridgeError_lift) {
        uniffiCallStatus in
    uniffi_jackin_usage_ffi_fn_method_usagemenubarbridge_status_bar_label(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(surfaceId),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageMenuBarBridge: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = UsageMenuBarBridge

    public static func lift(_ handle: UInt64) throws -> UsageMenuBarBridge {
        return UsageMenuBarBridge(unsafeFromHandle: handle)
    }

    public static func lower(_ value: UsageMenuBarBridge) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageMenuBarBridge {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: UsageMenuBarBridge, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageMenuBarBridge_lift(_ handle: UInt64) throws -> UsageMenuBarBridge {
    return try FfiConverterTypeUsageMenuBarBridge.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageMenuBarBridge_lower(_ value: UsageMenuBarBridge) -> UInt64 {
    return FfiConverterTypeUsageMenuBarBridge.lower(value)
}




/**
 * One known account for a host surface (multi-account Desktop).
 */
public struct AccountDescriptorDto: Equatable, Hashable {
    public var surfaceId: String
    public var accountKey: String
    public var accountLabel: String
    public var planLabel: String?
    public var selected: Bool
    public var remainingPercent: UInt8?
    public var statusWord: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(surfaceId: String, accountKey: String, accountLabel: String, planLabel: String?, selected: Bool, remainingPercent: UInt8?, statusWord: String) {
        self.surfaceId = surfaceId
        self.accountKey = accountKey
        self.accountLabel = accountLabel
        self.planLabel = planLabel
        self.selected = selected
        self.remainingPercent = remainingPercent
        self.statusWord = statusWord
    }

    

    
}

#if compiler(>=6)
extension AccountDescriptorDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAccountDescriptorDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AccountDescriptorDto {
        return
            try AccountDescriptorDto(
                surfaceId: FfiConverterString.read(from: &buf), 
                accountKey: FfiConverterString.read(from: &buf), 
                accountLabel: FfiConverterString.read(from: &buf), 
                planLabel: FfiConverterOptionString.read(from: &buf), 
                selected: FfiConverterBool.read(from: &buf), 
                remainingPercent: FfiConverterOptionUInt8.read(from: &buf), 
                statusWord: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AccountDescriptorDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surfaceId, into: &buf)
        FfiConverterString.write(value.accountKey, into: &buf)
        FfiConverterString.write(value.accountLabel, into: &buf)
        FfiConverterOptionString.write(value.planLabel, into: &buf)
        FfiConverterBool.write(value.selected, into: &buf)
        FfiConverterOptionUInt8.write(value.remainingPercent, into: &buf)
        FfiConverterString.write(value.statusWord, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountDescriptorDto_lift(_ buf: RustBuffer) throws -> AccountDescriptorDto {
    return try FfiConverterTypeAccountDescriptorDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAccountDescriptorDto_lower(_ value: AccountDescriptorDto) -> RustBuffer {
    return FfiConverterTypeAccountDescriptorDto.lower(value)
}


/**
 * Monetary amount (minor units).
 */
public struct MoneyDto: Equatable, Hashable {
    public var amountMinor: Int64
    public var currency: String
    public var exponent: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(amountMinor: Int64, currency: String, exponent: UInt8) {
        self.amountMinor = amountMinor
        self.currency = currency
        self.exponent = exponent
    }

    

    
}

#if compiler(>=6)
extension MoneyDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoneyDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoneyDto {
        return
            try MoneyDto(
                amountMinor: FfiConverterInt64.read(from: &buf), 
                currency: FfiConverterString.read(from: &buf), 
                exponent: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: MoneyDto, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.amountMinor, into: &buf)
        FfiConverterString.write(value.currency, into: &buf)
        FfiConverterUInt8.write(value.exponent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoneyDto_lift(_ buf: RustBuffer) throws -> MoneyDto {
    return try FfiConverterTypeMoneyDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoneyDto_lower(_ value: MoneyDto) -> RustBuffer {
    return FfiConverterTypeMoneyDto.lower(value)
}


/**
 * Open configuration from Swift (paths only — no credentials).
 */
public struct OpenConfig: Equatable, Hashable {
    /**
     * Absolute jackin data directory (`~/.jackin/data`).
     */
    public var dataDir: String
    /**
     * Refresh floor seconds (clamped ≥ 60 in Rust).
     */
    public var refreshFloorSecs: UInt64
    /**
     * Enabled surface ids; empty = all.
     */
    public var enabledSurfaceIds: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Absolute jackin data directory (`~/.jackin/data`).
         */dataDir: String, 
        /**
         * Refresh floor seconds (clamped ≥ 60 in Rust).
         */refreshFloorSecs: UInt64, 
        /**
         * Enabled surface ids; empty = all.
         */enabledSurfaceIds: [String]) {
        self.dataDir = dataDir
        self.refreshFloorSecs = refreshFloorSecs
        self.enabledSurfaceIds = enabledSurfaceIds
    }

    

    
}

#if compiler(>=6)
extension OpenConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpenConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpenConfig {
        return
            try OpenConfig(
                dataDir: FfiConverterString.read(from: &buf), 
                refreshFloorSecs: FfiConverterUInt64.read(from: &buf), 
                enabledSurfaceIds: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: OpenConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dataDir, into: &buf)
        FfiConverterUInt64.write(value.refreshFloorSecs, into: &buf)
        FfiConverterSequenceString.write(value.enabledSurfaceIds, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenConfig_lift(_ buf: RustBuffer) throws -> OpenConfig {
    return try FfiConverterTypeOpenConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpenConfig_lower(_ value: OpenConfig) -> RustBuffer {
    return FfiConverterTypeOpenConfig.lower(value)
}


/**
 * Overview row for glance popover / Usage-window sidebar.
 */
public struct OverviewRowDto: Equatable, Hashable {
    public var surfaceId: String
    public var displayLabel: String
    public var headline: String
    public var resetLabel: String?
    public var exactReset: String?
    public var statusWord: String
    public var severity: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(surfaceId: String, displayLabel: String, headline: String, resetLabel: String?, exactReset: String?, statusWord: String, severity: String) {
        self.surfaceId = surfaceId
        self.displayLabel = displayLabel
        self.headline = headline
        self.resetLabel = resetLabel
        self.exactReset = exactReset
        self.statusWord = statusWord
        self.severity = severity
    }

    

    
}

#if compiler(>=6)
extension OverviewRowDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOverviewRowDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OverviewRowDto {
        return
            try OverviewRowDto(
                surfaceId: FfiConverterString.read(from: &buf), 
                displayLabel: FfiConverterString.read(from: &buf), 
                headline: FfiConverterString.read(from: &buf), 
                resetLabel: FfiConverterOptionString.read(from: &buf), 
                exactReset: FfiConverterOptionString.read(from: &buf), 
                statusWord: FfiConverterString.read(from: &buf), 
                severity: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: OverviewRowDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.surfaceId, into: &buf)
        FfiConverterString.write(value.displayLabel, into: &buf)
        FfiConverterString.write(value.headline, into: &buf)
        FfiConverterOptionString.write(value.resetLabel, into: &buf)
        FfiConverterOptionString.write(value.exactReset, into: &buf)
        FfiConverterString.write(value.statusWord, into: &buf)
        FfiConverterString.write(value.severity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOverviewRowDto_lift(_ buf: RustBuffer) throws -> OverviewRowDto {
    return try FfiConverterTypeOverviewRowDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOverviewRowDto_lower(_ value: OverviewRowDto) -> RustBuffer {
    return FfiConverterTypeOverviewRowDto.lower(value)
}


/**
 * One quota / spend bucket.
 */
public struct QuotaBucketDto: Equatable, Hashable {
    public var label: String
    public var usedLabel: String?
    public var limitLabel: String?
    public var remainingPercent: UInt8?
    public var resetLabel: String?
    public var resetsAt: Int64?
    public var statusSlot: String?
    public var paceLabel: String?
    public var status: String
    public var usedMoney: MoneyDto?
    public var limitMoney: MoneyDto?
    public var severity: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(label: String, usedLabel: String?, limitLabel: String?, remainingPercent: UInt8?, resetLabel: String?, resetsAt: Int64?, statusSlot: String?, paceLabel: String?, status: String, usedMoney: MoneyDto?, limitMoney: MoneyDto?, severity: String) {
        self.label = label
        self.usedLabel = usedLabel
        self.limitLabel = limitLabel
        self.remainingPercent = remainingPercent
        self.resetLabel = resetLabel
        self.resetsAt = resetsAt
        self.statusSlot = statusSlot
        self.paceLabel = paceLabel
        self.status = status
        self.usedMoney = usedMoney
        self.limitMoney = limitMoney
        self.severity = severity
    }

    

    
}

#if compiler(>=6)
extension QuotaBucketDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuotaBucketDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuotaBucketDto {
        return
            try QuotaBucketDto(
                label: FfiConverterString.read(from: &buf), 
                usedLabel: FfiConverterOptionString.read(from: &buf), 
                limitLabel: FfiConverterOptionString.read(from: &buf), 
                remainingPercent: FfiConverterOptionUInt8.read(from: &buf), 
                resetLabel: FfiConverterOptionString.read(from: &buf), 
                resetsAt: FfiConverterOptionInt64.read(from: &buf), 
                statusSlot: FfiConverterOptionString.read(from: &buf), 
                paceLabel: FfiConverterOptionString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                usedMoney: FfiConverterOptionTypeMoneyDto.read(from: &buf), 
                limitMoney: FfiConverterOptionTypeMoneyDto.read(from: &buf), 
                severity: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: QuotaBucketDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterOptionString.write(value.usedLabel, into: &buf)
        FfiConverterOptionString.write(value.limitLabel, into: &buf)
        FfiConverterOptionUInt8.write(value.remainingPercent, into: &buf)
        FfiConverterOptionString.write(value.resetLabel, into: &buf)
        FfiConverterOptionInt64.write(value.resetsAt, into: &buf)
        FfiConverterOptionString.write(value.statusSlot, into: &buf)
        FfiConverterOptionString.write(value.paceLabel, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterOptionTypeMoneyDto.write(value.usedMoney, into: &buf)
        FfiConverterOptionTypeMoneyDto.write(value.limitMoney, into: &buf)
        FfiConverterString.write(value.severity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuotaBucketDto_lift(_ buf: RustBuffer) throws -> QuotaBucketDto {
    return try FfiConverterTypeQuotaBucketDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuotaBucketDto_lower(_ value: QuotaBucketDto) -> RustBuffer {
    return FfiConverterTypeQuotaBucketDto.lower(value)
}


/**
 * Surface row for Settings / list.
 */
public struct SurfaceDescriptorDto: Equatable, Hashable {
    public var id: String
    public var label: String
    public var agent: String
    public var provider: String?
    public var enabled: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, label: String, agent: String, provider: String?, enabled: Bool) {
        self.id = id
        self.label = label
        self.agent = agent
        self.provider = provider
        self.enabled = enabled
    }

    

    
}

#if compiler(>=6)
extension SurfaceDescriptorDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSurfaceDescriptorDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SurfaceDescriptorDto {
        return
            try SurfaceDescriptorDto(
                id: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                agent: FfiConverterString.read(from: &buf), 
                provider: FfiConverterOptionString.read(from: &buf), 
                enabled: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SurfaceDescriptorDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.agent, into: &buf)
        FfiConverterOptionString.write(value.provider, into: &buf)
        FfiConverterBool.write(value.enabled, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceDescriptorDto_lift(_ buf: RustBuffer) throws -> SurfaceDescriptorDto {
    return try FfiConverterTypeSurfaceDescriptorDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSurfaceDescriptorDto_lower(_ value: SurfaceDescriptorDto) -> RustBuffer {
    return FfiConverterTypeSurfaceDescriptorDto.lower(value)
}


/**
 * Bounded event batch.
 */
public struct UsageEventBatchDto: Equatable, Hashable {
    public var nextCursor: UInt64
    public var events: [UsageEventDto]
    public var resyncRequired: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nextCursor: UInt64, events: [UsageEventDto], resyncRequired: Bool) {
        self.nextCursor = nextCursor
        self.events = events
        self.resyncRequired = resyncRequired
    }

    

    
}

#if compiler(>=6)
extension UsageEventBatchDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageEventBatchDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageEventBatchDto {
        return
            try UsageEventBatchDto(
                nextCursor: FfiConverterUInt64.read(from: &buf), 
                events: FfiConverterSequenceTypeUsageEventDto.read(from: &buf), 
                resyncRequired: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: UsageEventBatchDto, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.nextCursor, into: &buf)
        FfiConverterSequenceTypeUsageEventDto.write(value.events, into: &buf)
        FfiConverterBool.write(value.resyncRequired, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageEventBatchDto_lift(_ buf: RustBuffer) throws -> UsageEventBatchDto {
    return try FfiConverterTypeUsageEventBatchDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageEventBatchDto_lower(_ value: UsageEventBatchDto) -> RustBuffer {
    return FfiConverterTypeUsageEventBatchDto.lower(value)
}


/**
 * One host event.
 */
public struct UsageEventDto: Equatable, Hashable {
    public var sequence: UInt64
    public var kind: String
    public var surfaceId: String?
    public var detail: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sequence: UInt64, kind: String, surfaceId: String?, detail: String?) {
        self.sequence = sequence
        self.kind = kind
        self.surfaceId = surfaceId
        self.detail = detail
    }

    

    
}

#if compiler(>=6)
extension UsageEventDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageEventDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageEventDto {
        return
            try UsageEventDto(
                sequence: FfiConverterUInt64.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                surfaceId: FfiConverterOptionString.read(from: &buf), 
                detail: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: UsageEventDto, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.sequence, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.surfaceId, into: &buf)
        FfiConverterOptionString.write(value.detail, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageEventDto_lift(_ buf: RustBuffer) throws -> UsageEventDto {
    return try FfiConverterTypeUsageEventDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageEventDto_lower(_ value: UsageEventDto) -> RustBuffer {
    return FfiConverterTypeUsageEventDto.lower(value)
}


/**
 * Presentation-time format prefs (string enums).
 */
public struct UsageFormatPrefsDto: Equatable, Hashable {
    /**
     * `left` | `used`
     */
    public var percentStyle: String
    /**
     * `countdown` | `exact_clock`
     */
    public var resetStyle: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * `left` | `used`
         */percentStyle: String, 
        /**
         * `countdown` | `exact_clock`
         */resetStyle: String) {
        self.percentStyle = percentStyle
        self.resetStyle = resetStyle
    }

    

    
}

#if compiler(>=6)
extension UsageFormatPrefsDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageFormatPrefsDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageFormatPrefsDto {
        return
            try UsageFormatPrefsDto(
                percentStyle: FfiConverterString.read(from: &buf), 
                resetStyle: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: UsageFormatPrefsDto, into buf: inout [UInt8]) {
        FfiConverterString.write(value.percentStyle, into: &buf)
        FfiConverterString.write(value.resetStyle, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageFormatPrefsDto_lift(_ buf: RustBuffer) throws -> UsageFormatPrefsDto {
    return try FfiConverterTypeUsageFormatPrefsDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageFormatPrefsDto_lower(_ value: UsageFormatPrefsDto) -> RustBuffer {
    return FfiConverterTypeUsageFormatPrefsDto.lower(value)
}


/**
 * Full focused usage view for one surface.
 */
public struct UsageViewDto: Equatable, Hashable {
    public var focusedAgent: String?
    public var focusedProvider: String?
    public var providerLabel: String
    public var accountLabel: String
    public var username: String?
    public var planLabel: String?
    public var credentialOrigin: String?
    public var buckets: [QuotaBucketDto]
    public var status: String
    public var source: String
    public var confidence: String
    public var fetchedAtEpoch: Int64
    public var updatedLabel: String
    public var statusBarLabel: String
    public var lastError: String?
    /**
     * Honesty caption when estimated / local-log derived; `None` for authoritative.
     */
    public var estimateCaption: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(focusedAgent: String?, focusedProvider: String?, providerLabel: String, accountLabel: String, username: String?, planLabel: String?, credentialOrigin: String?, buckets: [QuotaBucketDto], status: String, source: String, confidence: String, fetchedAtEpoch: Int64, updatedLabel: String, statusBarLabel: String, lastError: String?, 
        /**
         * Honesty caption when estimated / local-log derived; `None` for authoritative.
         */estimateCaption: String?) {
        self.focusedAgent = focusedAgent
        self.focusedProvider = focusedProvider
        self.providerLabel = providerLabel
        self.accountLabel = accountLabel
        self.username = username
        self.planLabel = planLabel
        self.credentialOrigin = credentialOrigin
        self.buckets = buckets
        self.status = status
        self.source = source
        self.confidence = confidence
        self.fetchedAtEpoch = fetchedAtEpoch
        self.updatedLabel = updatedLabel
        self.statusBarLabel = statusBarLabel
        self.lastError = lastError
        self.estimateCaption = estimateCaption
    }

    

    
}

#if compiler(>=6)
extension UsageViewDto: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageViewDto: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageViewDto {
        return
            try UsageViewDto(
                focusedAgent: FfiConverterOptionString.read(from: &buf), 
                focusedProvider: FfiConverterOptionString.read(from: &buf), 
                providerLabel: FfiConverterString.read(from: &buf), 
                accountLabel: FfiConverterString.read(from: &buf), 
                username: FfiConverterOptionString.read(from: &buf), 
                planLabel: FfiConverterOptionString.read(from: &buf), 
                credentialOrigin: FfiConverterOptionString.read(from: &buf), 
                buckets: FfiConverterSequenceTypeQuotaBucketDto.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                source: FfiConverterString.read(from: &buf), 
                confidence: FfiConverterString.read(from: &buf), 
                fetchedAtEpoch: FfiConverterInt64.read(from: &buf), 
                updatedLabel: FfiConverterString.read(from: &buf), 
                statusBarLabel: FfiConverterString.read(from: &buf), 
                lastError: FfiConverterOptionString.read(from: &buf), 
                estimateCaption: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: UsageViewDto, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.focusedAgent, into: &buf)
        FfiConverterOptionString.write(value.focusedProvider, into: &buf)
        FfiConverterString.write(value.providerLabel, into: &buf)
        FfiConverterString.write(value.accountLabel, into: &buf)
        FfiConverterOptionString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.planLabel, into: &buf)
        FfiConverterOptionString.write(value.credentialOrigin, into: &buf)
        FfiConverterSequenceTypeQuotaBucketDto.write(value.buckets, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.source, into: &buf)
        FfiConverterString.write(value.confidence, into: &buf)
        FfiConverterInt64.write(value.fetchedAtEpoch, into: &buf)
        FfiConverterString.write(value.updatedLabel, into: &buf)
        FfiConverterString.write(value.statusBarLabel, into: &buf)
        FfiConverterOptionString.write(value.lastError, into: &buf)
        FfiConverterOptionString.write(value.estimateCaption, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageViewDto_lift(_ buf: RustBuffer) throws -> UsageViewDto {
    return try FfiConverterTypeUsageViewDto.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageViewDto_lower(_ value: UsageViewDto) -> RustBuffer {
    return FfiConverterTypeUsageViewDto.lower(value)
}


/**
 * Typed bridge failures. Messages never include credentials or tokens.
 */
public 
enum UsageBridgeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * Recoverable rejection (validation, unknown surface, closed runtime).
     */
    case Rejected(code: String, message: String
    )
    /**
     * A Rust panic was caught at the facade boundary.
     */
    case ContainedPanic(message: String
    )
    /**
     * Runtime not opened or already shut down.
     */
    case RuntimeUnavailable
    /**
     * Event cursor requires resync.
     */
    case ResyncRequired

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension UsageBridgeError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUsageBridgeError: FfiConverterRustBuffer {
    typealias SwiftType = UsageBridgeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UsageBridgeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Rejected(
            code: try FfiConverterString.read(from: &buf), 
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .ContainedPanic(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .RuntimeUnavailable
        case 4: return .ResyncRequired

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: UsageBridgeError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Rejected(code,message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(code, into: &buf)
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ContainedPanic(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case .RuntimeUnavailable:
            writeInt(&buf, Int32(3))
        
        
        case .ResyncRequired:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageBridgeError_lift(_ buf: RustBuffer) throws -> UsageBridgeError {
    return try FfiConverterTypeUsageBridgeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUsageBridgeError_lower(_ value: UsageBridgeError) -> RustBuffer {
    return FfiConverterTypeUsageBridgeError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMoneyDto: FfiConverterRustBuffer {
    typealias SwiftType = MoneyDto?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMoneyDto.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMoneyDto.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAccountDescriptorDto: FfiConverterRustBuffer {
    typealias SwiftType = [AccountDescriptorDto]

    public static func write(_ value: [AccountDescriptorDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAccountDescriptorDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [AccountDescriptorDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [AccountDescriptorDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAccountDescriptorDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOverviewRowDto: FfiConverterRustBuffer {
    typealias SwiftType = [OverviewRowDto]

    public static func write(_ value: [OverviewRowDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOverviewRowDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [OverviewRowDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [OverviewRowDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOverviewRowDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeQuotaBucketDto: FfiConverterRustBuffer {
    typealias SwiftType = [QuotaBucketDto]

    public static func write(_ value: [QuotaBucketDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeQuotaBucketDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [QuotaBucketDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [QuotaBucketDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeQuotaBucketDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSurfaceDescriptorDto: FfiConverterRustBuffer {
    typealias SwiftType = [SurfaceDescriptorDto]

    public static func write(_ value: [SurfaceDescriptorDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSurfaceDescriptorDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SurfaceDescriptorDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [SurfaceDescriptorDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSurfaceDescriptorDto.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUsageEventDto: FfiConverterRustBuffer {
    typealias SwiftType = [UsageEventDto]

    public static func write(_ value: [UsageEventDto], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUsageEventDto.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UsageEventDto] {
        let len: Int32 = try readInt(&buf)
        var seq = [UsageEventDto]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUsageEventDto.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jackin_usage_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_compact_status_bar_label() != 57867) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_compact_status_bar_label_for() != 27154) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_compact_status_bar_strip() != 29560) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_list_accounts() != 28969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_list_surfaces() != 14496) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_merged_status_bar_label() != 46622) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_next_events() != 65354) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_next_refresh_label() != 53364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_open_runtime() != 47176) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_overview_rows() != 59208) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_panic_probe() != 5364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_refresh() != 32155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_refresh_due() != 31521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_refresh_floor_secs() != 21503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_set_enabled() != 59390) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_set_format_prefs() != 53990) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_set_refresh_floor_secs() != 6201) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_set_selected_account() != 7286) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_shutdown() != 32908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_snapshot() != 15318) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_method_usagemenubarbridge_status_bar_label() != 38813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jackin_usage_ffi_checksum_constructor_usagemenubarbridge_create() != 13398) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJackinUsageFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all