//! Snapshot tests for the TUI render layer.
//!
//! Uses `insta` to pin the text output of key render functions. Any change to
//! rendered output fails CI until reviewed and accepted with `cargo insta review`.
//! This is the Phase 0 regression net for the TUI architecture refactor.
//!
//! Initial snapshots are generated by running:
//! ```sh
//! INSTA_UPDATE=new cargo test -p jackin -- snapshot_tests --nocapture
//! ```

#[cfg(test)]
mod tests {
    use ratatui::{Terminal, backend::TestBackend, layout::Rect};

    use crate::{
        config::AppConfig,
        console::manager::{
            prepare_for_render, render,
            state::{EditorState, EditorTab, ManagerStage, ManagerState, SettingsState},
        },
        workspace::WorkspaceConfig,
    };

    /// Render `ManagerState` to a text buffer dump for snapshot comparison.
    fn render_manager_state(
        state: &mut ManagerState<'_>,
        config: &AppConfig,
        cwd: &std::path::Path,
        width: u16,
        height: u16,
    ) -> String {
        let area = Rect::new(0, 0, width, height);
        let backend = TestBackend::new(width, height);
        let mut terminal = Terminal::new(backend).unwrap();
        prepare_for_render(state, config, cwd, area);
        terminal
            .draw(|frame| render(frame, area, state, config, cwd))
            .unwrap();
        let buf = terminal.backend().buffer();
        (0..height)
            .map(|y| {
                (0..width)
                    .map(|x| buf[(x, y)].symbol().to_string())
                    .collect::<String>()
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    fn test_cwd() -> std::path::PathBuf {
        // Use a stable path so snapshots are reproducible.
        std::path::PathBuf::from("/workspace")
    }

    #[test]
    fn snapshot_list_empty_80x24() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        // ManagerStage::List is the default.
        let rendered = render_manager_state(&mut state, &config, &cwd, 80, 24);
        insta::assert_snapshot!("list_empty_80x24", rendered);
    }

    #[test]
    fn snapshot_settings_general_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.stage = ManagerStage::Settings(SettingsState::from_config(&config));
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("settings_general_90x20", rendered);
    }

    #[test]
    fn snapshot_editor_general_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.stage = ManagerStage::Editor(EditorState::new_edit(
            "my-workspace".into(),
            WorkspaceConfig::default(),
        ));
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("editor_general_90x20", rendered);
    }

    #[test]
    fn snapshot_editor_mounts_tab_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.active_tab = EditorTab::Mounts;
        state.stage = ManagerStage::Editor(editor);
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("editor_mounts_tab_90x20", rendered);
    }
}
