/// First-run onboarding wizard.
///
/// Triggered when `jackin console` is invoked with no existing config and
/// an interactive TTY. Runs pre-flight checks, asks a few setup questions,
/// writes a starter `~/.config/jackin/config.toml`, and explains how to run
/// a role so the operator can use `jackin load` immediately.
use owo_colors::OwoColorize;

use crate::paths::JackinPaths;

/// Run the first-run onboarding wizard on stderr (the console TUI has not
/// opened yet). Returns `Ok(())` if setup completed; the caller proceeds to
/// launch the console normally. Returns `Err` only on unrecoverable I/O.
pub async fn run(paths: &JackinPaths) -> anyhow::Result<()> {
    println!();
    println!("{}", "Welcome to jackin'!".bold());
    println!(
        "{}",
        "Looks like this is your first run. Let's set up a starter config.".dimmed()
    );
    println!();

    // Step 1 — Docker check.
    println!("{}  Checking Docker daemon…", "1.".bold());
    match crate::docker_client::BollardDockerClient::connect() {
        Ok(_) => {
            println!("   {} Docker is reachable.", "✓".green().bold());
        }
        Err(e) => {
            println!("   {} Docker is not reachable: {e:#}", "✗".red().bold());
            println!(
                "   {}",
                "Start Docker Desktop, OrbStack, or run `colima start`, then re-run.".yellow()
            );
            anyhow::bail!(
                "Docker daemon is not reachable — cannot proceed with setup. Start Docker and try again."
            );
        }
    }
    println!();

    // Step 2 — Ask for workspace directory.
    println!(
        "{}  Enter your workspace directory (the project path jackin starts agents in).",
        "2.".bold()
    );
    println!("   Press Enter to use the current directory.");
    let cwd = std::env::current_dir()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| "~".to_string());
    print!("   Workspace [{}]: ", cwd.dimmed());
    use std::io::{self, Write as _};
    io::stdout().flush().ok();

    let mut workspace_input = String::new();
    io::stdin().read_line(&mut workspace_input).ok();
    let workspace_dir = {
        let trimmed = workspace_input.trim();
        if trimmed.is_empty() {
            cwd.clone()
        } else {
            trimmed.to_string()
        }
    };
    println!("   → {}", workspace_dir.green());
    println!();

    // Step 3 — Show available roles.
    println!(
        "{}  Recommended starter role: {}",
        "3.".bold(),
        "jackin-project/jackin-agent-smith".green()
    );
    println!(
        "   {}",
        "You can add more roles after setup with `jackin config trust add <role>`.".dimmed()
    );
    println!();

    // Step 4 — Write starter config.
    println!("{}  Writing starter config…", "4.".bold());
    let starter_config = format!(
        r#"# jackin' starter configuration
# Generated by the first-run wizard.
# Edit with: jackin config mount add / jackin workspace create

[workspaces.my-workspace]
workdir = "{workspace_dir}"

[[workspaces.my-workspace.mounts]]
src  = "{workspace_dir}"
dst  = "/home/agent/work"
isolation = "shared"
"#
    );
    std::fs::write(&paths.config_file, &starter_config).map_err(|e| {
        anyhow::anyhow!(
            "Failed to write starter config to {}: {e:#}",
            paths.config_file.display()
        )
    })?;
    println!(
        "   {} Written to {}",
        "✓".green().bold(),
        paths.config_file.display()
    );
    println!();

    // Step 5 — Next steps.
    println!("{}", "Setup complete!".bold().green());
    println!();
    println!("To launch your first agent session:");
    println!();
    println!(
        "  {} {}",
        "$".dimmed(),
        "jackin load jackin-project/jackin-agent-smith".bold()
    );
    println!();
    println!(
        "{}",
        "The console is opening now. Press Ctrl+C to exit, or select a workspace and role."
            .dimmed()
    );
    println!();

    Ok(())
}
