use super::{AuthProvisionOutcome, RoleState};
use crate::config::AuthForwardMode;
use std::path::Path;

impl RoleState {
    /// Provision Codex's host-side config.toml. Mounted RW into the
    /// container at `/home/agent/.codex/config.toml`.
    ///
    /// The generated file sets `approval_policy = "never"` and
    /// `sandbox_mode = "danger-full-access"` to match the operator
    /// contract jackin already accepts for Claude
    /// (`--dangerously-skip-permissions`): once the operator has
    /// chosen to drop the agent into the container, jackin treats
    /// the container as the scope of untrusted-AI execution.
    /// Codex's internal approval prompt would add per-action friction
    /// without changing what the agent can reach (workspace mounts,
    /// the network namespace, the `DinD` sidecar).
    pub(super) fn provision_codex_auth(
        config_toml: &std::path::Path,
        manifest: &crate::manifest::RoleManifest,
    ) -> anyhow::Result<()> {
        use std::fmt::Write;

        let mut content = String::from(
            "# Generated by jackin; do not edit.\n\
             approval_policy = \"never\"\n\
             sandbox_mode = \"danger-full-access\"\n",
        );

        if let Some(codex_cfg) = manifest.codex.as_ref()
            && let Some(model) = &codex_cfg.model
        {
            writeln!(content, "model = \"{model}\"").expect("string formatting cannot fail");
        }

        // Skip the write when content matches what's already on disk so
        // operator-edited files aren't churned on every launch (they will
        // still be regenerated when manifest content changes — e.g. a new
        // [codex].model — which is the intended behaviour for a "do not
        // edit" file).
        if let Ok(existing) = std::fs::read_to_string(config_toml)
            && existing == content
        {
            return Ok(());
        }

        write_private_file(config_toml, &content)
    }
}

impl RoleState {
    /// Provision both Claude's account-metadata file (`account_json`,
    /// host-side; mounted at `/home/agent/.claude.json` in the container)
    /// and the OAuth credential file inside the session-state directory
    /// (`state_dir/.credentials.json`, host-side; mounted at
    /// `/home/agent/.claude/.credentials.json`) according to the chosen
    /// auth forwarding strategy.
    ///
    /// `account_json` must always exist after this call because Docker
    /// bind-mounts require the source to be a file, not a missing path
    /// (otherwise Docker creates a directory, breaking Claude Code).
    ///
    /// On macOS the host credentials live in the system Keychain
    /// ("Claude Code-credentials"), not in a file.  On Linux they are
    /// stored at `~/.claude/.credentials.json`.
    pub(super) fn provision_claude_auth(
        account_json: &Path,
        state_dir: &Path,
        mode: AuthForwardMode,
        host_home: &Path,
    ) -> anyhow::Result<AuthProvisionOutcome> {
        let host_claude_json = host_home.join(".claude.json");
        let credentials_json = state_dir.join(".credentials.json");

        let outcome = match mode {
            AuthForwardMode::Ignore => {
                // Always ensure a clean slate — if switching from sync/token
                // to ignore, the previously forwarded credentials must be
                // revoked.
                if !account_json.exists() || std::fs::read_to_string(account_json)? != "{}" {
                    write_private_file(account_json, "{}")?;
                }
                if credentials_json.exists() {
                    std::fs::remove_file(&credentials_json)?;
                }
                AuthProvisionOutcome::Skipped
            }
            AuthForwardMode::Token => {
                // Token mode provisions the same empty shape as Ignore —
                // Claude Code inside the container authenticates via
                // CLAUDE_CODE_OAUTH_TOKEN from the resolved env, not via
                // filesystem credentials. Switching from sync → token must
                // still wipe any previously forwarded creds.
                if !account_json.exists() || std::fs::read_to_string(account_json)? != "{}" {
                    write_private_file(account_json, "{}")?;
                }
                if credentials_json.exists() {
                    std::fs::remove_file(&credentials_json)?;
                }
                AuthProvisionOutcome::TokenMode
            }
            AuthForwardMode::Sync => {
                if let Some(creds) = read_host_credentials(host_home) {
                    copy_host_claude_json(&host_claude_json, account_json)?;
                    write_private_file(&credentials_json, &creds)?;
                    AuthProvisionOutcome::Synced
                } else {
                    // Host has no auth — leave the container's existing
                    // files untouched (it may have credentials from a
                    // previous manual login). Only bootstrap an empty
                    // file if nothing exists yet.
                    if !account_json.exists() {
                        write_private_file(account_json, "{}")?;
                    }
                    // Repair permissions on pre-existing auth files that
                    // may have legacy permissive modes (e.g. 0644).
                    repair_permissions(account_json);
                    repair_permissions(&credentials_json);
                    AuthProvisionOutcome::HostMissing
                }
            }
        };

        Ok(outcome)
    }
}

/// Copy the host's `.claude.json` into the container state, or write `{}`
/// if the host file doesn't exist.
fn copy_host_claude_json(host_path: &Path, dest_path: &Path) -> anyhow::Result<()> {
    let content = std::fs::read_to_string(host_path).unwrap_or_else(|_| "{}".to_string());
    write_private_file(dest_path, &content)
}

/// Read the host's Claude Code OAuth credentials.
///
/// Checks the file-based store at `~/.claude/.credentials.json` first
/// (used on Linux, and makes the function testable with temp dirs).
/// Falls back to the macOS Keychain ("Claude Code-credentials") when
/// the file is absent and `host_home` matches the real home directory.
fn read_host_credentials(host_home: &Path) -> Option<String> {
    // File-based credentials (Linux, or macOS with an explicit export).
    let creds_path = host_home.join(".claude/.credentials.json");
    if let Ok(content) = std::fs::read_to_string(creds_path) {
        return Some(content);
    }

    // macOS Keychain fallback — only attempted when host_home is the
    // real home directory.  This keeps tests hermetic (they use temp
    // dirs) while still supporting the Keychain in production.
    #[cfg(target_os = "macos")]
    {
        let real_home = directories::BaseDirs::new().map(|b| b.home_dir().to_path_buf());
        if real_home.as_deref() == Some(host_home) {
            let output = std::process::Command::new("security")
                .args([
                    "find-generic-password",
                    "-s",
                    "Claude Code-credentials",
                    "-w",
                ])
                .output()
                .ok()?;
            if output.status.success() {
                let creds = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !creds.is_empty() {
                    return Some(creds);
                }
            }
        }
    }

    None
}

/// Reject symlinks at `path` to prevent a compromised role from
/// redirecting host-side writes to arbitrary files.
///
/// The role's `.claude/` directory is mounted read-write into the
/// container, so an role could replace `.credentials.json` with a
/// symlink.  Without this check, the next `write_private_file` or
/// `repair_permissions` call would follow the symlink and overwrite
/// or chmod the target on the host.
fn reject_symlink(path: &Path) -> anyhow::Result<()> {
    // Use symlink_metadata (lstat) — regular metadata() follows symlinks.
    if let Ok(meta) = std::fs::symlink_metadata(path) {
        anyhow::ensure!(
            !meta.file_type().is_symlink(),
            "refusing to write through symlink at {}; \
             this may indicate a compromised role state — \
             remove the symlink and retry",
            path.display()
        );
    }
    Ok(())
}

/// Write a file with restricted permissions (`0o600` on Unix) since it
/// may contain authentication credentials.
///
/// Rejects symlinks to prevent a compromised role from redirecting
/// writes to arbitrary host paths.  Uses `tempfile::NamedTempFile` to
/// create an unpredictable temp file (opened with `O_EXCL`, so a
/// pre-planted symlink at the temp path is impossible), then renames
/// it to the destination — closing the TOCTOU window entirely.
fn write_private_file(path: &Path, content: &str) -> anyhow::Result<()> {
    reject_symlink(path)?;

    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::PermissionsExt;

        let parent = path
            .parent()
            .ok_or_else(|| anyhow::anyhow!("no parent directory for {}", path.display()))?;

        // NamedTempFile uses O_EXCL internally, so it will never follow
        // a pre-planted symlink.  The random suffix makes the path
        // unpredictable.
        let mut tmp = tempfile::NamedTempFile::new_in(parent)?;
        tmp.write_all(content.as_bytes())?;
        std::fs::set_permissions(tmp.path(), std::fs::Permissions::from_mode(0o600))?;
        tmp.persist(path)?;
    }
    #[cfg(not(unix))]
    {
        std::fs::write(path, content)?;
    }
    Ok(())
}

/// Tighten permissions on an existing file to `0o600` if it exists.
/// Refuses to operate on symlinks.  No-op on non-Unix or if the file
/// doesn't exist.
fn repair_permissions(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        // Use symlink_metadata so we don't follow symlinks.
        if let Ok(meta) = std::fs::symlink_metadata(path) {
            if meta.file_type().is_symlink() {
                eprintln!(
                    "[jackin] warning: refusing to chmod symlink at {}",
                    path.display()
                );
                return;
            }
            if meta.is_file() {
                let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
            }
        }
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
}

#[cfg(test)]
mod tests {
    use crate::config::AuthForwardMode;
    use crate::instance::{AuthProvisionOutcome, RoleState};
    use crate::paths::JackinPaths;
    use tempfile::tempdir;

    const TEST_CREDENTIALS: &str =
        r#"{"claudeAiOauth":{"accessToken":"test","refreshToken":"test"}}"#;

    /// Set up a fake host auth environment in the temp dir.
    fn seed_host_auth(temp: &tempfile::TempDir) {
        std::fs::write(
            temp.path().join(".claude.json"),
            r#"{"oauthAccount":{"emailAddress":"test@example.com"}}"#,
        )
        .unwrap();
        let creds_dir = temp.path().join(".claude");
        std::fs::create_dir_all(&creds_dir).unwrap();
        std::fs::write(creds_dir.join(".credentials.json"), TEST_CREDENTIALS).unwrap();
    }

    fn simple_manifest(temp: &tempfile::TempDir) -> crate::manifest::RoleManifest {
        std::fs::write(
            temp.path().join("jackin.role.toml"),
            r#"dockerfile = "Dockerfile"

[claude]
plugins = []
"#,
        )
        .unwrap();
        std::fs::write(
            temp.path().join("Dockerfile"),
            "FROM projectjackin/construct:trixie\n",
        )
        .unwrap();
        crate::manifest::RoleManifest::load(temp.path()).unwrap()
    }

    // ── Auth forwarding tests ───────────────────────────────────────────

    // ── Auth forwarding tests ───────────────────────────────────────────

    #[test]
    fn ignore_mode_writes_empty_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );
        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
    }

    #[test]
    fn sync_mode_copies_host_auth_on_first_run() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert!(
            std::fs::read_to_string(state.claude_account_json().unwrap())
                .unwrap()
                .contains("test@example.com")
        );
        assert_eq!(
            std::fs::read_to_string(state.claude_state_dir().unwrap().join(".credentials.json"))
                .unwrap(),
            TEST_CREDENTIALS
        );
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
    }

    #[test]
    fn sync_mode_falls_back_to_empty_json_when_host_has_none() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        // No host auth seeded
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
    }

    #[test]
    fn sync_mode_overwrites_existing() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run with host auth
        seed_host_auth(&temp);
        let (state, outcome1) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(outcome1, AuthProvisionOutcome::Synced);

        // Simulate container modifying its own .claude.json
        std::fs::write(
            state.claude_account_json().unwrap(),
            r#"{"container":"data"}"#,
        )
        .unwrap();

        // Update host credentials
        let updated_creds = r#"{"claudeAiOauth":{"accessToken":"new","refreshToken":"new"}}"#;
        std::fs::write(temp.path().join(".claude/.credentials.json"), updated_creds).unwrap();

        // Second run: should overwrite with host content
        let (state2, outcome2) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state2.claude_state_dir().unwrap().join(".credentials.json"))
                .unwrap(),
            updated_creds
        );
        assert_eq!(outcome2, AuthProvisionOutcome::Synced);
    }

    // ── Mode transition tests ───────────────────────────────────────────

    #[test]
    fn switching_from_sync_to_ignore_revokes_forwarded_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: sync mode writes credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(
            state
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );

        // Operator switches to ignore — credentials must be wiped
        let (state2, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state2
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );
    }

    #[test]
    fn token_mode_writes_empty_json_and_no_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        // Seed host auth — token mode must NOT copy it.
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Token,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists(),
            "token mode must not write .credentials.json"
        );
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
    }

    #[test]
    fn switching_from_sync_to_token_revokes_forwarded_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: sync mode writes credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(
            state
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );

        // Operator switches to token — credentials must be wiped and
        // .claude.json reset to {} so Claude Code inside the container
        // authenticates exclusively via CLAUDE_CODE_OAUTH_TOKEN.
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Token,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state2
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
    }

    #[test]
    fn switching_from_token_to_sync_forwards_fresh_host_creds() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: token mode leaves an empty state
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Token,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );

        // Operator switches to sync — host auth must now be forwarded
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(
            std::fs::read_to_string(state2.claude_account_json().unwrap())
                .unwrap()
                .contains("test@example.com")
        );
        assert_eq!(
            std::fs::read_to_string(state2.claude_state_dir().unwrap().join(".credentials.json"))
                .unwrap(),
            TEST_CREDENTIALS
        );
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
    }

    #[test]
    fn switching_from_token_to_ignore_remains_empty() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // Token mode seeds an empty state
        let (_, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Token,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Switching to ignore must keep the empty shape (no .credentials.json)
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state2
                .claude_state_dir()
                .unwrap()
                .join(".credentials.json")
                .exists()
        );
        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
    }

    #[test]
    fn sync_mode_preserves_container_auth_when_host_file_missing() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: host has auth, sync copies it
        seed_host_auth(&temp);
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Host auth disappears (e.g. user logged out)
        std::fs::remove_file(temp.path().join(".claude.json")).unwrap();
        std::fs::remove_file(temp.path().join(".claude/.credentials.json")).unwrap();

        // Container may have its own auth by now (from manual login inside)
        let container_auth = r#"{"oauthAccount":{"emailAddress":"container@example.com"}}"#;
        std::fs::write(state.claude_account_json().unwrap(), container_auth).unwrap();

        // Second run: host auth missing — container auth must be preserved
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            container_auth
        );
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
    }

    #[cfg(unix)]
    #[test]
    fn auth_file_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        let perms = std::fs::metadata(state.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            perms.mode() & 0o777,
            0o600,
            "claude.json should have 0600 permissions"
        );
        let creds_perms =
            std::fs::metadata(state.claude_state_dir().unwrap().join(".credentials.json"))
                .unwrap()
                .permissions();
        assert_eq!(
            creds_perms.mode() & 0o777,
            0o600,
            ".credentials.json should have 0600 permissions"
        );
    }

    #[cfg(unix)]
    #[test]
    fn sync_repairs_permissions_on_legacy_permissive_file() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: create the file with ignore mode (gets 0600)
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Simulate a legacy state file with permissive mode
        std::fs::set_permissions(
            state.claude_account_json().unwrap(),
            std::fs::Permissions::from_mode(0o644),
        )
        .unwrap();
        let perms = std::fs::metadata(state.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(perms.mode() & 0o777, 0o644, "precondition: file is 0644");

        // Sync with host auth — must tighten permissions
        seed_host_auth(&temp);
        let (state2, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        let perms = std::fs::metadata(state2.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            perms.mode() & 0o777,
            0o600,
            "sync should repair permissions on existing file"
        );
    }

    #[cfg(unix)]
    #[test]
    fn sync_repairs_permissions_when_host_auth_missing() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: sync with host auth to seed both files
        seed_host_auth(&temp);
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Simulate legacy permissive modes on both auth files
        std::fs::set_permissions(
            state.claude_account_json().unwrap(),
            std::fs::Permissions::from_mode(0o644),
        )
        .unwrap();
        let creds_path = state.claude_state_dir().unwrap().join(".credentials.json");
        std::fs::set_permissions(&creds_path, std::fs::Permissions::from_mode(0o644)).unwrap();

        // Remove host auth so sync takes the preserve path
        std::fs::remove_file(temp.path().join(".claude.json")).unwrap();
        std::fs::remove_file(temp.path().join(".claude/.credentials.json")).unwrap();

        // Second run: host auth missing — files preserved but permissions repaired
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);

        let json_perms = std::fs::metadata(state2.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            json_perms.mode() & 0o777,
            0o600,
            "sync should repair .claude.json permissions even when host auth is missing"
        );
        let creds_perms =
            std::fs::metadata(state2.claude_state_dir().unwrap().join(".credentials.json"))
                .unwrap()
                .permissions();
        assert_eq!(
            creds_perms.mode() & 0o777,
            0o600,
            "sync should repair .credentials.json permissions even when host auth is missing"
        );
    }

    // ── Symlink traversal protection ────────────────────────────────────

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_claude_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: create the state directory
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Replace .claude.json with a symlink to a decoy file
        let decoy = temp.path().join("decoy.txt");
        std::fs::write(&decoy, "original").unwrap();
        std::fs::remove_file(state.claude_account_json().unwrap()).unwrap();
        std::os::unix::fs::symlink(&decoy, state.claude_account_json().unwrap()).unwrap();

        // Sync should refuse to write through the symlink
        let err = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "original");
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_credentials_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: create the state directory with credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Replace .credentials.json with a symlink
        let decoy = temp.path().join("decoy-creds.txt");
        std::fs::write(&decoy, "secret").unwrap();
        let creds_path = state.claude_state_dir().unwrap().join(".credentials.json");
        std::fs::remove_file(&creds_path).unwrap();
        std::os::unix::fs::symlink(&decoy, &creds_path).unwrap();

        // Sync should refuse to write through the symlink
        let err = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "secret");
    }
}

#[cfg(test)]
mod codex_auth_tests {
    use crate::instance::RoleState;
    use crate::manifest::RoleManifest;
    use tempfile::tempdir;

    fn manifest_with_codex_model(temp: &tempfile::TempDir, model: Option<&str>) -> RoleManifest {
        let codex_section = model.map_or_else(
            || "[codex]\n".to_string(),
            |m| format!("[codex]\nmodel = \"{m}\"\n"),
        );
        std::fs::write(
            temp.path().join("jackin.role.toml"),
            format!(
                r#"dockerfile = "Dockerfile"
agents = ["codex"]

{codex_section}"#
            ),
        )
        .unwrap();
        std::fs::write(
            temp.path().join("Dockerfile"),
            "FROM projectjackin/construct:trixie\n",
        )
        .unwrap();
        RoleManifest::load(temp.path()).unwrap()
    }

    #[test]
    fn provisions_minimal_config_when_no_model() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        RoleState::provision_codex_auth(&path, &manifest).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("approval_policy = \"never\""));
        assert!(content.contains("sandbox_mode = \"danger-full-access\""));
        assert!(!content.contains("model ="));
    }

    #[test]
    fn provisions_config_with_model_when_set() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, Some("gpt-5"));
        let path = temp.path().join("config.toml");

        RoleState::provision_codex_auth(&path, &manifest).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("model = \"gpt-5\""));
    }

    // Pin the symlink-rejection invariant for codex config.toml. The host
    // file is bind-mounted RW into the container, so a compromised agent
    // could replace it with a symlink between launches; without this
    // check the next provisioning call would follow the symlink and
    // overwrite the target on the host.
    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_codex_config_toml() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        let decoy = temp.path().join("decoy.txt");
        std::fs::write(&decoy, "secret").unwrap();
        std::os::unix::fs::symlink(&decoy, &path).unwrap();

        let err = RoleState::provision_codex_auth(&path, &manifest).unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched.
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "secret");
    }

    #[cfg(unix)]
    #[test]
    fn codex_config_toml_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        RoleState::provision_codex_auth(&path, &manifest).unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "codex config.toml must be 0o600, got {mode:o}");
    }

    // Pin the no-churn contract: when the manifest hasn't changed, a
    // second `provision_codex_auth` call must not modify the file. This
    // guards against silent operator-edit clobbering on every launch
    // (and lets future "preserve operator edits" logic be added without
    // breaking the simple case).
    #[test]
    fn skips_write_when_existing_content_matches() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, Some("gpt-5"));
        let path = temp.path().join("config.toml");

        RoleState::provision_codex_auth(&path, &manifest).unwrap();
        let mtime_first = std::fs::metadata(&path).unwrap().modified().unwrap();

        // Sleep just enough to make a second mtime distinguishable on
        // filesystems with second-resolution timestamps.
        std::thread::sleep(std::time::Duration::from_millis(1100));
        RoleState::provision_codex_auth(&path, &manifest).unwrap();
        let mtime_second = std::fs::metadata(&path).unwrap().modified().unwrap();

        assert_eq!(
            mtime_first, mtime_second,
            "no-op provisioning must not touch the file"
        );
    }

    #[test]
    fn rewrites_when_manifest_model_changes() {
        let temp = tempdir().unwrap();
        let path = temp.path().join("config.toml");

        let manifest_a = manifest_with_codex_model(&temp, Some("gpt-5"));
        RoleState::provision_codex_auth(&path, &manifest_a).unwrap();
        assert!(std::fs::read_to_string(&path).unwrap().contains("gpt-5"));

        // Re-write the manifest with a different model.
        let manifest_b = manifest_with_codex_model(&temp, Some("o3"));
        RoleState::provision_codex_auth(&path, &manifest_b).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("o3"));
        assert!(!content.contains("gpt-5"));
    }
}
