use super::{AuthProvisionOutcome, RoleState};
use crate::config::AuthForwardMode;
use std::path::Path;

impl RoleState {
    /// Provision Codex's host-side `config.toml` (always written) and,
    /// under `auth_forward = sync`, its `auth.json` (copied from the
    /// host's `~/.codex/auth.json` when present, deleted under `ignore`
    /// / `api_key`).
    ///
    /// The generated `config.toml` sets `approval_policy = "never"` and
    /// `sandbox_mode = "danger-full-access"` to match the operator
    /// contract jackin already accepts for Claude
    /// (`--dangerously-skip-permissions`): once the operator has
    /// chosen to drop the agent into the container, jackin treats
    /// the container as the scope of untrusted-AI execution.
    /// Codex's internal approval prompt would add per-action friction
    /// without changing what the agent can reach (workspace mounts,
    /// the network namespace, the `DinD` sidecar).
    ///
    /// `auth.json` semantics mirror Claude's `.credentials.json` for
    /// the file-mount surface; in-container `codex login` writes are
    /// only persisted across container removal when a sync mount
    /// already exists at launch (a host file at `~/.codex/auth.json`).
    ///   * **Sync** + host file present → copy with `0600` perms,
    ///     return `Synced`.
    ///   * **Sync** + host file absent → leave any existing role-state
    ///     `auth.json` untouched (it may survive from a prior synced
    ///     run), return `HostMissing`.
    ///   * **`ApiKey`** → wipe the role-state `auth.json` (the agent
    ///     authenticates via `OPENAI_API_KEY`; a forwarded auth.json
    ///     would let it silently fall back to OAuth credentials the
    ///     operator chose to bypass), return `TokenMode`.
    ///   * **`OAuthToken`** → unreachable in production: parser-rejected
    ///     for Codex (Task 6). Defensive arm returns `TokenMode` without
    ///     touching role-state files.
    ///   * **Ignore** → delete the role-state `auth.json` if present,
    ///     return `Skipped`.
    ///
    /// Returns `(outcome, mounted_auth_json)` where `mounted_auth_json` is
    /// the role-state `auth.json` path when it should be bind-mounted into
    /// the container (file exists post-call), or `None` when the mount must
    /// be skipped (Ignore wiped it / Sync host-missing with no prior file /
    /// Token mode with no prior file). Centralising the decision here means
    /// `RoleState::prepare` does not need to re-stat the file or reason
    /// about which outcome implies which mount state.
    pub(super) fn provision_codex_auth(
        config_toml: &std::path::Path,
        auth_json: &std::path::Path,
        manifest: &crate::manifest::RoleManifest,
        mode: AuthForwardMode,
        host_home: &Path,
    ) -> anyhow::Result<(AuthProvisionOutcome, Option<std::path::PathBuf>)> {
        use std::fmt::Write;

        let mut content = String::from(
            "# Generated by jackin; do not edit.\n\
             approval_policy = \"never\"\n\
             sandbox_mode = \"danger-full-access\"\n",
        );

        if let Some(codex_cfg) = manifest.codex.as_ref()
            && let Some(model) = &codex_cfg.model
        {
            writeln!(content, "model = \"{model}\"").expect("string formatting cannot fail");
        }

        // Skip the write when content matches what's already on disk so
        // operator-edited files aren't churned on every launch (they will
        // still be regenerated when manifest content changes — e.g. a new
        // [codex].model — which is the intended behaviour for a "do not
        // edit" file).
        if !std::fs::read_to_string(config_toml).is_ok_and(|existing| existing == content) {
            write_private_file(config_toml, &content)?;
        }

        // Reject any pre-existing symlink at the role-state auth.json path
        // BEFORE branching on mode. The host bind-mounts this file RW into
        // the container, so a compromised role could otherwise replace it
        // with a symlink between launches and trick subsequent provisioning
        // calls into reading/writing/deleting through the symlink.
        if auth_json.exists() {
            reject_symlink(auth_json)?;
        }

        let host_auth_json = host_home.join(".codex/auth.json");
        let outcome = match mode {
            // OAuthToken is parser-rejected for Codex (Task 6), so this arm
            // is unreachable in production — kept for match exhaustiveness
            // and to preserve historical no-wipe behavior if a config ever
            // bypasses the parser. Treated as TokenMode without touching
            // role-state files.
            AuthForwardMode::OAuthToken => AuthProvisionOutcome::TokenMode,
            // ApiKey is env-driven (OPENAI_API_KEY): the agent inside the
            // container must NOT see a forwarded auth.json from a prior
            // Sync run, otherwise it would silently fall back to OAuth
            // credentials that the operator has explicitly chosen to
            // bypass. Wipe role-state auth.json identically to Ignore,
            // and surface the env-driven nature via TokenMode.
            AuthForwardMode::ApiKey => {
                wipe_codex_state(auth_json)?;
                AuthProvisionOutcome::TokenMode
            }
            AuthForwardMode::Ignore => {
                wipe_codex_state(auth_json)?;
                AuthProvisionOutcome::Skipped
            }
            AuthForwardMode::Sync => match std::fs::read_to_string(&host_auth_json) {
                Ok(content) => {
                    write_private_file(auth_json, &content)?;
                    AuthProvisionOutcome::Synced
                }
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                    if auth_json.exists() {
                        repair_permissions(auth_json);
                    }
                    AuthProvisionOutcome::HostMissing
                }
                Err(e) => {
                    // Surface unexpected read errors (EACCES, EIO, ENOTDIR,
                    // …) instead of misdiagnosing them as "host missing"
                    // and silently dropping the operator into a re-login
                    // loop they cannot escape until they notice the bad
                    // permission/dir/etc. on `~/.codex/auth.json`.
                    anyhow::bail!(
                        "failed to read host {}: {e} (run with --debug to capture the underlying error)",
                        host_auth_json.display()
                    );
                }
            },
        };

        let mounted_auth_json = match outcome {
            AuthProvisionOutcome::Synced => Some(auth_json.to_path_buf()),
            AuthProvisionOutcome::Skipped => None,
            AuthProvisionOutcome::HostMissing | AuthProvisionOutcome::TokenMode => {
                auth_json.exists().then(|| auth_json.to_path_buf())
            }
        };
        Ok((outcome, mounted_auth_json))
    }
}

impl RoleState {
    /// Provision Claude's host-side auth files (`account_json` and
    /// `credentials_json`) according to the chosen auth-forwarding
    /// strategy and report whether the files should be bind-mounted
    /// into the container under `/jackin/claude/`.
    ///
    /// Returns `(outcome, forward_auth)`. `forward_auth` controls
    /// whether the launcher will bind-mount the files; the underlying
    /// host paths are unconditionally tracked on `RoleState` so callers
    /// can still inspect them (tests, debug output, future migration).
    ///
    ///   * **Sync** + host file present → write both files at `0o600`,
    ///     `forward_auth = true`. Container auth flows from host.
    ///   * **Sync** + host file absent → preserve any existing role-
    ///     state files (may carry forward an in-container login),
    ///     `forward_auth = true`. The launcher then mounts only the
    ///     files that actually exist on disk.
    ///   * **`Ignore`/`ApiKey`/`OAuthToken`** → wipe both role-state
    ///     files (revokes any forwarded creds from a prior Sync) and
    ///     `forward_auth = false`. The agent authenticates via env vars
    ///     (`CLAUDE_CODE_OAUTH_TOKEN` / `ANTHROPIC_API_KEY`) or via a
    ///     fresh in-container login that lives only in the writable
    ///     layer (lost on `docker rm`, by design).
    ///
    /// On macOS the host credentials live in the system Keychain
    /// ("Claude Code-credentials"), not in a file. On Linux they are
    /// stored at `~/.claude/.credentials.json`.
    pub(super) fn provision_claude_auth(
        account_json: &Path,
        credentials_json: &Path,
        mode: AuthForwardMode,
        host_home: &Path,
    ) -> anyhow::Result<(AuthProvisionOutcome, bool)> {
        let host_claude_json = host_home.join(".claude.json");

        let outcome = match mode {
            AuthForwardMode::Ignore => {
                // Always ensure a clean slate — if switching from sync/token
                // to ignore, the previously forwarded credentials must be
                // revoked.
                wipe_claude_state(account_json, credentials_json)?;
                AuthProvisionOutcome::Skipped
            }
            // ApiKey and OAuthToken share filesystem behavior: both env-driven
            // modes provision the same empty shape as Ignore — the agent
            // inside the container authenticates via env vars, not via
            // filesystem credentials. Switching from sync → token/api_key must
            // still wipe any previously forwarded creds. They differ only in
            // which env var the launcher sets (CLAUDE_CODE_OAUTH_TOKEN vs
            // ANTHROPIC_API_KEY); host-state provisioning is identical.
            AuthForwardMode::OAuthToken | AuthForwardMode::ApiKey => {
                wipe_claude_state(account_json, credentials_json)?;
                AuthProvisionOutcome::TokenMode
            }
            AuthForwardMode::Sync => {
                if let Some(creds) = read_host_credentials(host_home) {
                    copy_host_claude_json(&host_claude_json, account_json)?;
                    write_private_file(credentials_json, &creds)?;
                    AuthProvisionOutcome::Synced
                } else {
                    // Host has no auth — leave the container's existing
                    // files untouched (they may carry credentials from a
                    // previous manual login). Bootstrap an empty
                    // account.json if nothing exists yet so the file is
                    // always present after `prepare`, simplifying
                    // inspection callers.
                    if !account_json.exists() {
                        write_private_file(account_json, "{}")?;
                    }
                    // Repair permissions on pre-existing auth files that
                    // may have legacy permissive modes (e.g. 0644).
                    repair_permissions(account_json);
                    repair_permissions(credentials_json);
                    AuthProvisionOutcome::HostMissing
                }
            }
        };

        // Sync-mode outcomes forward auth state; env-driven modes don't.
        // The launcher additionally checks file existence at mount time
        // (host-missing sync may have neither file on disk).
        let forward_auth = matches!(
            outcome,
            AuthProvisionOutcome::Synced | AuthProvisionOutcome::HostMissing
        );
        Ok((outcome, forward_auth))
    }
}

/// Copy the host's `.claude.json` into the container state, or write `{}`
/// if the host file doesn't exist.
fn copy_host_claude_json(host_path: &Path, dest_path: &Path) -> anyhow::Result<()> {
    let content = std::fs::read_to_string(host_path).unwrap_or_else(|_| "{}".to_string());
    write_private_file(dest_path, &content)
}

/// Wipe the container's Claude auth state to a clean empty shape.
///
/// Used by every non-Sync mode (`Ignore`, `OAuthToken`, `ApiKey`) — they
/// all must guarantee no stale `.credentials.json` survives from a
/// prior Sync run, and that `.claude.json` is `{}` so Claude Code
/// inside the container authenticates exclusively via env vars (or
/// fresh login) rather than re-using forwarded credentials.
///
/// `account_json` is rewritten only when its current contents differ
/// from `{}` (or the file doesn't exist), to avoid touching mtime on
/// every launch.
fn wipe_claude_state(account_json: &Path, credentials_json: &Path) -> anyhow::Result<()> {
    if !account_json.exists() || std::fs::read_to_string(account_json)? != "{}" {
        write_private_file(account_json, "{}")?;
    }
    if credentials_json.exists() {
        std::fs::remove_file(credentials_json)?;
    }
    Ok(())
}

/// Wipe the container's Codex auth state to a clean empty shape.
///
/// Used by every non-Sync mode that owns the file (`Ignore`, `ApiKey`)
/// — they must guarantee no stale `auth.json` from a prior Sync run
/// survives so the agent inside the container authenticates exclusively
/// via env vars (or fresh `codex login`) rather than re-using forwarded
/// credentials.
///
/// Unlike `wipe_claude_state`, there is no companion "account" file to
/// reset — Codex's role-state surface is just `auth.json`. Removing it
/// is sufficient because the launcher only bind-mounts `auth.json` when
/// `provision_codex_auth` reports it exists post-call (see
/// `mounted_auth_json` in the caller).
fn wipe_codex_state(auth_json: &Path) -> anyhow::Result<()> {
    if auth_json.exists() {
        std::fs::remove_file(auth_json)?;
    }
    Ok(())
}

/// Read the host's Claude Code OAuth credentials.
///
/// Checks the file-based store at `~/.claude/.credentials.json` first
/// (used on Linux, and makes the function testable with temp dirs).
/// Falls back to the macOS Keychain ("Claude Code-credentials") when
/// the file is absent and `host_home` matches the real home directory.
fn read_host_credentials(host_home: &Path) -> Option<String> {
    // File-based credentials (Linux, or macOS with an explicit export).
    let creds_path = host_home.join(".claude/.credentials.json");
    if let Ok(content) = std::fs::read_to_string(creds_path) {
        return Some(content);
    }

    // macOS Keychain fallback — only attempted when host_home is the
    // real home directory.  This keeps tests hermetic (they use temp
    // dirs) while still supporting the Keychain in production.
    #[cfg(target_os = "macos")]
    {
        let real_home = directories::BaseDirs::new().map(|b| b.home_dir().to_path_buf());
        if real_home.as_deref() == Some(host_home) {
            let output = std::process::Command::new("security")
                .args([
                    "find-generic-password",
                    "-s",
                    "Claude Code-credentials",
                    "-w",
                ])
                .output()
                .ok()?;
            if output.status.success() {
                let creds = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !creds.is_empty() {
                    return Some(creds);
                }
            }
        }
    }

    None
}

/// Reject symlinks at `path` to prevent a compromised role from
/// redirecting host-side writes to arbitrary files.
///
/// The role's `.claude/` directory is mounted read-write into the
/// container, so an role could replace `.credentials.json` with a
/// symlink.  Without this check, the next `write_private_file` or
/// `repair_permissions` call would follow the symlink and overwrite
/// or chmod the target on the host.
fn reject_symlink(path: &Path) -> anyhow::Result<()> {
    // Use symlink_metadata (lstat) — regular metadata() follows symlinks.
    if let Ok(meta) = std::fs::symlink_metadata(path) {
        anyhow::ensure!(
            !meta.file_type().is_symlink(),
            "refusing to write through symlink at {}; \
             this may indicate a compromised role state — \
             remove the symlink and retry",
            path.display()
        );
    }
    Ok(())
}

/// Write a file with restricted permissions (`0o600` on Unix) since it
/// may contain authentication credentials.
///
/// Rejects symlinks to prevent a compromised role from redirecting
/// writes to arbitrary host paths.  Uses `tempfile::NamedTempFile` to
/// create an unpredictable temp file (opened with `O_EXCL`, so a
/// pre-planted symlink at the temp path is impossible), then renames
/// it to the destination — closing the TOCTOU window entirely.
fn write_private_file(path: &Path, content: &str) -> anyhow::Result<()> {
    reject_symlink(path)?;

    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::PermissionsExt;

        let parent = path
            .parent()
            .ok_or_else(|| anyhow::anyhow!("no parent directory for {}", path.display()))?;

        // NamedTempFile uses O_EXCL internally, so it will never follow
        // a pre-planted symlink.  The random suffix makes the path
        // unpredictable.
        let mut tmp = tempfile::NamedTempFile::new_in(parent)?;
        tmp.write_all(content.as_bytes())?;
        std::fs::set_permissions(tmp.path(), std::fs::Permissions::from_mode(0o600))?;
        tmp.persist(path)?;
    }
    #[cfg(not(unix))]
    {
        std::fs::write(path, content)?;
    }
    Ok(())
}

/// Tighten permissions on an existing file to `0o600` if it exists.
/// Refuses to operate on symlinks.  No-op on non-Unix or if the file
/// doesn't exist.
fn repair_permissions(path: &Path) {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        // Use symlink_metadata so we don't follow symlinks.
        if let Ok(meta) = std::fs::symlink_metadata(path) {
            if meta.file_type().is_symlink() {
                eprintln!(
                    "[jackin] warning: refusing to chmod symlink at {}",
                    path.display()
                );
                return;
            }
            if meta.is_file() {
                let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
            }
        }
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
}

#[cfg(test)]
mod tests {
    use crate::config::AuthForwardMode;
    use crate::instance::{AuthProvisionOutcome, RoleState};
    use crate::paths::JackinPaths;
    use tempfile::tempdir;

    const TEST_CREDENTIALS: &str =
        r#"{"claudeAiOauth":{"accessToken":"test","refreshToken":"test"}}"#;

    /// Set up a fake host auth environment in the temp dir.
    fn seed_host_auth(temp: &tempfile::TempDir) {
        std::fs::write(
            temp.path().join(".claude.json"),
            r#"{"oauthAccount":{"emailAddress":"test@example.com"}}"#,
        )
        .unwrap();
        let creds_dir = temp.path().join(".claude");
        std::fs::create_dir_all(&creds_dir).unwrap();
        std::fs::write(creds_dir.join(".credentials.json"), TEST_CREDENTIALS).unwrap();
    }

    fn simple_manifest(temp: &tempfile::TempDir) -> crate::manifest::RoleManifest {
        std::fs::write(
            temp.path().join("jackin.role.toml"),
            r#"dockerfile = "Dockerfile"

[claude]
plugins = []
"#,
        )
        .unwrap();
        std::fs::write(
            temp.path().join("Dockerfile"),
            "FROM projectjackin/construct:trixie\n",
        )
        .unwrap();
        crate::manifest::RoleManifest::load(temp.path()).unwrap()
    }

    // ── Auth forwarding tests ───────────────────────────────────────────

    // ── Auth forwarding tests ───────────────────────────────────────────

    #[test]
    fn ignore_mode_writes_empty_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(!state.claude_credentials_json().unwrap().exists());
        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
    }

    #[test]
    fn sync_mode_copies_host_auth_on_first_run() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert!(
            std::fs::read_to_string(state.claude_account_json().unwrap())
                .unwrap()
                .contains("test@example.com")
        );
        assert_eq!(
            std::fs::read_to_string(state.claude_credentials_json().unwrap()).unwrap(),
            TEST_CREDENTIALS
        );
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
    }

    #[test]
    fn sync_mode_falls_back_to_empty_json_when_host_has_none() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        // No host auth seeded
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(!state.claude_credentials_json().unwrap().exists());
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
    }

    #[test]
    fn sync_mode_overwrites_existing() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run with host auth
        seed_host_auth(&temp);
        let (state, outcome1) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(outcome1, AuthProvisionOutcome::Synced);

        // Simulate container modifying its own .claude.json
        std::fs::write(
            state.claude_account_json().unwrap(),
            r#"{"container":"data"}"#,
        )
        .unwrap();

        // Update host credentials
        let updated_creds = r#"{"claudeAiOauth":{"accessToken":"new","refreshToken":"new"}}"#;
        std::fs::write(temp.path().join(".claude/.credentials.json"), updated_creds).unwrap();

        // Second run: should overwrite with host content
        let (state2, outcome2) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state2.claude_credentials_json().unwrap()).unwrap(),
            updated_creds
        );
        assert_eq!(outcome2, AuthProvisionOutcome::Synced);
    }

    // ── Mode transition tests ───────────────────────────────────────────

    #[test]
    fn switching_from_sync_to_ignore_revokes_forwarded_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: sync mode writes credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(state.claude_credentials_json().unwrap().exists());

        // Operator switches to ignore — credentials must be wiped
        let (state2, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(!state2.claude_credentials_json().unwrap().exists());
    }

    #[test]
    fn token_mode_writes_empty_json_and_no_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        // Seed host auth — token mode must NOT copy it.
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::OAuthToken,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(
            !state.claude_credentials_json().unwrap().exists(),
            "token mode must not write .credentials.json"
        );
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
    }

    /// `ApiKey` shares the wipe-state contract with `OAuthToken` (both
    /// env-driven modes) but is dispatched as a distinct enum variant —
    /// pin its filesystem behavior independently so a future per-mode
    /// split can't silently break the `ApiKey` path. The pre-seeded
    /// `.credentials.json` here doubles as a "switching from sync to
    /// `ApiKey` revokes forwarded creds" assertion: the file existed
    /// before the `ApiKey` run and must be gone after.
    #[test]
    fn api_key_mode_wipes_credentials_and_writes_empty_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        // Seed host auth — api_key mode must NOT copy it.
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: sync mode writes credentials we'll then need to verify
        // get wiped under api_key.
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(
            state.claude_credentials_json().unwrap().exists(),
            "precondition: sync seeded .credentials.json"
        );

        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::ApiKey,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}",
            "api_key mode must reset .claude.json to empty object"
        );
        assert!(
            !state2.claude_credentials_json().unwrap().exists(),
            "api_key mode must wipe .credentials.json"
        );
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
    }

    #[test]
    fn switching_from_sync_to_token_revokes_forwarded_credentials() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: sync mode writes credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(state.claude_credentials_json().unwrap().exists());

        // Operator switches to token — credentials must be wiped and
        // .claude.json reset to {} so Claude Code inside the container
        // authenticates exclusively via CLAUDE_CODE_OAUTH_TOKEN.
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::OAuthToken,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(!state2.claude_credentials_json().unwrap().exists());
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
    }

    #[test]
    fn switching_from_token_to_sync_forwards_fresh_host_creds() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: token mode leaves an empty state
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::OAuthToken,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state.claude_account_json().unwrap()).unwrap(),
            "{}"
        );

        // Operator switches to sync — host auth must now be forwarded
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert!(
            std::fs::read_to_string(state2.claude_account_json().unwrap())
                .unwrap()
                .contains("test@example.com")
        );
        assert_eq!(
            std::fs::read_to_string(state2.claude_credentials_json().unwrap()).unwrap(),
            TEST_CREDENTIALS
        );
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
    }

    #[test]
    fn switching_from_token_to_ignore_remains_empty() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // Token mode seeds an empty state
        let (_, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::OAuthToken,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Switching to ignore must keep the empty shape (no .credentials.json)
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            "{}"
        );
        assert!(!state2.claude_credentials_json().unwrap().exists());
        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
    }

    #[test]
    fn sync_mode_preserves_container_auth_when_host_file_missing() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: host has auth, sync copies it
        seed_host_auth(&temp);
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Host auth disappears (e.g. user logged out)
        std::fs::remove_file(temp.path().join(".claude.json")).unwrap();
        std::fs::remove_file(temp.path().join(".claude/.credentials.json")).unwrap();

        // Container may have its own auth by now (from manual login inside)
        let container_auth = r#"{"oauthAccount":{"emailAddress":"container@example.com"}}"#;
        std::fs::write(state.claude_account_json().unwrap(), container_auth).unwrap();

        // Second run: host auth missing — container auth must be preserved
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(
            std::fs::read_to_string(state2.claude_account_json().unwrap()).unwrap(),
            container_auth
        );
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
    }

    #[cfg(unix)]
    #[test]
    fn auth_file_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        let perms = std::fs::metadata(state.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            perms.mode() & 0o777,
            0o600,
            "claude.json should have 0600 permissions"
        );
        let creds_perms = std::fs::metadata(state.claude_credentials_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            creds_perms.mode() & 0o777,
            0o600,
            ".credentials.json should have 0600 permissions"
        );
    }

    #[cfg(unix)]
    #[test]
    fn sync_repairs_permissions_on_legacy_permissive_file() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: create the file with ignore mode (gets 0600)
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Ignore,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Simulate a legacy state file with permissive mode
        std::fs::set_permissions(
            state.claude_account_json().unwrap(),
            std::fs::Permissions::from_mode(0o644),
        )
        .unwrap();
        let perms = std::fs::metadata(state.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(perms.mode() & 0o777, 0o644, "precondition: file is 0644");

        // Sync with host auth — must tighten permissions
        seed_host_auth(&temp);
        let (state2, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        let perms = std::fs::metadata(state2.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            perms.mode() & 0o777,
            0o600,
            "sync should repair permissions on existing file"
        );
    }

    #[cfg(unix)]
    #[test]
    fn sync_repairs_permissions_when_host_auth_missing() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        let manifest = simple_manifest(&temp);

        // First run: sync with host auth to seed both files
        seed_host_auth(&temp);
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Simulate legacy permissive modes on both auth files
        std::fs::set_permissions(
            state.claude_account_json().unwrap(),
            std::fs::Permissions::from_mode(0o644),
        )
        .unwrap();
        let creds_path = state.claude_credentials_json().unwrap();
        std::fs::set_permissions(creds_path, std::fs::Permissions::from_mode(0o644)).unwrap();

        // Remove host auth so sync takes the preserve path
        std::fs::remove_file(temp.path().join(".claude.json")).unwrap();
        std::fs::remove_file(temp.path().join(".claude/.credentials.json")).unwrap();

        // Second run: host auth missing — files preserved but permissions repaired
        let (state2, outcome) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);

        let json_perms = std::fs::metadata(state2.claude_account_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            json_perms.mode() & 0o777,
            0o600,
            "sync should repair .claude.json permissions even when host auth is missing"
        );
        let creds_perms = std::fs::metadata(state2.claude_credentials_json().unwrap())
            .unwrap()
            .permissions();
        assert_eq!(
            creds_perms.mode() & 0o777,
            0o600,
            "sync should repair .credentials.json permissions even when host auth is missing"
        );
    }

    // ── Symlink traversal protection ────────────────────────────────────

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_claude_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: create the state directory
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Replace .claude.json with a symlink to a decoy file
        let decoy = temp.path().join("decoy.txt");
        std::fs::write(&decoy, "original").unwrap();
        std::fs::remove_file(state.claude_account_json().unwrap()).unwrap();
        std::os::unix::fs::symlink(&decoy, state.claude_account_json().unwrap()).unwrap();

        // Sync should refuse to write through the symlink
        let err = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "original");
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_credentials_json() {
        let temp = tempdir().unwrap();
        let paths = JackinPaths::for_tests(temp.path());
        seed_host_auth(&temp);
        let manifest = simple_manifest(&temp);

        // First run: create the state directory with credentials
        let (state, _) = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap();

        // Replace .credentials.json with a symlink
        let decoy = temp.path().join("decoy-creds.txt");
        std::fs::write(&decoy, "secret").unwrap();
        let creds_path = state.claude_credentials_json().unwrap();
        std::fs::remove_file(creds_path).unwrap();
        std::os::unix::fs::symlink(&decoy, creds_path).unwrap();

        // Sync should refuse to write through the symlink
        let err = RoleState::prepare(
            &paths,
            "jackin-agent-smith",
            &manifest,
            AuthForwardMode::Sync,
            temp.path(),
            crate::agent::Agent::Claude,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "secret");
    }
}

#[cfg(test)]
mod codex_auth_tests {
    use crate::config::AuthForwardMode;
    use crate::instance::{AuthProvisionOutcome, RoleState};
    use crate::manifest::RoleManifest;
    use std::path::Path;
    use tempfile::tempdir;

    /// Test wrapper that pins config.toml provisioning under a fixed
    /// (Ignore, no-host-codex) auth context, so the legacy assertions
    /// stay focused on the config.toml contract. The auth.json half is
    /// exercised by the dedicated `sync_*`, `ignore_*`, `token_*`,
    /// `switching_*`, and `rejects_symlink_at_auth_json_*` tests below.
    fn provision_config_only(
        config_toml: &Path,
        manifest: &RoleManifest,
    ) -> anyhow::Result<AuthProvisionOutcome> {
        let auth_json = config_toml.with_file_name("auth.json");
        let host_home = Path::new("/nonexistent-host-home-for-config-only-tests");
        let (outcome, _) = RoleState::provision_codex_auth(
            config_toml,
            &auth_json,
            manifest,
            AuthForwardMode::Ignore,
            host_home,
        )?;
        Ok(outcome)
    }

    fn manifest_with_codex_model(temp: &tempfile::TempDir, model: Option<&str>) -> RoleManifest {
        let codex_section = model.map_or_else(
            || "[codex]\n".to_string(),
            |m| format!("[codex]\nmodel = \"{m}\"\n"),
        );
        std::fs::write(
            temp.path().join("jackin.role.toml"),
            format!(
                r#"dockerfile = "Dockerfile"
agents = ["codex"]

{codex_section}"#
            ),
        )
        .unwrap();
        std::fs::write(
            temp.path().join("Dockerfile"),
            "FROM projectjackin/construct:trixie\n",
        )
        .unwrap();
        RoleManifest::load(temp.path()).unwrap()
    }

    #[test]
    fn provisions_minimal_config_when_no_model() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        provision_config_only(&path, &manifest).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("approval_policy = \"never\""));
        assert!(content.contains("sandbox_mode = \"danger-full-access\""));
        assert!(!content.contains("model ="));
    }

    #[test]
    fn provisions_config_with_model_when_set() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, Some("gpt-5"));
        let path = temp.path().join("config.toml");

        provision_config_only(&path, &manifest).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("model = \"gpt-5\""));
    }

    // Pin the symlink-rejection invariant for codex config.toml. The host
    // file is bind-mounted RW into the container, so a compromised agent
    // could replace it with a symlink between launches; without this
    // check the next provisioning call would follow the symlink and
    // overwrite the target on the host.
    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_codex_config_toml() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        let decoy = temp.path().join("decoy.txt");
        std::fs::write(&decoy, "secret").unwrap();
        std::os::unix::fs::symlink(&decoy, &path).unwrap();

        let err = provision_config_only(&path, &manifest).unwrap_err();
        assert!(
            err.to_string().contains("symlink"),
            "expected symlink error, got: {err}"
        );

        // Decoy file must be untouched.
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "secret");
    }

    #[cfg(unix)]
    #[test]
    fn codex_config_toml_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let path = temp.path().join("config.toml");

        provision_config_only(&path, &manifest).unwrap();

        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "codex config.toml must be 0o600, got {mode:o}");
    }

    // Pin the no-churn contract: when the manifest hasn't changed, a
    // second `provision_codex_auth` call must not modify the file. This
    // guards against silent operator-edit clobbering on every launch
    // (and lets future "preserve operator edits" logic be added without
    // breaking the simple case).
    #[test]
    fn skips_write_when_existing_content_matches() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, Some("gpt-5"));
        let path = temp.path().join("config.toml");

        provision_config_only(&path, &manifest).unwrap();
        let mtime_first = std::fs::metadata(&path).unwrap().modified().unwrap();

        // Sleep just enough to make a second mtime distinguishable on
        // filesystems with second-resolution timestamps.
        std::thread::sleep(std::time::Duration::from_millis(1100));
        provision_config_only(&path, &manifest).unwrap();
        let mtime_second = std::fs::metadata(&path).unwrap().modified().unwrap();

        assert_eq!(
            mtime_first, mtime_second,
            "no-op provisioning must not touch the file"
        );
    }

    #[test]
    fn rewrites_when_manifest_model_changes() {
        let temp = tempdir().unwrap();
        let path = temp.path().join("config.toml");

        let manifest_a = manifest_with_codex_model(&temp, Some("gpt-5"));
        provision_config_only(&path, &manifest_a).unwrap();
        assert!(std::fs::read_to_string(&path).unwrap().contains("gpt-5"));

        // Re-write the manifest with a different model.
        let manifest_b = manifest_with_codex_model(&temp, Some("o3"));
        provision_config_only(&path, &manifest_b).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("o3"));
        assert!(!content.contains("gpt-5"));
    }

    /// Stage a fake host home with a populated `~/.codex/auth.json` so
    /// the sync-mode tests below have a real source file to copy from.
    /// Returns the host-home root and the auth.json contents written.
    fn stage_host_auth_json(temp: &tempfile::TempDir, tail: &str) -> (std::path::PathBuf, String) {
        let host_home = temp.path().join("host_home");
        let codex_dir = host_home.join(".codex");
        std::fs::create_dir_all(&codex_dir).unwrap();
        let content = format!(
            "{{\"auth_mode\":\"chatgpt\",\"OPENAI_API_KEY\":null,\"tokens\":{{\"id_token\":\"{tail}\"}}}}",
        );
        std::fs::write(codex_dir.join("auth.json"), &content).unwrap();
        (host_home, content)
    }

    #[test]
    fn sync_copies_host_auth_json_when_present() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let (host_home, expected) = stage_host_auth_json(&temp, "abc.test");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::Synced);
        assert_eq!(std::fs::read_to_string(&auth_json).unwrap(), expected);
    }

    #[test]
    fn sync_returns_host_missing_when_host_lacks_auth_json() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let host_home = temp.path().join("host_home_without_codex_dir");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
        assert!(!auth_json.exists(), "no bootstrap file should be created");
    }

    #[test]
    fn sync_preserves_existing_role_auth_json_when_host_file_missing() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        std::fs::write(&auth_json, "{\"in_container_login\":true}").unwrap();
        let host_home = temp.path().join("empty_host_home");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::HostMissing);
        assert_eq!(
            std::fs::read_to_string(&auth_json).unwrap(),
            "{\"in_container_login\":true}",
            "in-container login state must survive sync-with-no-host"
        );
    }

    #[test]
    fn ignore_deletes_existing_role_auth_json() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        std::fs::write(&auth_json, "{\"stale\":\"creds\"}").unwrap();

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Ignore,
            Path::new("/nonexistent"),
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
        assert!(!auth_json.exists());
    }

    /// `OAuthToken` is parser-rejected for Codex (Task 6) so this arm is
    /// unreachable from operator config in production. The test pins the
    /// defensive no-wipe behavior of the `OAuthToken` arm anyway: if a
    /// parser bypass ever lands a Codex+OAuthToken config at this layer,
    /// the existing role-state `auth.json` is preserved (rather than
    /// silently destroyed) so the operator can recover.
    #[test]
    fn token_mode_leaves_role_auth_json_untouched() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        std::fs::write(&auth_json, "{\"existing\":true}").unwrap();
        let (host_home, _) = stage_host_auth_json(&temp, "should-not-be-copied");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::OAuthToken,
            &host_home,
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
        assert_eq!(
            std::fs::read_to_string(&auth_json).unwrap(),
            "{\"existing\":true}"
        );
    }

    /// `ApiKey` mode authenticates via `OPENAI_API_KEY`; a leftover
    /// `auth.json` from a prior Sync run would let Codex silently fall
    /// back to forwarded OAuth credentials that the operator has
    /// explicitly chosen to bypass. Pin the wipe contract here so a
    /// future refactor can't quietly downgrade `ApiKey` to no-op.
    #[test]
    fn api_key_mode_wipes_role_auth_json() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        std::fs::write(&auth_json, "{\"stale\":\"creds\"}").unwrap();
        // Stage a host auth.json too — api_key mode must NOT copy it,
        // and must NOT leave the stale role-state file in place either.
        let (host_home, _) = stage_host_auth_json(&temp, "should-not-be-copied");

        let (outcome, mounted) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::ApiKey,
            &host_home,
        )
        .unwrap();

        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
        assert!(
            !auth_json.exists(),
            "api_key mode must wipe role-state auth.json"
        );
        assert!(
            mounted.is_none(),
            "api_key mode must report no auth.json to mount"
        );
    }

    /// Switching from Sync (creds present on host) to `ApiKey` must wipe
    /// the synced `auth.json` so the next container start cannot fall
    /// back to forwarded OAuth credentials. Without this, an operator
    /// who toggles to `ApiKey` to use `OPENAI_API_KEY` would still be
    /// running on stale OAuth state from the previous sync run.
    #[test]
    fn switching_from_sync_to_api_key_wipes_synced_auth_json() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let (host_home, _) = stage_host_auth_json(&temp, "switch.test");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
        assert!(auth_json.exists());

        let (outcome, mounted) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::ApiKey,
            &host_home,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::TokenMode);
        assert!(!auth_json.exists(), "ApiKey must wipe prior synced creds");
        assert!(mounted.is_none());
    }

    #[cfg(unix)]
    #[test]
    fn synced_auth_json_has_restricted_permissions() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let (host_home, _) = stage_host_auth_json(&temp, "perm.test");

        RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();

        let mode = std::fs::metadata(&auth_json).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "codex auth.json must be 0o600, got {mode:o}");
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_auth_json_under_ignore() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");

        let decoy = temp.path().join("decoy.txt");
        std::fs::write(&decoy, "secret").unwrap();
        std::os::unix::fs::symlink(&decoy, &auth_json).unwrap();

        let err = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Ignore,
            Path::new("/nonexistent"),
        )
        .unwrap_err();

        assert!(
            err.to_string().contains("symlink"),
            "expected symlink rejection, got: {err}"
        );
        // Decoy file must be untouched.
        assert_eq!(std::fs::read_to_string(&decoy).unwrap(), "secret");
    }

    /// Pin symlink rejection across all credential-bearing modes via the
    /// pre-mode-dispatch check at the top of `provision_codex_auth`.
    /// Without this, a compromised role could plant a symlink at the
    /// role-state `auth.json` and have subsequent sync/token-mode
    /// provisioning bind-mount it into the container as-is.
    #[cfg(unix)]
    #[test]
    fn rejects_symlink_at_auth_json_under_sync_and_token() {
        for mode in [
            AuthForwardMode::Sync,
            AuthForwardMode::OAuthToken,
            AuthForwardMode::ApiKey,
        ] {
            let temp = tempdir().unwrap();
            let manifest = manifest_with_codex_model(&temp, None);
            let config_toml = temp.path().join("config.toml");
            let auth_json = temp.path().join("auth.json");

            let decoy = temp.path().join("decoy.txt");
            std::fs::write(&decoy, "secret").unwrap();
            std::os::unix::fs::symlink(&decoy, &auth_json).unwrap();

            let err = RoleState::provision_codex_auth(
                &config_toml,
                &auth_json,
                &manifest,
                mode,
                Path::new("/nonexistent"),
            )
            .unwrap_err();
            assert!(
                err.to_string().contains("symlink"),
                "mode {mode:?} did not reject symlink: {err}"
            );
            assert_eq!(
                std::fs::read_to_string(&decoy).unwrap(),
                "secret",
                "mode {mode:?} clobbered decoy"
            );
        }
    }

    /// Switching from Sync (creds present on host) to Ignore must wipe
    /// the synced auth.json so the next container start forces a fresh
    /// in-container login. Without this, an operator who toggles to
    /// Ignore to revoke access keeps the prior credentials accessible.
    #[test]
    fn switching_from_sync_to_ignore_wipes_synced_auth_json() {
        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let (host_home, _) = stage_host_auth_json(&temp, "rev.test");

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::Synced);
        assert!(auth_json.exists());

        let (outcome, _) = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Ignore,
            &host_home,
        )
        .unwrap();
        assert_eq!(outcome, AuthProvisionOutcome::Skipped);
        assert!(!auth_json.exists(), "Ignore must wipe prior synced creds");
    }

    /// An unreadable host `auth.json` (e.g. `chmod 0` after a `sudo
    /// codex login`) used to be silently bucketed as `HostMissing`,
    /// trapping operators in a re-login loop. Verify the EACCES path
    /// now surfaces an explicit error mentioning the host path.
    #[cfg(unix)]
    #[test]
    fn surfaces_unreadable_host_auth_json_as_error() {
        use std::os::unix::fs::PermissionsExt;

        let temp = tempdir().unwrap();
        let manifest = manifest_with_codex_model(&temp, None);
        let config_toml = temp.path().join("config.toml");
        let auth_json = temp.path().join("auth.json");
        let host_home = temp.path().join("host_home");
        let host_codex = host_home.join(".codex");
        std::fs::create_dir_all(&host_codex).unwrap();
        let host_auth_json = host_codex.join("auth.json");
        std::fs::write(&host_auth_json, "{\"auth_mode\":\"chatgpt\"}").unwrap();
        // chmod 0 — file exists but is unreadable. Skip if we can't
        // produce an unreadable file (e.g. running as root in CI).
        std::fs::set_permissions(&host_auth_json, std::fs::Permissions::from_mode(0o000)).unwrap();
        if std::fs::read_to_string(&host_auth_json).is_ok() {
            // Running as root — chmod 0 doesn't block reads. Skip.
            return;
        }

        let err = RoleState::provision_codex_auth(
            &config_toml,
            &auth_json,
            &manifest,
            AuthForwardMode::Sync,
            &host_home,
        )
        .unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("auth.json"),
            "error must mention the host path: {msg}"
        );
        assert!(
            !msg.to_lowercase().contains("not found"),
            "EACCES must not be reported as not-found: {msg}"
        );
    }
}
