//! Generated inventory of production error-ownership call sites.

use std::{fmt::Write as _, fs, path::Path};

use anyhow::{Context, Result, bail};

const PATH: &str = "plans/unified-otel-observability/worksheets/011-error-ownership-census.md";

pub(super) fn validate(root: &Path, generate: bool) -> Result<()> {
    let expected = generate_census(root)?;
    let path = root.join(PATH);
    if generate {
        fs::write(&path, expected).with_context(|| format!("writing {}", path.display()))?;
        return Ok(());
    }
    let actual = fs::read_to_string(&path)
        .with_context(|| format!("reading generated ownership census {}", path.display()))?;
    if actual == expected {
        Ok(())
    } else {
        bail!(
            "telemetry error-ownership census drift; run `cargo xtask telemetry-registry --generate`"
        )
    }
}

fn generate_census(root: &Path) -> Result<String> {
    let mut files = Vec::new();
    super::collect_source_files(&root.join("crates"), root, &mut files)?;
    let mut rows = Vec::new();
    for (path, source) in files {
        let path = path.to_string_lossy();
        let lines = source.lines().collect::<Vec<_>>();
        for (index, line) in lines.iter().enumerate() {
            let mechanism = if line.contains(".record_telemetry_error(") {
                Some("propagated `TelemetryError` carrier")
            } else if path != "crates/jackin-telemetry/src/error.rs"
                && line.contains("record_error(")
            {
                Some("immediate consumed-error owner")
            } else if line.contains(".telemetry_owned(")
                || line.contains("ConfigError::telemetry_owned")
            {
                Some("typed configuration owner")
            } else {
                None
            };
            let Some(mechanism) = mechanism else {
                continue;
            };
            let owner = if mechanism == "typed configuration owner" {
                "ConfigError".to_owned()
            } else {
                ownership_type(&lines[index..lines.len().min(index + 6)])
            };
            rows.push((path.to_string(), index + 1, mechanism, owner));
        }
    }
    rows.sort_unstable();
    let mut output = String::from(
        "# Generated error-ownership call-site census\n\nThis file is generated by `cargo xtask telemetry-registry --generate`. It inventories every production use of the generic propagated carrier, immediate consumed-error recorder, and typed configuration marker. The registry gate rejects line or ownership drift. Boundary-specific operation guards are tracked by the acceptance map, and the historical prose/error migration is reconciled by `011-site-census.md`.\n\n| Site | Decision | Bounded owner |\n|---|---|---|\n",
    );
    for (path, line, mechanism, owner) in rows {
        writeln!(output, "| `{path}:{line}` | {mechanism} | `{owner}` |")?;
    }
    Ok(output)
}

pub(super) fn ownership_type(lines: &[&str]) -> String {
    for line in lines {
        let Some((_, tail)) = line.split_once("ErrorType::") else {
            continue;
        };
        let owner = tail
            .chars()
            .take_while(|character| character.is_ascii_alphanumeric() || *character == '_')
            .collect::<String>();
        if !owner.is_empty() {
            return owner;
        }
    }
    "dynamic".to_owned()
}
