//! Golden frame corpus + truncation + capability-skew tests (plan 045).
//!
//! Binary fixtures under `corpus/` are regenerated by the ignored
//! `regenerate_corpus` test. Exhaustive matches on `ClientFrame` /
//! `ServerFrame` force a fixture when a new variant is added.

#![expect(
    clippy::unwrap_used,
    clippy::panic,
    reason = "integration corpus tests"
)]

use std::path::Path;

use jackin_protocol::attach::{
    self, ClientFrame, ClientTerminal, ClipboardImage, ClipboardImageChunk, ClipboardImageEnd,
    ClipboardImageError, ClipboardImageFormat, ClipboardImageStart, FileExportChunk, FileExportEnd,
    FileExportStart, ServerFrame, SpawnRequest,
};

fn client_samples() -> Vec<(&'static str, ClientFrame)> {
    vec![
        (
            "client_hello",
            ClientFrame::Hello {
                rows: 24,
                cols: 80,
                spawn: None,
                env: vec![],
                focus_session: None,
                terminal: ClientTerminal::default(),
            },
        ),
        (
            "client_hello_spawn_shell",
            ClientFrame::Hello {
                rows: 30,
                cols: 100,
                spawn: Some(SpawnRequest::Shell),
                env: vec![("A".into(), "1".into())],
                focus_session: Some(7),
                terminal: ClientTerminal::default(),
            },
        ),
        (
            "client_resize",
            ClientFrame::Resize {
                rows: 40,
                cols: 120,
            },
        ),
        ("client_input", ClientFrame::Input(b"hi".to_vec())),
        (
            "client_command",
            ClientFrame::Command(b"{\"k\":1}".to_vec()),
        ),
        ("client_detach", ClientFrame::Detach),
        ("client_focus_in", ClientFrame::FocusIn),
        ("client_focus_out", ClientFrame::FocusOut),
        (
            "client_clipboard_image",
            ClientFrame::ClipboardImage(ClipboardImage {
                format: ClipboardImageFormat::Png,
                bytes: vec![1, 2, 3, 4],
            }),
        ),
        (
            "client_clipboard_image_start",
            ClientFrame::ClipboardImageStart(ClipboardImageStart {
                transfer_id: 1,
                format: ClipboardImageFormat::Png,
                size: 4,
            }),
        ),
        (
            "client_clipboard_image_chunk",
            ClientFrame::ClipboardImageChunk(ClipboardImageChunk {
                transfer_id: 1,
                offset: 0,
                bytes: vec![9, 8],
            }),
        ),
        (
            "client_clipboard_image_end",
            ClientFrame::ClipboardImageEnd(ClipboardImageEnd {
                transfer_id: 1,
                sha256: [0u8; 32],
            }),
        ),
        (
            "client_clipboard_image_error",
            ClientFrame::ClipboardImageError(ClipboardImageError::Empty),
        ),
        ("client_host_notice", ClientFrame::HostNotice("n".into())),
    ]
}

fn server_samples() -> Vec<(&'static str, ServerFrame)> {
    vec![
        ("server_welcome", ServerFrame::Welcome { session_count: 3 }),
        ("server_output", ServerFrame::Output(b"out".to_vec())),
        (
            "server_session_list",
            ServerFrame::SessionList(b"[]".to_vec()),
        ),
        (
            "server_shutdown",
            ServerFrame::Shutdown {
                reason: Some("bye".into()),
            },
        ),
        ("server_bell", ServerFrame::Bell),
        (
            "server_host_open_url",
            ServerFrame::HostOpenUrl("https://example.com".into()),
        ),
        (
            "server_file_export_start",
            ServerFrame::FileExportStart(FileExportStart {
                transfer_id: 2,
                size: 10,
                source_path: "/tmp/a".into(),
                file_name: "a".into(),
                reveal_after_export: false,
                open_after_export: false,
            }),
        ),
        (
            "server_file_export_chunk",
            ServerFrame::FileExportChunk(FileExportChunk {
                transfer_id: 2,
                offset: 0,
                bytes: vec![1, 2],
            }),
        ),
        (
            "server_file_export_end",
            ServerFrame::FileExportEnd(FileExportEnd {
                transfer_id: 2,
                sha256: [0u8; 32],
            }),
        ),
        (
            "server_host_reveal_path",
            ServerFrame::HostRevealPath("/tmp/x".into()),
        ),
        (
            "server_host_stage_image_from_clipboard_path",
            ServerFrame::HostStageImageFromClipboardPath,
        ),
        (
            "server_host_paste_image_from_clipboard",
            ServerFrame::HostPasteImageFromClipboard,
        ),
        (
            "server_host_stage_image_from_clipboard",
            ServerFrame::HostStageImageFromClipboard,
        ),
    ]
}

/// Exhaustive coverage: every ClientFrame / ServerFrame arm appears in samples.
fn assert_client_sample_covers(frame: &ClientFrame) {
    match frame {
        ClientFrame::Hello { .. }
        | ClientFrame::Resize { .. }
        | ClientFrame::Input(_)
        | ClientFrame::Command(_)
        | ClientFrame::Detach
        | ClientFrame::FocusIn
        | ClientFrame::FocusOut
        | ClientFrame::ClipboardImage(_)
        | ClientFrame::ClipboardImageStart(_)
        | ClientFrame::ClipboardImageChunk(_)
        | ClientFrame::ClipboardImageEnd(_)
        | ClientFrame::ClipboardImageError(_)
        | ClientFrame::HostNotice(_) => {}
    }
}

fn assert_server_sample_covers(frame: &ServerFrame) {
    match frame {
        ServerFrame::Welcome { .. }
        | ServerFrame::Output(_)
        | ServerFrame::SessionList(_)
        | ServerFrame::Shutdown { .. }
        | ServerFrame::Bell
        | ServerFrame::HostOpenUrl(_)
        | ServerFrame::FileExportStart(_)
        | ServerFrame::FileExportChunk(_)
        | ServerFrame::FileExportEnd(_)
        | ServerFrame::HostRevealPath(_)
        | ServerFrame::HostStageImageFromClipboardPath
        | ServerFrame::HostPasteImageFromClipboard
        | ServerFrame::HostStageImageFromClipboard => {}
    }
}

#[test]
fn corpus_covers_every_client_and_server_frame_variant() {
    for (_, f) in client_samples() {
        assert_client_sample_covers(&f);
    }
    for (_, f) in server_samples() {
        assert_server_sample_covers(&f);
    }
    // Count arms via samples length vs hard minimum from enum census.
    assert!(client_samples().len() >= 13, "client samples incomplete");
    assert!(server_samples().len() >= 13, "server samples incomplete");
}

#[test]
fn golden_client_frames_round_trip_decode() {
    for (name, frame) in client_samples() {
        let bytes = attach::encode_client(frame.clone()).expect(name);
        assert!(!bytes.is_empty(), "{name}");
        let tag = bytes[0];
        let payload = bytes[5..].to_vec();
        let decoded = attach::decode_client(tag, payload)
            .unwrap_or_else(|e| panic!("{name}: decode failed: {e:#}"));
        // Detach/Focus are unit-like; compare via re-encode equality where PartialEq holds.
        assert_eq!(decoded, frame, "{name}");
        // truncations must fail closed
        for cut in [1usize, 3, bytes.len().saturating_sub(1).max(1)] {
            if cut >= bytes.len() {
                continue;
            }
            let partial = &bytes[..cut];
            if partial.is_empty() {
                continue;
            }
            let tag = partial[0];
            let payload = if partial.len() > 5 {
                partial[5..].to_vec()
            } else {
                vec![]
            };
            // short payload must not panic
            drop(attach::decode_client(tag, payload));
        }
    }
}

#[test]
fn golden_server_frames_round_trip_decode() {
    for (name, frame) in server_samples() {
        let bytes = attach::encode_server(frame.clone());
        assert!(!bytes.is_empty(), "{name}");
        let tag = bytes[0];
        let payload = bytes[5..].to_vec();
        let decoded = attach::decode_server(tag, payload)
            .unwrap_or_else(|e| panic!("{name}: decode failed: {e:#}"));
        assert_eq!(decoded, frame, "{name}");
        for cut in [1usize, 3, bytes.len().saturating_sub(1).max(1)] {
            if cut >= bytes.len() {
                continue;
            }
            let partial = &bytes[..cut];
            if partial.is_empty() {
                continue;
            }
            let tag = partial[0];
            let payload = if partial.len() > 5 {
                partial[5..].to_vec()
            } else {
                vec![]
            };
            drop(attach::decode_server(tag, payload));
        }
    }
}

/// Residual (plan 045 STOP): current Hello decoder hard-errors when the
/// focus/terminal capability tail is omitted ("hello payload ended before
/// focus kind"). Soft-default skew for older peers is not implemented yet;
/// this test pins fail-closed (clean Err, never panic) until a decoder change.
#[test]
fn skew_hello_without_trailing_capability_fields_fails_closed_cleanly() {
    let mut payload = Vec::new();
    payload.extend_from_slice(&24u16.to_be_bytes());
    payload.extend_from_slice(&80u16.to_be_bytes());
    payload.push(0); // spawn none
    payload.extend_from_slice(&0u16.to_be_bytes()); // agent len
    payload.extend_from_slice(&0u16.to_be_bytes()); // env count
    // no focus / terminal tail
    let err = attach::decode_client(attach::TAG_HELLO, payload)
        .expect_err("current decoder hard-errors on short Hello (skew residual)");
    let msg = format!("{err:#}");
    assert!(
        msg.contains("focus") || msg.contains("short") || msg.contains("ended"),
        "expected focus-tail/short error, got: {msg}"
    );
}

#[test]
fn skew_unknown_client_tag_0xfe_returns_clean_error() {
    let err = attach::decode_client(0xFE, vec![1, 2, 3]).expect_err("unknown tag must error");
    let msg = format!("{err:#}");
    assert!(
        msg.to_lowercase().contains("unknown") || msg.to_lowercase().contains("tag"),
        "error should name unknown tag: {msg}"
    );
}

#[test]
fn skew_unknown_server_tag_0xfe_returns_clean_error() {
    let err = attach::decode_server(0xFE, vec![1, 2, 3]).expect_err("unknown tag must error");
    let msg = format!("{err:#}");
    assert!(
        msg.to_lowercase().contains("unknown") || msg.to_lowercase().contains("tag"),
        "error should name unknown tag: {msg}"
    );
}

#[test]
#[ignore = "run manually to rewrite binary corpus fixtures under tests/corpus/"]
fn regenerate_corpus() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus");
    std::fs::create_dir_all(&dir).unwrap();
    for (name, frame) in client_samples() {
        let bytes = attach::encode_client(frame).unwrap();
        std::fs::write(dir.join(format!("{name}.bin")), bytes).unwrap();
    }
    for (name, frame) in server_samples() {
        let bytes = attach::encode_server(frame);
        std::fs::write(dir.join(format!("{name}.bin")), bytes).unwrap();
    }
}
