// Auto-generated by BoltFFI. Do not edit.
// swiftlint:disable all
// swiftformat:disable all

import Foundation
import JackinUsageFFI

public struct FfiError: Error {
    public let message: String

    public init(message: String) {
        self.message = message
    }
}

/// Open configuration from Swift (paths only — no credentials).
public struct OpenConfig: Hashable, Equatable, Sendable {
    /// Optional data-dir override for hermetic tests/smoke only. Production is `None`.
    public var dataDirOverride: String?
    /// Optional config-root override for hermetic tests/fixtures only. Production is `None`.
    public var configRootOverride: String?
    /// Refresh floor seconds (clamped ≥ 60 in Rust).
    public var refreshFloorSecs: UInt64
    /// Enabled surface ids; empty = all.
    public var enabledSurfaceIds: [String]
    /// Whether live provider probes may dispatch. `false` = smoke/defense mode
    /// (no credential/file/env/CLI/network/Keychain resolution). Not persisted.
    public var allowLiveProbes: Bool

    public init(
        dataDirOverride: String?,
        configRootOverride: String?,
        refreshFloorSecs: UInt64,
        enabledSurfaceIds: [String],
        allowLiveProbes: Bool
    ) {
        self.dataDirOverride = dataDirOverride
        self.configRootOverride = configRootOverride
        self.refreshFloorSecs = refreshFloorSecs
        self.enabledSurfaceIds = enabledSurfaceIds
        self.allowLiveProbes = allowLiveProbes
    }

    @inlinable static func decode(from reader: inout WireReader) -> OpenConfig {
        OpenConfig(
            dataDirOverride: reader.readOptional { reader in reader.readString() },
            configRootOverride: reader.readOptional { reader in reader.readString() },
            refreshFloorSecs: reader.readU64(),
            enabledSurfaceIds: reader.readArray { reader in reader.readString() },
            allowLiveProbes: reader.readBool()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.dataDirOverride) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.configRootOverride) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeU64(self.refreshFloorSecs)
        writer.writeArray(self.enabledSurfaceIds) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.allowLiveProbes)
    }
}

/// Surface row for Settings / list.
public struct SurfaceDescriptorDto: Hashable, Equatable, Sendable {
    public var id: String
    public var label: String
    public var agent: String
    public var provider: String?
    public var enabled: Bool

    public init(
        id: String,
        label: String,
        agent: String,
        provider: String?,
        enabled: Bool
    ) {
        self.id = id
        self.label = label
        self.agent = agent
        self.provider = provider
        self.enabled = enabled
    }

    @inlinable static func decode(from reader: inout WireReader) -> SurfaceDescriptorDto {
        SurfaceDescriptorDto(
            id: reader.readString(),
            label: reader.readString(),
            agent: reader.readString(),
            provider: reader.readOptional { reader in reader.readString() },
            enabled: reader.readBool()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.id)
        writer.writeString(self.label)
        writer.writeString(self.agent)
        writer.writeOptional(self.provider) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.enabled)
    }
}

/// Sanitized config/credential discovery failure. Contains no source path or secret.
public struct DiscoveryDiagnosticDto: Hashable, Equatable, Sendable {
    public var surfaceId: String?
    public var scopeLabel: String
    public var issue: String
    public var message: String
    public var displayLabel: String

    public init(
        surfaceId: String?,
        scopeLabel: String,
        issue: String,
        message: String,
        displayLabel: String
    ) {
        self.surfaceId = surfaceId
        self.scopeLabel = scopeLabel
        self.issue = issue
        self.message = message
        self.displayLabel = displayLabel
    }

    @inlinable static func decode(from reader: inout WireReader) -> DiscoveryDiagnosticDto {
        DiscoveryDiagnosticDto(
            surfaceId: reader.readOptional { reader in reader.readString() },
            scopeLabel: reader.readString(),
            issue: reader.readString(),
            message: reader.readString(),
            displayLabel: reader.readString()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.surfaceId) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.scopeLabel)
        writer.writeString(self.issue)
        writer.writeString(self.message)
        writer.writeString(self.displayLabel)
    }
}

/// Monetary amount (minor units).
public struct MoneyDto: Hashable, Equatable, Sendable {
    public var amountMinor: Int64
    public var currency: String
    public var exponent: UInt8

    public init(amountMinor: Int64, currency: String, exponent: UInt8) {
        self.amountMinor = amountMinor
        self.currency = currency
        self.exponent = exponent
    }

    @inlinable static func decode(from reader: inout WireReader) -> MoneyDto {
        MoneyDto(amountMinor: reader.readI64(), currency: reader.readString(), exponent: reader.readU8())
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeI64(self.amountMinor)
        writer.writeString(self.currency)
        writer.writeU8(self.exponent)
    }
}

/// One quota / spend bucket.
public struct QuotaBucketDto: Hashable, Equatable, Sendable {
    public var label: String
    public var usedLabel: String?
    public var limitLabel: String?
    public var remainingPercent: UInt8?
    public var resetLabel: String?
    public var resetsAt: Int64?
    public var statusSlot: String?
    public var paceLabel: String?
    public var status: String
    public var usedMoney: MoneyDto?
    public var limitMoney: MoneyDto?
    public var severity: String
    /// Rust-owned percentage segment text (segment 0), when present.
    public var remainingLabel: String?
    /// Rust-owned complete semantic segments in display order.
    public var displaySegments: [String]
    /// `display_segments` joined with the canonical `" · "` separator.
    public var displayLabel: String
    /// Meter fill geometry only (remaining for normal/credits, used for Spend).
    public var meterPercent: UInt8?

    public init(
        label: String,
        usedLabel: String?,
        limitLabel: String?,
        remainingPercent: UInt8?,
        resetLabel: String?,
        resetsAt: Int64?,
        statusSlot: String?,
        paceLabel: String?,
        status: String,
        usedMoney: MoneyDto?,
        limitMoney: MoneyDto?,
        severity: String,
        remainingLabel: String?,
        displaySegments: [String],
        displayLabel: String,
        meterPercent: UInt8?
    ) {
        self.label = label
        self.usedLabel = usedLabel
        self.limitLabel = limitLabel
        self.remainingPercent = remainingPercent
        self.resetLabel = resetLabel
        self.resetsAt = resetsAt
        self.statusSlot = statusSlot
        self.paceLabel = paceLabel
        self.status = status
        self.usedMoney = usedMoney
        self.limitMoney = limitMoney
        self.severity = severity
        self.remainingLabel = remainingLabel
        self.displaySegments = displaySegments
        self.displayLabel = displayLabel
        self.meterPercent = meterPercent
    }

    @inlinable static func decode(from reader: inout WireReader) -> QuotaBucketDto {
        QuotaBucketDto(
            label: reader.readString(),
            usedLabel: reader.readOptional { reader in reader.readString() },
            limitLabel: reader.readOptional { reader in reader.readString() },
            remainingPercent: reader.readOptional { reader in reader.readU8() },
            resetLabel: reader.readOptional { reader in reader.readString() },
            resetsAt: reader.readOptional { reader in reader.readI64() },
            statusSlot: reader.readOptional { reader in reader.readString() },
            paceLabel: reader.readOptional { reader in reader.readString() },
            status: reader.readString(),
            usedMoney: reader.readOptional { reader in MoneyDto.decode(from: &reader) },
            limitMoney: reader.readOptional { reader in MoneyDto.decode(from: &reader) },
            severity: reader.readString(),
            remainingLabel: reader.readOptional { reader in reader.readString() },
            displaySegments: reader.readArray { reader in reader.readString() },
            displayLabel: reader.readString(),
            meterPercent: reader.readOptional { reader in reader.readU8() }
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.label)
        writer.writeOptional(self.usedLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.limitLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.remainingPercent) { writer, boltffiValue0 in writer.writeU8(boltffiValue0) }
        writer.writeOptional(self.resetLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.resetsAt) { writer, boltffiValue0 in writer.writeI64(boltffiValue0) }
        writer.writeOptional(self.statusSlot) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.paceLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.status)
        writer.writeOptional(self.usedMoney) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeOptional(self.limitMoney) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeString(self.severity)
        writer.writeOptional(self.remainingLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeArray(self.displaySegments) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.displayLabel)
        writer.writeOptional(self.meterPercent) { writer, boltffiValue0 in writer.writeU8(boltffiValue0) }
    }
}

/// One already-grouped visual line of a [`UsageDetailRowDto`] (1:1 mirror of the
/// Rust `UsagePresentationLine`). `leading`/`trailing` are finished strings.
public struct UsagePresentationLineDto: Hashable, Equatable, Sendable {
    public var leading: String?
    public var trailing: String?

    public init(leading: String?, trailing: String?) {
        self.leading = leading
        self.trailing = trailing
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsagePresentationLineDto {
        UsagePresentationLineDto(leading: reader.readOptional { reader in reader.readString() }, trailing: reader.readOptional { reader in reader.readString() })
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeOptional(self.leading) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.trailing) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
    }
}

/// One provider-detail row (1:1 mirror of the Rust `UsageDetailRow`). Every
/// visible string is Rust-owned; `kind`/`severity` are machine strings and
/// `meter_percent` is meter geometry only.
public struct UsageDetailRowDto: Hashable, Equatable, Sendable {
    public var rowId: String
    /// `metadata` | `bucket` | `detail`
    public var kind: String
    public var label: String
    public var layoutLines: [UsagePresentationLineDto]
    public var displayLabel: String
    public var meterPercent: UInt8?
    /// `normal` | `warn` | `danger`
    public var severity: String

    public init(
        rowId: String,
        kind: String,
        label: String,
        layoutLines: [UsagePresentationLineDto],
        displayLabel: String,
        meterPercent: UInt8?,
        severity: String
    ) {
        self.rowId = rowId
        self.kind = kind
        self.label = label
        self.layoutLines = layoutLines
        self.displayLabel = displayLabel
        self.meterPercent = meterPercent
        self.severity = severity
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageDetailRowDto {
        UsageDetailRowDto(
            rowId: reader.readString(),
            kind: reader.readString(),
            label: reader.readString(),
            layoutLines: reader.readArray { reader in UsagePresentationLineDto.decode(from: &reader) },
            displayLabel: reader.readString(),
            meterPercent: reader.readOptional { reader in reader.readU8() },
            severity: reader.readString()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.rowId)
        writer.writeString(self.kind)
        writer.writeString(self.label)
        writer.writeArray(self.layoutLines) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeString(self.displayLabel)
        writer.writeOptional(self.meterPercent) { writer, boltffiValue0 in writer.writeU8(boltffiValue0) }
        writer.writeString(self.severity)
    }
}

/// The complete Rust-owned provider-detail card (mirror of
/// `UsageDetailPresentation`). Rows are already in canonical order.
public struct UsageDetailPresentationDto: Hashable, Equatable, Sendable {
    public var rows: [UsageDetailRowDto]

    public init(rows: [UsageDetailRowDto]) {
        self.rows = rows
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageDetailPresentationDto {
        UsageDetailPresentationDto(rows: reader.readArray { reader in UsageDetailRowDto.decode(from: &reader) })
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeArray(self.rows) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
    }
}

/// Finished provider/account/activity identity copy.
public struct UsageIdentityPresentationDto: Hashable, Equatable, Sendable {
    public var providerTitle: String
    public var accountLabel: String
    public var activityLabel: String
    /// `idle` | `updating` | `exceptional`
    public var activityKind: String
    public var accessibilityLabel: String

    public init(
        providerTitle: String,
        accountLabel: String,
        activityLabel: String,
        activityKind: String,
        accessibilityLabel: String
    ) {
        self.providerTitle = providerTitle
        self.accountLabel = accountLabel
        self.activityLabel = activityLabel
        self.activityKind = activityKind
        self.accessibilityLabel = accessibilityLabel
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageIdentityPresentationDto {
        UsageIdentityPresentationDto(
            providerTitle: reader.readString(),
            accountLabel: reader.readString(),
            activityLabel: reader.readString(),
            activityKind: reader.readString(),
            accessibilityLabel: reader.readString()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.providerTitle)
        writer.writeString(self.accountLabel)
        writer.writeString(self.activityLabel)
        writer.writeString(self.activityKind)
        writer.writeString(self.accessibilityLabel)
    }
}

/// One selected-account-aware provider glance row (1:1 mirror of the Rust
/// `HostProviderGlanceRow`). The Desktop status bar, popover, and Usage window
/// all consume this same Rust-owned row.
public struct ProviderGlanceRowDto: Hashable, Equatable, Sendable {
    public var surfaceId: String
    public var iconKey: String
    public var fallbackGlyph: String
    public var usageUrl: String?
    public var displayLabel: String
    public var accountLabel: String
    public var planLabel: String?
    public var glanceRemainingPercent: UInt8?
    public var barLabel: String
    public var headline: String
    public var resetLabel: String?
    public var compactResetLabel: String?
    public var exactReset: String?
    public var statusWord: String
    public var isRefreshing: Bool
    public var statusLabel: String
    public var severity: String
    public var updatedLabel: String
    public var activityLabel: String
    public var activityKind: String
    public var accessibilityLabel: String
    public var lastError: String?
    public var dimmed: Bool

    public init(
        surfaceId: String,
        iconKey: String,
        fallbackGlyph: String,
        usageUrl: String?,
        displayLabel: String,
        accountLabel: String,
        planLabel: String?,
        glanceRemainingPercent: UInt8?,
        barLabel: String,
        headline: String,
        resetLabel: String?,
        compactResetLabel: String?,
        exactReset: String?,
        statusWord: String,
        isRefreshing: Bool,
        statusLabel: String,
        severity: String,
        updatedLabel: String,
        activityLabel: String,
        activityKind: String,
        accessibilityLabel: String,
        lastError: String?,
        dimmed: Bool
    ) {
        self.surfaceId = surfaceId
        self.iconKey = iconKey
        self.fallbackGlyph = fallbackGlyph
        self.usageUrl = usageUrl
        self.displayLabel = displayLabel
        self.accountLabel = accountLabel
        self.planLabel = planLabel
        self.glanceRemainingPercent = glanceRemainingPercent
        self.barLabel = barLabel
        self.headline = headline
        self.resetLabel = resetLabel
        self.compactResetLabel = compactResetLabel
        self.exactReset = exactReset
        self.statusWord = statusWord
        self.isRefreshing = isRefreshing
        self.statusLabel = statusLabel
        self.severity = severity
        self.updatedLabel = updatedLabel
        self.activityLabel = activityLabel
        self.activityKind = activityKind
        self.accessibilityLabel = accessibilityLabel
        self.lastError = lastError
        self.dimmed = dimmed
    }

    @inlinable static func decode(from reader: inout WireReader) -> ProviderGlanceRowDto {
        ProviderGlanceRowDto(
            surfaceId: reader.readString(),
            iconKey: reader.readString(),
            fallbackGlyph: reader.readString(),
            usageUrl: reader.readOptional { reader in reader.readString() },
            displayLabel: reader.readString(),
            accountLabel: reader.readString(),
            planLabel: reader.readOptional { reader in reader.readString() },
            glanceRemainingPercent: reader.readOptional { reader in reader.readU8() },
            barLabel: reader.readString(),
            headline: reader.readString(),
            resetLabel: reader.readOptional { reader in reader.readString() },
            compactResetLabel: reader.readOptional { reader in reader.readString() },
            exactReset: reader.readOptional { reader in reader.readString() },
            statusWord: reader.readString(),
            isRefreshing: reader.readBool(),
            statusLabel: reader.readString(),
            severity: reader.readString(),
            updatedLabel: reader.readString(),
            activityLabel: reader.readString(),
            activityKind: reader.readString(),
            accessibilityLabel: reader.readString(),
            lastError: reader.readOptional { reader in reader.readString() },
            dimmed: reader.readBool()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.surfaceId)
        writer.writeString(self.iconKey)
        writer.writeString(self.fallbackGlyph)
        writer.writeOptional(self.usageUrl) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.displayLabel)
        writer.writeString(self.accountLabel)
        writer.writeOptional(self.planLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.glanceRemainingPercent) { writer, boltffiValue0 in writer.writeU8(boltffiValue0) }
        writer.writeString(self.barLabel)
        writer.writeString(self.headline)
        writer.writeOptional(self.resetLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.compactResetLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.exactReset) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.statusWord)
        writer.writeBool(self.isRefreshing)
        writer.writeString(self.statusLabel)
        writer.writeString(self.severity)
        writer.writeString(self.updatedLabel)
        writer.writeString(self.activityLabel)
        writer.writeString(self.activityKind)
        writer.writeString(self.accessibilityLabel)
        writer.writeOptional(self.lastError) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.dimmed)
    }
}

/// Full focused usage view for one surface.
public struct UsageViewDto: Hashable, Equatable, Sendable {
    public var identity: UsageIdentityPresentationDto
    public var focusedAgent: String?
    public var focusedProvider: String?
    public var providerLabel: String
    public var accountLabel: String
    public var username: String?
    public var planLabel: String?
    public var credentialOrigin: String?
    public var buckets: [QuotaBucketDto]
    public var status: String
    public var source: String
    public var confidence: String
    public var fetchedAtEpoch: Int64
    public var updatedLabel: String
    public var statusBarLabel: String
    public var lastError: String?
    /// Honesty caption when estimated / local-log derived; `None` for authoritative.
    public var estimateCaption: String?
    /// Rust-owned Capsule-parity provider-detail card (same rows/strings/order
    /// as the Capsule usage dialog). The Usage window renders this verbatim.
    public var detailPresentation: UsageDetailPresentationDto

    public init(
        identity: UsageIdentityPresentationDto,
        focusedAgent: String?,
        focusedProvider: String?,
        providerLabel: String,
        accountLabel: String,
        username: String?,
        planLabel: String?,
        credentialOrigin: String?,
        buckets: [QuotaBucketDto],
        status: String,
        source: String,
        confidence: String,
        fetchedAtEpoch: Int64,
        updatedLabel: String,
        statusBarLabel: String,
        lastError: String?,
        estimateCaption: String?,
        detailPresentation: UsageDetailPresentationDto
    ) {
        self.identity = identity
        self.focusedAgent = focusedAgent
        self.focusedProvider = focusedProvider
        self.providerLabel = providerLabel
        self.accountLabel = accountLabel
        self.username = username
        self.planLabel = planLabel
        self.credentialOrigin = credentialOrigin
        self.buckets = buckets
        self.status = status
        self.source = source
        self.confidence = confidence
        self.fetchedAtEpoch = fetchedAtEpoch
        self.updatedLabel = updatedLabel
        self.statusBarLabel = statusBarLabel
        self.lastError = lastError
        self.estimateCaption = estimateCaption
        self.detailPresentation = detailPresentation
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageViewDto {
        UsageViewDto(
            identity: UsageIdentityPresentationDto.decode(from: &reader),
            focusedAgent: reader.readOptional { reader in reader.readString() },
            focusedProvider: reader.readOptional { reader in reader.readString() },
            providerLabel: reader.readString(),
            accountLabel: reader.readString(),
            username: reader.readOptional { reader in reader.readString() },
            planLabel: reader.readOptional { reader in reader.readString() },
            credentialOrigin: reader.readOptional { reader in reader.readString() },
            buckets: reader.readArray { reader in QuotaBucketDto.decode(from: &reader) },
            status: reader.readString(),
            source: reader.readString(),
            confidence: reader.readString(),
            fetchedAtEpoch: reader.readI64(),
            updatedLabel: reader.readString(),
            statusBarLabel: reader.readString(),
            lastError: reader.readOptional { reader in reader.readString() },
            estimateCaption: reader.readOptional { reader in reader.readString() },
            detailPresentation: UsageDetailPresentationDto.decode(from: &reader)
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        self.identity.encode(to: &writer)
        writer.writeOptional(self.focusedAgent) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.focusedProvider) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.providerLabel)
        writer.writeString(self.accountLabel)
        writer.writeOptional(self.username) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.planLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.credentialOrigin) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeArray(self.buckets) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeString(self.status)
        writer.writeString(self.source)
        writer.writeString(self.confidence)
        writer.writeI64(self.fetchedAtEpoch)
        writer.writeString(self.updatedLabel)
        writer.writeString(self.statusBarLabel)
        writer.writeOptional(self.lastError) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.estimateCaption) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        self.detailPresentation.encode(to: &writer)
    }
}

/// Presentation-time format prefs (string enums).
public struct UsageFormatPrefsDto: Hashable, Equatable, Sendable {
    /// `left` | `used`
    public var percentStyle: String
    /// `countdown` | `exact_clock`
    public var resetStyle: String

    public init(percentStyle: String, resetStyle: String) {
        self.percentStyle = percentStyle
        self.resetStyle = resetStyle
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageFormatPrefsDto {
        UsageFormatPrefsDto(percentStyle: reader.readString(), resetStyle: reader.readString())
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.percentStyle)
        writer.writeString(self.resetStyle)
    }
}

/// Overview row for glance popover / Usage-window sidebar.
public struct OverviewRowDto: Hashable, Equatable, Sendable {
    public var surfaceId: String
    public var displayLabel: String
    public var headline: String
    public var resetLabel: String?
    public var exactReset: String?
    public var statusWord: String
    public var severity: String

    public init(
        surfaceId: String,
        displayLabel: String,
        headline: String,
        resetLabel: String?,
        exactReset: String?,
        statusWord: String,
        severity: String
    ) {
        self.surfaceId = surfaceId
        self.displayLabel = displayLabel
        self.headline = headline
        self.resetLabel = resetLabel
        self.exactReset = exactReset
        self.statusWord = statusWord
        self.severity = severity
    }

    @inlinable static func decode(from reader: inout WireReader) -> OverviewRowDto {
        OverviewRowDto(
            surfaceId: reader.readString(),
            displayLabel: reader.readString(),
            headline: reader.readString(),
            resetLabel: reader.readOptional { reader in reader.readString() },
            exactReset: reader.readOptional { reader in reader.readString() },
            statusWord: reader.readString(),
            severity: reader.readString()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.surfaceId)
        writer.writeString(self.displayLabel)
        writer.writeString(self.headline)
        writer.writeOptional(self.resetLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.exactReset) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.statusWord)
        writer.writeString(self.severity)
    }
}

/// One known account for a host surface (multi-account Desktop).
public struct AccountDescriptorDto: Hashable, Equatable, Sendable {
    public var surfaceId: String
    public var providerColumnLabel: String
    public var accountKey: String
    public var accountLabel: String
    public var planLabel: String?
    public var selected: Bool
    public var lifecycle: String
    public var lifecycleLabel: String
    public var provenance: [String]
    public var provenanceLabel: String
    public var planOrStatusLabel: String
    public var remainingPercent: UInt8?
    public var remainingLabel: String
    public var headline: String
    public var resetLabel: String?
    public var resetDisplayLabel: String
    public var exactReset: String?
    public var statusWord: String
    public var statusLabel: String
    public var severity: String
    public var updatedLabel: String
    public var lastError: String?
    public var dimmed: Bool
    public var accessibilityLabel: String

    public init(
        surfaceId: String,
        providerColumnLabel: String,
        accountKey: String,
        accountLabel: String,
        planLabel: String?,
        selected: Bool,
        lifecycle: String,
        lifecycleLabel: String,
        provenance: [String],
        provenanceLabel: String,
        planOrStatusLabel: String,
        remainingPercent: UInt8?,
        remainingLabel: String,
        headline: String,
        resetLabel: String?,
        resetDisplayLabel: String,
        exactReset: String?,
        statusWord: String,
        statusLabel: String,
        severity: String,
        updatedLabel: String,
        lastError: String?,
        dimmed: Bool,
        accessibilityLabel: String
    ) {
        self.surfaceId = surfaceId
        self.providerColumnLabel = providerColumnLabel
        self.accountKey = accountKey
        self.accountLabel = accountLabel
        self.planLabel = planLabel
        self.selected = selected
        self.lifecycle = lifecycle
        self.lifecycleLabel = lifecycleLabel
        self.provenance = provenance
        self.provenanceLabel = provenanceLabel
        self.planOrStatusLabel = planOrStatusLabel
        self.remainingPercent = remainingPercent
        self.remainingLabel = remainingLabel
        self.headline = headline
        self.resetLabel = resetLabel
        self.resetDisplayLabel = resetDisplayLabel
        self.exactReset = exactReset
        self.statusWord = statusWord
        self.statusLabel = statusLabel
        self.severity = severity
        self.updatedLabel = updatedLabel
        self.lastError = lastError
        self.dimmed = dimmed
        self.accessibilityLabel = accessibilityLabel
    }

    @inlinable static func decode(from reader: inout WireReader) -> AccountDescriptorDto {
        AccountDescriptorDto(
            surfaceId: reader.readString(),
            providerColumnLabel: reader.readString(),
            accountKey: reader.readString(),
            accountLabel: reader.readString(),
            planLabel: reader.readOptional { reader in reader.readString() },
            selected: reader.readBool(),
            lifecycle: reader.readString(),
            lifecycleLabel: reader.readString(),
            provenance: reader.readArray { reader in reader.readString() },
            provenanceLabel: reader.readString(),
            planOrStatusLabel: reader.readString(),
            remainingPercent: reader.readOptional { reader in reader.readU8() },
            remainingLabel: reader.readString(),
            headline: reader.readString(),
            resetLabel: reader.readOptional { reader in reader.readString() },
            resetDisplayLabel: reader.readString(),
            exactReset: reader.readOptional { reader in reader.readString() },
            statusWord: reader.readString(),
            statusLabel: reader.readString(),
            severity: reader.readString(),
            updatedLabel: reader.readString(),
            lastError: reader.readOptional { reader in reader.readString() },
            dimmed: reader.readBool(),
            accessibilityLabel: reader.readString()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.surfaceId)
        writer.writeString(self.providerColumnLabel)
        writer.writeString(self.accountKey)
        writer.writeString(self.accountLabel)
        writer.writeOptional(self.planLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.selected)
        writer.writeString(self.lifecycle)
        writer.writeString(self.lifecycleLabel)
        writer.writeArray(self.provenance) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.provenanceLabel)
        writer.writeString(self.planOrStatusLabel)
        writer.writeOptional(self.remainingPercent) { writer, boltffiValue0 in writer.writeU8(boltffiValue0) }
        writer.writeString(self.remainingLabel)
        writer.writeString(self.headline)
        writer.writeOptional(self.resetLabel) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.resetDisplayLabel)
        writer.writeOptional(self.exactReset) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.statusWord)
        writer.writeString(self.statusLabel)
        writer.writeString(self.severity)
        writer.writeString(self.updatedLabel)
        writer.writeOptional(self.lastError) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.dimmed)
        writer.writeString(self.accessibilityLabel)
    }
}

/// Provider state when no stable account identity exists yet.
public struct DesktopProviderStateDto: Hashable, Equatable, Sendable {
    public var statusWord: String
    public var statusLabel: String
    public var updatedLabel: String
    public var lastError: String?
    public var isRefreshing: Bool

    public init(
        statusWord: String,
        statusLabel: String,
        updatedLabel: String,
        lastError: String?,
        isRefreshing: Bool
    ) {
        self.statusWord = statusWord
        self.statusLabel = statusLabel
        self.updatedLabel = updatedLabel
        self.lastError = lastError
        self.isRefreshing = isRefreshing
    }

    @inlinable static func decode(from reader: inout WireReader) -> DesktopProviderStateDto {
        DesktopProviderStateDto(
            statusWord: reader.readString(),
            statusLabel: reader.readString(),
            updatedLabel: reader.readString(),
            lastError: reader.readOptional { reader in reader.readString() },
            isRefreshing: reader.readBool()
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.statusWord)
        writer.writeString(self.statusLabel)
        writer.writeString(self.updatedLabel)
        writer.writeOptional(self.lastError) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeBool(self.isRefreshing)
    }
}

/// One Rust-ordered provider group in the atomic Desktop inventory.
public struct DesktopProviderGroupDto: Hashable, Equatable, Sendable {
    public var surfaceId: String
    public var displayLabel: String
    public var iconKey: String
    public var fallbackGlyph: String
    public var usageUrl: String?
    public var accountColumnLabel: String
    public var planOrStatusLabel: String
    public var remainingLabel: String
    public var resetDisplayLabel: String
    public var accessibilityLabel: String
    public var accounts: [AccountDescriptorDto]
    public var emptyState: DesktopProviderStateDto?

    public init(
        surfaceId: String,
        displayLabel: String,
        iconKey: String,
        fallbackGlyph: String,
        usageUrl: String?,
        accountColumnLabel: String,
        planOrStatusLabel: String,
        remainingLabel: String,
        resetDisplayLabel: String,
        accessibilityLabel: String,
        accounts: [AccountDescriptorDto],
        emptyState: DesktopProviderStateDto?
    ) {
        self.surfaceId = surfaceId
        self.displayLabel = displayLabel
        self.iconKey = iconKey
        self.fallbackGlyph = fallbackGlyph
        self.usageUrl = usageUrl
        self.accountColumnLabel = accountColumnLabel
        self.planOrStatusLabel = planOrStatusLabel
        self.remainingLabel = remainingLabel
        self.resetDisplayLabel = resetDisplayLabel
        self.accessibilityLabel = accessibilityLabel
        self.accounts = accounts
        self.emptyState = emptyState
    }

    @inlinable static func decode(from reader: inout WireReader) -> DesktopProviderGroupDto {
        DesktopProviderGroupDto(
            surfaceId: reader.readString(),
            displayLabel: reader.readString(),
            iconKey: reader.readString(),
            fallbackGlyph: reader.readString(),
            usageUrl: reader.readOptional { reader in reader.readString() },
            accountColumnLabel: reader.readString(),
            planOrStatusLabel: reader.readString(),
            remainingLabel: reader.readString(),
            resetDisplayLabel: reader.readString(),
            accessibilityLabel: reader.readString(),
            accounts: reader.readArray { reader in AccountDescriptorDto.decode(from: &reader) },
            emptyState: reader.readOptional { reader in DesktopProviderStateDto.decode(from: &reader) }
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeString(self.surfaceId)
        writer.writeString(self.displayLabel)
        writer.writeString(self.iconKey)
        writer.writeString(self.fallbackGlyph)
        writer.writeOptional(self.usageUrl) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.accountColumnLabel)
        writer.writeString(self.planOrStatusLabel)
        writer.writeString(self.remainingLabel)
        writer.writeString(self.resetDisplayLabel)
        writer.writeString(self.accessibilityLabel)
        writer.writeArray(self.accounts) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeOptional(self.emptyState) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
    }
}

/// Atomic Rust-owned Desktop inventory.
public struct DesktopInventoryDto: Hashable, Equatable, Sendable {
    public var groups: [DesktopProviderGroupDto]

    public init(groups: [DesktopProviderGroupDto]) {
        self.groups = groups
    }

    @inlinable static func decode(from reader: inout WireReader) -> DesktopInventoryDto {
        DesktopInventoryDto(groups: reader.readArray { reader in DesktopProviderGroupDto.decode(from: &reader) })
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeArray(self.groups) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
    }
}

/// One grouped provider plus its exact selected account/detail snapshot.
public struct DesktopProviderProjectionDto: Hashable, Equatable, Sendable {
    public var group: DesktopProviderGroupDto
    public var selectedAccountKey: String?
    public var selectedUsage: UsageViewDto

    public init(group: DesktopProviderGroupDto, selectedAccountKey: String?, selectedUsage: UsageViewDto) {
        self.group = group
        self.selectedAccountKey = selectedAccountKey
        self.selectedUsage = selectedUsage
    }

    @inlinable static func decode(from reader: inout WireReader) -> DesktopProviderProjectionDto {
        DesktopProviderProjectionDto(group: DesktopProviderGroupDto.decode(from: &reader), selectedAccountKey: reader.readOptional { reader in reader.readString() }, selectedUsage: UsageViewDto.decode(from: &reader))
    }

    @inlinable func encode(to writer: inout WireWriter) {
        self.group.encode(to: &writer)
        writer.writeOptional(self.selectedAccountKey) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        self.selectedUsage.encode(to: &writer)
    }
}

/// Complete immutable native Desktop state for one runtime generation.
public struct DesktopProjectionDto: Hashable, Equatable, Sendable {
    public var generation: UInt64
    public var refreshInProgress: Bool
    public var errorMessage: String?
    public var nextRefreshLabel: String
    public var surfaces: [SurfaceDescriptorDto]
    public var providers: [DesktopProviderProjectionDto]
    public var glanceRows: [ProviderGlanceRowDto]
    public var statusBarGlanceRows: [ProviderGlanceRowDto]
    public var diagnostics: [DiscoveryDiagnosticDto]

    public init(
        generation: UInt64,
        refreshInProgress: Bool,
        errorMessage: String?,
        nextRefreshLabel: String,
        surfaces: [SurfaceDescriptorDto],
        providers: [DesktopProviderProjectionDto],
        glanceRows: [ProviderGlanceRowDto],
        statusBarGlanceRows: [ProviderGlanceRowDto],
        diagnostics: [DiscoveryDiagnosticDto]
    ) {
        self.generation = generation
        self.refreshInProgress = refreshInProgress
        self.errorMessage = errorMessage
        self.nextRefreshLabel = nextRefreshLabel
        self.surfaces = surfaces
        self.providers = providers
        self.glanceRows = glanceRows
        self.statusBarGlanceRows = statusBarGlanceRows
        self.diagnostics = diagnostics
    }

    @inlinable static func decode(from reader: inout WireReader) -> DesktopProjectionDto {
        DesktopProjectionDto(
            generation: reader.readU64(),
            refreshInProgress: reader.readBool(),
            errorMessage: reader.readOptional { reader in reader.readString() },
            nextRefreshLabel: reader.readString(),
            surfaces: reader.readArray { reader in SurfaceDescriptorDto.decode(from: &reader) },
            providers: reader.readArray { reader in DesktopProviderProjectionDto.decode(from: &reader) },
            glanceRows: reader.readArray { reader in ProviderGlanceRowDto.decode(from: &reader) },
            statusBarGlanceRows: reader.readArray { reader in ProviderGlanceRowDto.decode(from: &reader) },
            diagnostics: reader.readArray { reader in DiscoveryDiagnosticDto.decode(from: &reader) }
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeU64(self.generation)
        writer.writeBool(self.refreshInProgress)
        writer.writeOptional(self.errorMessage) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeString(self.nextRefreshLabel)
        writer.writeArray(self.surfaces) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeArray(self.providers) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeArray(self.glanceRows) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeArray(self.statusBarGlanceRows) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeArray(self.diagnostics) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
    }
}

/// One host event.
public struct UsageEventDto: Hashable, Equatable, Sendable {
    public var sequence: UInt64
    public var kind: String
    public var surfaceId: String?
    public var detail: String?

    public init(
        sequence: UInt64,
        kind: String,
        surfaceId: String?,
        detail: String?
    ) {
        self.sequence = sequence
        self.kind = kind
        self.surfaceId = surfaceId
        self.detail = detail
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageEventDto {
        UsageEventDto(
            sequence: reader.readU64(),
            kind: reader.readString(),
            surfaceId: reader.readOptional { reader in reader.readString() },
            detail: reader.readOptional { reader in reader.readString() }
        )
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeU64(self.sequence)
        writer.writeString(self.kind)
        writer.writeOptional(self.surfaceId) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
        writer.writeOptional(self.detail) { writer, boltffiValue0 in writer.writeString(boltffiValue0) }
    }
}

/// Bounded event batch.
public struct UsageEventBatchDto: Hashable, Equatable, Sendable {
    public var nextCursor: UInt64
    public var events: [UsageEventDto]
    public var resyncRequired: Bool

    public init(nextCursor: UInt64, events: [UsageEventDto], resyncRequired: Bool) {
        self.nextCursor = nextCursor
        self.events = events
        self.resyncRequired = resyncRequired
    }

    @inlinable static func decode(from reader: inout WireReader) -> UsageEventBatchDto {
        UsageEventBatchDto(nextCursor: reader.readU64(), events: reader.readArray { reader in UsageEventDto.decode(from: &reader) }, resyncRequired: reader.readBool())
    }

    @inlinable func encode(to writer: inout WireWriter) {
        writer.writeU64(self.nextCursor)
        writer.writeArray(self.events) { writer, boltffiValue0 in boltffiValue0.encode(to: &writer) }
        writer.writeBool(self.resyncRequired)
    }
}

/// Typed bridge failures. Messages never include credentials or tokens.
public enum UsageBridgeError: Hashable, Equatable, Sendable, Error {
    /// Recoverable rejection (validation, unknown surface, closed runtime).
    case rejected(code: String, message: String)
    /// A Rust panic was caught at the facade boundary.
    case containedPanic(message: String)
    /// Runtime not opened or already shut down.
    case runtimeUnavailable
    /// Event cursor requires resync.
    case resyncRequired

    @inlinable static func decode(from reader: inout WireReader) -> UsageBridgeError {
        let tag = reader.readU32()
        switch tag {
        case 0:
            return .rejected(code: reader.readString(), message: reader.readString())
        case 1:
            return .containedPanic(message: reader.readString())
        case 2:
            return .runtimeUnavailable
        case 3:
            return .resyncRequired
        default:
            fatalError("Invalid UsageBridgeError tag: \(tag)")
        }
    }

    @inlinable func encode(to writer: inout WireWriter) {
        switch self {
        case let .rejected(code, message):
            writer.writeU32(0)
            writer.writeString(code)
            writer.writeString(message)
        case let .containedPanic(message):
            writer.writeU32(1)
            writer.writeString(message)
        case .runtimeUnavailable:
            writer.writeU32(2)
        case .resyncRequired:
            writer.writeU32(3)
        }
    }
}

public final class UsageMenuBarBridge {
    @usableFromInline let handle: UInt64

    @usableFromInline init(handle: UInt64) {
        self.handle = handle
    }

    deinit {
        boltffi_release_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge(handle)
    }

    /// Construct a closed bridge.
    public init() {
        self.handle = boltffi_init_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_create()
    }

    /// Open the host runtime (paths + enable set). Idempotent replace.
    public func openRuntime(config: OpenConfig) throws {
        let boltffiConfigBytes = boltffiEncode { boltffiConfigWriter in config.encode(to: &boltffiConfigWriter) }
        try boltffiConfigBytes.withUnsafeBufferPointer { boltffiConfigBuffer -> Void in
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_open_runtime(self.handle, boltffiConfigBuffer.baseAddress!, UInt(boltffiConfigBuffer.count))
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
        }
    }

    /// List all host surfaces with enable flags.
    public func listSurfaces() throws -> [SurfaceDescriptorDto] {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_list_surfaces(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in SurfaceDescriptorDto.decode(from: &boltffiReader) } }
    }

    /// Sanitized discovery diagnostics for the current catalog generation.
    public func discoveryDiagnostics() throws -> [DiscoveryDiagnosticDto] {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_discovery_diagnostics(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in DiscoveryDiagnosticDto.decode(from: &boltffiReader) } }
    }

    /// Enable or disable a surface for bar + refresh.
    public func setEnabled(surfaceId: String, enabled: Bool) throws {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeString(surfaceId) }
        try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer -> Void in
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_set_enabled(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                enabled
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
        }
    }

    /// Refresh one surface (`surface_id`) or all enabled (`None`).
    ///
    /// When `force` is false, respects the runtime refresh floor (poll-safe).
    /// When `force` is true, bypasses the floor (manual Refresh).
    public func refresh(surfaceId: String?, force: Bool) throws {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeOptional(surfaceId) { boltffiSurfaceIdWriter, boltffiValue0 in boltffiSurfaceIdWriter.writeString(boltffiValue0) } }
        try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer -> Void in
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_refresh(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                force
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
        }
    }

    /// True while at least one Rust broker generation is queued/updating.
    public func refreshInProgress() throws -> Bool {
        var boltffiResult: Bool = Bool()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_refresh_in_progress(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        return boltffiResult
    }

    /// Set refresh floor seconds (clamped ≥ 60 in Rust).
    public func setRefreshFloorSecs(secs: UInt64) throws {
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_set_refresh_floor_secs(self.handle, secs)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
    }

    /// Whether a non-forced refresh would probe the network.
    public func refreshDue() throws -> Bool {
        var boltffiResult: Bool = Bool()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_refresh_due(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        return boltffiResult
    }

    /// Snapshot for one enabled surface (selected multi-account when set).
    public func snapshot(surfaceId: String) throws -> UsageViewDto {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeString(surfaceId) }
        return try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer in
            var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_snapshot(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                &boltffiResult
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
            defer { boltffi_free_buf(boltffiResult) }
            return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in UsageViewDto.decode(from: &boltffiReader) }
        }
    }

    /// List known accounts for one surface (`Some`) or all surfaces (`None`).
    public func listAccounts(surfaceId: String?) throws -> [AccountDescriptorDto] {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeOptional(surfaceId) { boltffiSurfaceIdWriter, boltffiValue0 in boltffiSurfaceIdWriter.writeString(boltffiValue0) } }
        return try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer in
            var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_list_accounts(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                &boltffiResult
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
            defer { boltffi_free_buf(boltffiResult) }
            return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in AccountDescriptorDto.decode(from: &boltffiReader) } }
        }
    }

    /// Atomic, Rust-ordered provider/account projection for jackin❯ desktop.
    public func desktopInventory() throws -> DesktopInventoryDto {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_desktop_inventory(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in DesktopInventoryDto.decode(from: &boltffiReader) }
    }

    /// Complete native Desktop state produced beneath one runtime mutex hold.
    /// Any required nested projection failure fails the whole call; callers retain
    /// their last complete value rather than replacing it with partial arrays.
    public func desktopProjection(statusBarMax: UInt32) throws -> DesktopProjectionDto {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_desktop_projection(self.handle, statusBarMax, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in DesktopProjectionDto.decode(from: &boltffiReader) }
    }

    /// Select which account drives snapshot/detail for a surface (persisted).
    public func setSelectedAccount(surfaceId: String, accountKey: String) throws {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeString(surfaceId) }
        try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer -> Void in
            let boltffiAccountKeyBytes = boltffiEncode { boltffiAccountKeyWriter in boltffiAccountKeyWriter.writeString(accountKey) }
            try boltffiAccountKeyBytes.withUnsafeBufferPointer { boltffiAccountKeyBuffer -> Void in
                let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_set_selected_account(
                    self.handle,
                    boltffiSurfaceIdBuffer.baseAddress!,
                    UInt(boltffiSurfaceIdBuffer.count),
                    boltffiAccountKeyBuffer.baseAddress!,
                    UInt(boltffiAccountKeyBuffer.count)
                )
                if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                    defer { boltffi_free_buf(boltffiError) }
                    throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
                }
            }
        }
    }

    /// Compact bar label for one surface.
    public func statusBarLabel(surfaceId: String) throws -> String? {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeString(surfaceId) }
        return try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer in
            var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_status_bar_label(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                &boltffiResult
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
            defer { boltffi_free_buf(boltffiResult) }
            return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readOptional { boltffiReader in boltffiReader.readString() } }
        }
    }

    /// Merged menu-bar text for all enabled surfaces.
    public func mergedStatusBarLabel() throws -> String {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_merged_status_bar_label(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readString() }
    }

    /// Short status-item label (worst enabled surface; remaining % by default).
    public func compactStatusBarLabel() throws -> String {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_compact_status_bar_label(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readString() }
    }

    /// Presentation-time format prefs (`left`/`used`, `countdown`/`exact_clock`).
    public func setFormatPrefs(prefs: UsageFormatPrefsDto) throws {
        let boltffiPrefsBytes = boltffiEncode { boltffiPrefsWriter in prefs.encode(to: &boltffiPrefsWriter) }
        try boltffiPrefsBytes.withUnsafeBufferPointer { boltffiPrefsBuffer -> Void in
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_set_format_prefs(self.handle, boltffiPrefsBuffer.baseAddress!, UInt(boltffiPrefsBuffer.count))
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
        }
    }

    /// Pinned-surface compact status-item label.
    public func compactStatusBarLabelFor(surfaceId: String) throws -> String? {
        let boltffiSurfaceIdBytes = boltffiEncode { boltffiSurfaceIdWriter in boltffiSurfaceIdWriter.writeString(surfaceId) }
        return try boltffiSurfaceIdBytes.withUnsafeBufferPointer { boltffiSurfaceIdBuffer in
            var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
            let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_compact_status_bar_label_for(
                self.handle,
                boltffiSurfaceIdBuffer.baseAddress!,
                UInt(boltffiSurfaceIdBuffer.count),
                &boltffiResult
            )
            if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
                defer { boltffi_free_buf(boltffiError) }
                throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
            }
            defer { boltffi_free_buf(boltffiResult) }
            return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readOptional { boltffiReader in boltffiReader.readString() } }
        }
    }

    /// Worst-first multi-surface compact strip (joined with ` · `).
    public func compactStatusBarStrip(max: UInt32) throws -> String {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_compact_status_bar_strip(self.handle, max, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readString() }
    }

    /// Overview rows for every enabled surface (popover + Usage window).
    public func overviewRows() throws -> [OverviewRowDto] {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_overview_rows(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in OverviewRowDto.decode(from: &boltffiReader) } }
    }

    /// Selected-account-aware provider glance rows in the canonical Desktop
    /// order (popover / Usage inventory). Full detected set — includes 0%.
    /// Rust owns detection, ordering, and every display string.
    public func providerGlanceRows() throws -> [ProviderGlanceRowDto] {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_provider_glance_rows(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in ProviderGlanceRowDto.decode(from: &boltffiReader) } }
    }

    /// Burn-first **status bar** glance rows only (SB-3/14/17/19).
    ///
    /// Filters 0%, ranks soonest-then-remaining, hard-caps at 3. `max` is
    /// clamped into `1…3`. Popover/Usage keep using [`Self::provider_glance_rows`].
    public func statusBarProviderGlanceRows(max: UInt32) throws -> [ProviderGlanceRowDto] {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_status_bar_provider_glance_rows(self.handle, max, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readArray { boltffiReader in ProviderGlanceRowDto.decode(from: &boltffiReader) } }
    }

    /// Next network refresh label (`Next update in …` / `Next update due`).
    public func nextRefreshLabel() throws -> String {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_next_refresh_label(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in boltffiReader.readString() }
    }

    /// Poll events after `cursor` (exclusive).
    ///
    /// Always returns `Ok` for a valid open runtime. When the client cursor is
    /// behind the retained log, `resync_required` is true on the batch (do not
    /// turn that into an error — presentation must reset the cursor).
    public func nextEvents(cursor: UInt64, max: UInt32) throws -> UsageEventBatchDto {
        var boltffiResult: FfiBuf_u8 = FfiBuf_u8()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_next_events(
            self.handle,
            cursor,
            max,
            &boltffiResult
        )
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        defer { boltffi_free_buf(boltffiResult) }
        return boltffiDecodeOwnedBuf(boltffiResult.ptr, Int(boltffiResult.len)) { boltffiReader in UsageEventBatchDto.decode(from: &boltffiReader) }
    }

    /// Refresh floor seconds (clamped policy).
    public func refreshFloorSecs() throws -> UInt64 {
        var boltffiResult: UInt64 = UInt64()
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_refresh_floor_secs(self.handle, &boltffiResult)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
        return boltffiResult
    }

    /// Shutdown; idempotent.
    public func shutdown() throws {
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_shutdown(self.handle)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
    }

    /// Intentional panic probe for containment tests (never call from product UI).
    public func panicProbe() throws {
        let boltffiError = boltffi_method_class_jackin_usage_ffi_bridge_usage_menu_bar_bridge_panic_probe(self.handle)
        if boltffiError.ptr != nil || Int(boltffiError.len) != 0 {
            defer { boltffi_free_buf(boltffiError) }
            throw boltffiDecodeOwnedBuf(boltffiError.ptr, Int(boltffiError.len)) { boltffiErrorReader in UsageBridgeError.decode(from: &boltffiErrorReader) }
        }
    }
}

@usableFromInline struct WireReader {
    @usableFromInline let data: Data
    @usableFromInline var position: Int

    @inlinable init(data: Data, position: Int = 0) {
        self.data = data
        self.position = position
    }

    @inlinable init(ptr: UnsafePointer<UInt8>, len: Int) {
        self.data = Data(bytes: ptr, count: len)
        self.position = 0
    }

    @inlinable mutating func readU8() -> UInt8 {
        let value = data[position]
        position += 1
        return value
    }

    @inlinable mutating func readI8() -> Int8 {
        Int8(bitPattern: readU8())
    }

    @inlinable mutating func readU16() -> UInt16 {
        let value = data.withUnsafeBytes { buffer in
            buffer.loadUnaligned(fromByteOffset: position, as: UInt16.self)
        }
        position += 2
        return UInt16(littleEndian: value)
    }

    @inlinable mutating func readI16() -> Int16 {
        Int16(bitPattern: readU16())
    }

    @inlinable mutating func readU32() -> UInt32 {
        let value = data.withUnsafeBytes { buffer in
            buffer.loadUnaligned(fromByteOffset: position, as: UInt32.self)
        }
        position += 4
        return UInt32(littleEndian: value)
    }

    @inlinable mutating func readI32() -> Int32 {
        Int32(bitPattern: readU32())
    }

    @inlinable mutating func readU64() -> UInt64 {
        let value = data.withUnsafeBytes { buffer in
            buffer.loadUnaligned(fromByteOffset: position, as: UInt64.self)
        }
        position += 8
        return UInt64(littleEndian: value)
    }

    @inlinable mutating func readI64() -> Int64 {
        Int64(bitPattern: readU64())
    }

    @inlinable mutating func readF32() -> Float {
        Float(bitPattern: readU32())
    }

    @inlinable mutating func readF64() -> Double {
        Double(bitPattern: readU64())
    }

    @inlinable mutating func readBool() -> Bool {
        readU8() != 0
    }

    @inlinable mutating func readString() -> String {
        let length = Int(readU32())
        guard length > 0 else { return "" }
        let start = position
        position += length
        return data.withUnsafeBytes { bytes in
            let pointer = bytes.baseAddress!.advanced(by: start).assumingMemoryBound(to: UInt8.self)
            let buffer = UnsafeBufferPointer(start: pointer, count: length)
            return String(decoding: buffer, as: UTF8.self)
        }
    }

    @inlinable mutating func readBytes() -> Data {
        let length = Int(readU32())
        guard length > 0 else { return Data() }
        let start = position
        position += length
        return Data(data[start..<(start + length)])
    }

    @inlinable mutating func readDuration() -> TimeInterval {
        let seconds = readU64()
        let nanoseconds = readU32()
        return Double(seconds) + (Double(nanoseconds) / 1.0e9)
    }

    @inlinable mutating func readTimestamp() -> Date {
        let seconds = readI64()
        let nanoseconds = readU32()
        let delta = Double(seconds) + (Double(nanoseconds) / 1.0e9)
        return Date(timeIntervalSince1970: delta)
    }

    @inlinable mutating func readUuid() -> UUID {
        let hi = readU64()
        let lo = readU64()
        var uuid: uuid_t = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
        var hiBe = hi.bigEndian
        var loBe = lo.bigEndian
        withUnsafeMutableBytes(of: &uuid) { uuidBytes in
            Swift.withUnsafeBytes(of: &hiBe) { uuidBytes[0..<8].copyBytes(from: $0) }
            Swift.withUnsafeBytes(of: &loBe) { uuidBytes[8..<16].copyBytes(from: $0) }
        }
        return UUID(uuid: uuid)
    }

    @inlinable mutating func readUrl() -> URL {
        guard let url = URL(string: readString()) else { fatalError("Invalid URL") }
        return url
    }

    @inlinable mutating func readOptional<T>(_ body: (inout WireReader) -> T) -> T? {
        switch readU8() {
        case 0:
            return nil
        case 1:
            return body(&self)
        default:
            fatalError("Invalid optional wire tag")
        }
    }

    @inlinable mutating func readSequence<T>(_ body: (inout WireReader) -> T) -> [T] {
        let count = Int(readU32())
        guard count > 0 else { return [] }
        var result = [T]()
        result.reserveCapacity(count)
        for _ in 0..<count {
            result.append(body(&self))
        }
        return result
    }

    @inlinable mutating func readArray<T>(_ body: (inout WireReader) -> T) -> [T] {
        readSequence(body)
    }

    @inlinable mutating func readResult<Success, Failure: Swift.Error>(
        _ success: (inout WireReader) -> Success,
        _ failure: (inout WireReader) -> Failure
    ) -> Swift.Result<Success, Failure> {
        switch readU8() {
        case 0:
            return .success(success(&self))
        case 1:
            return .failure(failure(&self))
        default:
            fatalError("Invalid result wire tag")
        }
    }

    @inlinable mutating func readMap<K: Hashable, V>(
        _ key: (inout WireReader) -> K,
        _ value: (inout WireReader) -> V
    ) -> [K: V] {
        let count = Int(readU32())
        var result = [K: V]()
        result.reserveCapacity(count)
        for _ in 0..<count {
            let decodedKey = key(&self)
            let decodedValue = value(&self)
            if result.updateValue(decodedValue, forKey: decodedKey) != nil {
                fatalError("Duplicate map key")
            }
        }
        return result
    }
}

@usableFromInline struct WireWriter {
    @usableFromInline var data: Data

    @inlinable init(capacity: Int = 64) {
        self.data = Data(capacity: capacity)
    }

    @inlinable mutating func writeU8(_ value: UInt8) {
        data.append(value)
    }

    @inlinable mutating func writeI8(_ value: Int8) {
        writeU8(UInt8(bitPattern: value))
    }

    @inlinable mutating func writeU16(_ value: UInt16) {
        var value = value.littleEndian
        Swift.withUnsafeBytes(of: &value) { bytes in
            data.append(contentsOf: bytes)
        }
    }

    @inlinable mutating func writeI16(_ value: Int16) {
        writeU16(UInt16(bitPattern: value))
    }

    @inlinable mutating func writeU32(_ value: UInt32) {
        var value = value.littleEndian
        Swift.withUnsafeBytes(of: &value) { bytes in
            data.append(contentsOf: bytes)
        }
    }

    @inlinable mutating func writeI32(_ value: Int32) {
        writeU32(UInt32(bitPattern: value))
    }

    @inlinable mutating func writeU64(_ value: UInt64) {
        var value = value.littleEndian
        Swift.withUnsafeBytes(of: &value) { bytes in
            data.append(contentsOf: bytes)
        }
    }

    @inlinable mutating func writeI64(_ value: Int64) {
        writeU64(UInt64(bitPattern: value))
    }

    @inlinable mutating func writeF32(_ value: Float) {
        writeU32(value.bitPattern)
    }

    @inlinable mutating func writeF64(_ value: Double) {
        writeU64(value.bitPattern)
    }

    @inlinable mutating func writeBool(_ value: Bool) {
        writeU8(value ? 1 : 0)
    }

    @inlinable mutating func writeString(_ value: String) {
        var value = value
        value.withUTF8 { utf8 in
            writeU32(UInt32(utf8.count))
            data.append(contentsOf: utf8)
        }
    }

    @inlinable mutating func writeBytes(_ value: Data) {
        writeU32(UInt32(value.count))
        data.append(contentsOf: value)
    }

    @inlinable mutating func writeDuration(_ value: TimeInterval) {
        if value.rounded(.down) > Double(Int64.max) { fatalError("Duration overflow") }
        if value < 0 { fatalError("Invalid duration") }
        let seconds = UInt64(value)
        let nanoseconds = UInt32((value - Double(seconds)) * 1.0e9)
        writeU64(seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeTimestamp(_ value: Date) {
        let delta = value.timeIntervalSince1970
        let secondsDouble = delta.rounded(.down)
        if secondsDouble < Double(Int64.min) || secondsDouble > Double(Int64.max) { fatalError("Timestamp overflow") }
        let seconds = Int64(secondsDouble)
        let nanoseconds = UInt32((delta - secondsDouble) * 1.0e9)
        writeI64(seconds)
        writeU32(nanoseconds)
    }

    @inlinable mutating func writeUuid(_ value: UUID) {
        var uuid = value.uuid
        let (hi, lo) = Swift.withUnsafeBytes(of: &uuid) { raw -> (UInt64, UInt64) in
            let hiBe = raw.loadUnaligned(fromByteOffset: 0, as: UInt64.self)
            let loBe = raw.loadUnaligned(fromByteOffset: 8, as: UInt64.self)
            return (UInt64(bigEndian: hiBe), UInt64(bigEndian: loBe))
        }
        writeU64(hi)
        writeU64(lo)
    }

    @inlinable mutating func writeUrl(_ value: URL) {
        writeString(value.absoluteString)
    }

    @inlinable mutating func writeOptional<T>(_ value: T?, _ body: (inout WireWriter, T) -> Void) {
        switch value {
        case .some(let value):
            writeU8(1)
            body(&self, value)
        case .none:
            writeU8(0)
        }
    }

    @inlinable mutating func writeSequence<T>(_ value: [T], _ body: (inout WireWriter, T) -> Void) {
        writeU32(UInt32(value.count))
        for item in value {
            body(&self, item)
        }
    }

    @inlinable mutating func writeArray<T>(_ value: [T], _ body: (inout WireWriter, T) -> Void) {
        writeSequence(value, body)
    }

    @inlinable mutating func writeResult<Success, Failure: Swift.Error>(
        _ value: Swift.Result<Success, Failure>,
        _ success: (inout WireWriter, Success) -> Void,
        _ failure: (inout WireWriter, Failure) -> Void
    ) {
        switch value {
        case .success(let value):
            writeU8(0)
            success(&self, value)
        case .failure(let value):
            writeU8(1)
            failure(&self, value)
        }
    }

    @inlinable mutating func writeMap<K: Hashable, V>(
        _ value: [K: V],
        _ key: (inout WireWriter, K) -> Void,
        _ writeValue: (inout WireWriter, V) -> Void
    ) {
        writeU32(UInt32(value.count))
        for entry in value {
            key(&self, entry.key)
            writeValue(&self, entry.value)
        }
    }

    @inlinable func finalize() -> Data {
        data
    }
}

@inlinable func boltffiDecodeOwnedBuf<T>(
    _ pointer: UnsafePointer<UInt8>?,
    _ length: Int,
    _ decode: (inout WireReader) -> T
) -> T {
    var reader = WireReader(ptr: pointer!, len: length)
    return decode(&reader)
}

@inlinable func boltffiEncode(_ body: (inout WireWriter) -> Void) -> [UInt8] {
    var writer = WireWriter()
    body(&writer)
    return [UInt8](writer.finalize())
}

/// Reserved marker for an error that does not match a callback's declared error type.
private let boltffiUnexpectedCallbackErrorMarker = Array("BOLTFFI_CALLBACK".utf8)

/// Version of the unexpected callback error payload written by this generated binding.
private let boltffiUnexpectedCallbackErrorVersion: UInt8 = 1

/// Encodes an unexpected host-language callback error for conversion by the Rust error owner.
///
/// Declared callback errors keep their normal wire representation. The marker lets Rust detect this
/// fallback before decoding the payload as the declared error type.
func boltffiEncodeUnexpectedCallbackError(_ error: Error) -> [UInt8] {
    var writer = WireWriter()
    writer.data.append(contentsOf: boltffiUnexpectedCallbackErrorMarker)
    writer.writeU8(boltffiUnexpectedCallbackErrorVersion)
    writer.writeString(String(describing: error))
    return [UInt8](writer.finalize())
}
