//! Snapshot tests for the TUI view layer.
//!
//! Uses `insta` to pin the text output of key view functions. Any change to
//! rendered output fails CI until reviewed and accepted with `cargo insta review`.
//! This is the Phase 0 regression net for the TUI architecture refactor.
//!
//! Initial snapshots are generated by running:
//! ```sh
//! INSTA_UPDATE=new cargo test -p jackin -- view::tests::snapshot --nocapture
//! ```

#[cfg(test)]
mod tests;
