//! Snapshot tests for the TUI render layer.
//!
//! Uses `insta` to pin the text output of key render functions. Any change to
//! rendered output fails CI until reviewed and accepted with `cargo insta review`.
//! This is the Phase 0 regression net for the TUI architecture refactor.
//!
//! Initial snapshots are generated by running:
//! ```sh
//! INSTA_UPDATE=new cargo test -p jackin -- snapshot_tests --nocapture
//! ```

#[cfg(test)]
mod tests {
    use ratatui::{Terminal, backend::TestBackend, buffer::Buffer, layout::Rect};

    use crate::{
        config::AppConfig,
        console::manager::{
            prepare_for_render, render,
            state::{
                EditorState, EditorTab, GlobalMountConfirm, GlobalMountModal, ManagerStage,
                ManagerState, Modal, MountScrollFocus, SettingsEnvModal, SettingsEnvScope,
                SettingsEnvTextTarget, SettingsState,
            },
        },
        workspace::WorkspaceConfig,
    };

    /// Render `ManagerState` to a text buffer dump for snapshot comparison.
    fn render_manager_state(
        state: &mut ManagerState<'_>,
        config: &AppConfig,
        cwd: &std::path::Path,
        width: u16,
        height: u16,
    ) -> String {
        let buf = render_manager_buffer(state, config, cwd, width, height);
        (0..height)
            .map(|y| {
                (0..width)
                    .map(|x| buf[(x, y)].symbol().to_string())
                    .collect::<String>()
            })
            .collect::<Vec<_>>()
            .join("\n")
    }

    fn render_manager_buffer(
        state: &mut ManagerState<'_>,
        config: &AppConfig,
        cwd: &std::path::Path,
        width: u16,
        height: u16,
    ) -> Buffer {
        let area = Rect::new(0, 0, width, height);
        let backend = TestBackend::new(width, height);
        let mut terminal = Terminal::new(backend).unwrap();
        prepare_for_render(state, config, cwd, area);
        terminal
            .draw(|frame| render(frame, area, state, config, cwd))
            .unwrap();
        terminal.backend().buffer().clone()
    }

    fn green_border_cluster_count(buf: &Buffer) -> usize {
        let area = buf.area;
        let mut seen = std::collections::BTreeSet::<(u16, u16)>::new();
        let mut clusters = 0usize;

        for y in area.y..area.y + area.height {
            for x in area.x..area.x + area.width {
                let coord = (x, y);
                if seen.contains(&coord) || !is_green_border_cell(buf, coord) {
                    continue;
                }
                clusters += 1;
                let mut stack = vec![coord];
                seen.insert(coord);
                while let Some((cx, cy)) = stack.pop() {
                    for next in neighbors(cx, cy, area) {
                        if seen.insert(next) && is_green_border_cell(buf, next) {
                            stack.push(next);
                        }
                    }
                }
            }
        }

        clusters
    }

    fn neighbors(x: u16, y: u16, area: Rect) -> impl Iterator<Item = (u16, u16)> {
        let min_x = area.x;
        let min_y = area.y;
        let max_x = area.x + area.width - 1;
        let max_y = area.y + area.height - 1;
        [
            x.checked_sub(1).map(|nx| (nx, y)),
            (x < max_x).then_some((x + 1, y)),
            y.checked_sub(1).map(|ny| (x, ny)),
            (y < max_y).then_some((x, y + 1)),
        ]
        .into_iter()
        .flatten()
        .filter(move |(nx, ny)| *nx >= min_x && *ny >= min_y)
    }

    fn is_green_border_cell(buf: &Buffer, coord: (u16, u16)) -> bool {
        let cell = &buf[coord];
        cell.fg == crate::console::widgets::PHOSPHOR_GREEN
            && matches!(cell.symbol(), "┌" | "┐" | "└" | "┘" | "─" | "│")
    }

    fn test_cwd() -> std::path::PathBuf {
        // Use a stable path so snapshots are reproducible.
        std::path::PathBuf::from("/workspace")
    }

    fn detail_config() -> AppConfig {
        toml::from_str(
            r#"
[roles."chainargos/agent-smith"]
git = "https://example.invalid/agent-smith.git"

[docker.mounts]
cache = { src = "/cache", dst = "/cache", readonly = false }

[docker.mounts."chainargos/agent-smith"]
secrets = { src = "/secrets", dst = "/secrets", readonly = true }

[workspaces.ws]
workdir = "/workspace"
allowed_roles = ["chainargos/agent-smith"]

[[workspaces.ws.mounts]]
src = "/workspace"
dst = "/workspace"
readonly = false
"#,
        )
        .expect("valid detail-pane config")
    }

    fn list_with_modal<'a>(
        config: &AppConfig,
        cwd: &std::path::Path,
        modal: Modal<'a>,
    ) -> ManagerState<'a> {
        let mut state = ManagerState::from_config(config, cwd);
        state.list_modal = Some(modal);
        state
    }

    fn settings_mounts_with_modal<'a>(
        config: &AppConfig,
        cwd: &std::path::Path,
        modal: GlobalMountModal<'a>,
    ) -> ManagerState<'a> {
        let mut state = ManagerState::from_config(config, cwd);
        let mut settings = SettingsState::from_config(config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Mounts;
        settings.tab_bar_focused = false;
        settings.mounts.scroll_focused = true;
        settings.mounts.modal = Some(modal);
        state.stage = ManagerStage::Settings(settings);
        state
    }

    fn settings_env_with_modal<'a>(
        config: &AppConfig,
        cwd: &std::path::Path,
        modal: SettingsEnvModal<'a>,
    ) -> ManagerState<'a> {
        let mut state = ManagerState::from_config(config, cwd);
        let mut settings = SettingsState::from_config(config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Environments;
        settings.tab_bar_focused = false;
        settings.env.scroll_focused = true;
        settings.env.modal = Some(modal);
        state.stage = ManagerStage::Settings(settings);
        state
    }

    fn settings_auth_with_modal(
        config: &AppConfig,
        cwd: &std::path::Path,
        modal: crate::console::manager::state::SettingsAuthModal<'static>,
    ) -> ManagerState<'static> {
        let mut state = ManagerState::from_config(config, cwd);
        let mut settings = SettingsState::from_config(config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Auth;
        settings.tab_bar_focused = false;
        settings.auth.scroll_focused = true;
        settings.auth.modal = Some(modal);
        state.stage = ManagerStage::Settings(settings);
        state
    }

    fn auth_form_modal() -> Modal<'static> {
        let kind = crate::console::manager::auth_kind::AuthKind::Claude;
        Modal::AuthForm {
            target: crate::console::manager::state::AuthFormTarget::Workspace { kind },
            state: Box::new(crate::console::widgets::auth_panel::AuthForm::new(kind)),
            focus: crate::console::manager::state::AuthFormFocus::Mode,
            literal_buffer: String::new(),
        }
    }

    #[test]
    fn snapshot_list_empty_80x24() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        // ManagerStage::List is the default.
        let rendered = render_manager_state(&mut state, &config, &cwd, 80, 24);
        insta::assert_snapshot!("list_empty_80x24", rendered);
    }

    #[test]
    fn new_workspace_hints_stay_in_footer() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 1;

        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 24);

        assert!(
            !rendered.contains("Press Enter"),
            "new-workspace body must not render keyboard hints inline:\n{rendered}"
        );
        assert!(
            rendered.contains("setup"),
            "footer must own the Enter/setup hint:\n{rendered}"
        );
    }

    #[test]
    fn snapshot_settings_general_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.stage = ManagerStage::Settings(SettingsState::from_config(&config));
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("settings_general_90x20", rendered);
    }

    #[test]
    fn snapshot_editor_general_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.stage = ManagerStage::Editor(EditorState::new_edit(
            "my-workspace".into(),
            WorkspaceConfig::default(),
        ));
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("editor_general_90x20", rendered);
    }

    #[test]
    fn editor_general_content_focus_shows_cursor() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("my-workspace".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.tab_content_scroll_focused = true;
        state.stage = ManagerStage::Editor(editor);

        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);

        assert!(
            rendered.contains("▸ Name"),
            "focused General tab must show the same cursor signal as its green border:\n{rendered}"
        );
    }

    #[test]
    fn snapshot_editor_mounts_tab_90x20() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut state = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.active_tab = EditorTab::Mounts;
        state.stage = ManagerStage::Editor(editor);
        let rendered = render_manager_state(&mut state, &config, &cwd, 90, 20);
        insta::assert_snapshot!("editor_mounts_tab_90x20", rendered);
    }

    #[test]
    fn host_console_content_states_have_one_green_border_cluster() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut cases: Vec<(&str, ManagerState<'_>)> = Vec::new();

        let mut list = ManagerState::from_config(&config, &cwd);
        list.list_names_focused = true;
        cases.push(("list", list));

        for (name, tab) in [
            ("editor general", EditorTab::General),
            ("editor mounts", EditorTab::Mounts),
            ("editor roles", EditorTab::Roles),
            ("editor secrets", EditorTab::Secrets),
            ("editor auth", EditorTab::Auth),
        ] {
            let mut state = ManagerState::from_config(&config, &cwd);
            let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
            editor.active_tab = tab;
            editor.tab_bar_focused = false;
            editor.tab_content_scroll_focused = true;
            editor.workspace_mounts_scroll_focused = tab == EditorTab::Mounts;
            state.stage = ManagerStage::Editor(editor);
            cases.push((name, state));
        }

        for tab in crate::console::manager::state::SettingsTab::ALL {
            let mut state = ManagerState::from_config(&config, &cwd);
            let mut settings = SettingsState::from_config(&config);
            settings.active_tab = tab;
            settings.tab_bar_focused = false;
            settings.mounts.scroll_focused =
                tab == crate::console::manager::state::SettingsTab::Mounts;
            settings.env.scroll_focused =
                tab == crate::console::manager::state::SettingsTab::Environments;
            settings.auth.scroll_focused = tab == crate::console::manager::state::SettingsTab::Auth;
            settings.trust.scroll_focused =
                tab == crate::console::manager::state::SettingsTab::Trust;
            state.stage = ManagerStage::Settings(settings);
            cases.push((tab.label(), state));
        }

        for (name, mut state) in cases {
            let buf = render_manager_buffer(&mut state, &config, &cwd, 100, 28);
            assert_eq!(
                green_border_cluster_count(&buf),
                1,
                "{name} must render exactly one PHOSPHOR_GREEN border cluster"
            );
        }
    }

    #[test]
    fn host_console_list_detail_transitions_have_one_green_border_cluster() {
        let cwd = test_cwd();

        let mut cases: Vec<(&str, AppConfig, ManagerState<'_>)> = Vec::new();

        let config = detail_config();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 0;
        state.list_names_focused = true;
        cases.push(("current dir list focus", config, state));

        let config = detail_config();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 0;
        state.list_names_focused = false;
        state.list_scroll_focus = Some(MountScrollFocus::Workspace);
        cases.push(("current dir mounts focus", config, state));

        let config = detail_config();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 0;
        state.list_names_focused = false;
        state.list_scroll_focus = Some(MountScrollFocus::Global);
        cases.push(("current dir global mounts focus", config, state));

        let config = detail_config();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 1;
        state.list_names_focused = true;
        cases.push(("saved workspace list focus", config, state));

        for (name, focus) in [
            ("saved workspace mounts focus", MountScrollFocus::Workspace),
            (
                "saved workspace global mounts focus",
                MountScrollFocus::Global,
            ),
            (
                "saved workspace role global mounts focus",
                MountScrollFocus::RoleGlobal,
            ),
            ("saved workspace roles focus", MountScrollFocus::Roles),
        ] {
            let config = detail_config();
            let mut state = ManagerState::from_config(&config, &cwd);
            state.selected = 1;
            state.list_names_focused = false;
            state.list_scroll_focus = Some(focus);
            cases.push((name, config, state));
        }

        let config = detail_config();
        let mut state = ManagerState::from_config(&config, &cwd);
        state.selected = 2;
        state.list_names_focused = true;
        cases.push(("new workspace detail focus", config, state));

        for (name, config, mut state) in cases {
            let buf = render_manager_buffer(&mut state, &config, &cwd, 110, 30);
            assert_eq!(
                green_border_cluster_count(&buf),
                1,
                "{name} must render exactly one PHOSPHOR_GREEN border cluster"
            );
        }
    }

    #[test]
    fn host_console_modal_states_have_one_green_border_cluster() {
        let config = AppConfig::default();
        let cwd = test_cwd();
        let mut cases: Vec<(&str, ManagerState<'_>)> = Vec::new();

        let mut confirm_delete = ManagerState::from_config(&config, &cwd);
        confirm_delete.stage = ManagerStage::ConfirmDelete {
            name: "ws".to_string(),
            state: jackin_tui::components::ConfirmState::new("Delete workspace?"),
        };
        cases.push(("list confirm delete", confirm_delete));

        cases.push((
            "list confirm modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::Confirm {
                    target: crate::console::manager::state::ConfirmTarget::DeleteEnvVar {
                        scope: crate::console::manager::state::SecretsScopeTag::Workspace,
                        key: "TOKEN".into(),
                    },
                    state: jackin_tui::components::ConfirmState::new("Delete TOKEN?"),
                },
            ),
        ));

        cases.push((
            "list save discard modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::SaveDiscardCancel {
                    state: jackin_tui::components::SaveDiscardState::new("Save changes?"),
                },
            ),
        ));

        cases.push((
            "list status modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::StatusPopup {
                    state: jackin_tui::components::StatusPopupState::new(
                        "Loading",
                        "Resolving role",
                    ),
                },
            ),
        ));

        cases.push((
            "list file browser modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::FileBrowser {
                    target: crate::console::manager::state::FileBrowserTarget::CreateFirstMountSrc,
                    state: jackin_console::widgets::file_browser::FileBrowserState::new_at(
                        cwd.clone(),
                        cwd.clone(),
                    ),
                },
            ),
        ));

        cases.push((
            "list mount dst choice modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::MountDstChoice {
                    target: crate::console::manager::state::FileBrowserTarget::CreateFirstMountSrc,
                    state:
                        jackin_console::tui::components::mount_dst_choice::MountDstChoiceState::new(
                            "/workspace",
                        ),
                },
            ),
        ));

        cases.push((
            "list workdir picker modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::WorkdirPick {
                    state: jackin_console::widgets::workdir_pick::WorkdirPickState::from_mounts(&[
                        crate::workspace::MountConfig {
                            src: "/workspace".into(),
                            dst: "/workspace".into(),
                            readonly: false,
                            isolation: crate::isolation::MountIsolation::Shared,
                        },
                    ]),
                },
            ),
        ));

        cases.push((
            "list github picker modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::GithubPicker {
                    state: jackin_console::widgets::github_picker::GithubPickerState::new(vec![
                        jackin_console::widgets::github_picker::GithubChoice {
                            src: "/workspace".into(),
                            branch: "main".into(),
                            url: "https://github.com/example/repo".into(),
                        },
                    ]),
                },
            ),
        ));

        cases.push((
            "list role picker modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::RolePicker {
                    state: crate::selector::RolePickerState::new(vec![
                        crate::selector::RoleSelector::parse("chainargos/agent-smith")
                            .expect("valid role selector"),
                    ]),
                },
            ),
        ));

        cases.push((
            "list source picker modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::SourcePicker {
                    state: jackin_console::widgets::source_picker::SourcePickerState::new(
                        "TOKEN".into(),
                        true,
                    ),
                    env_key: None,
                },
            ),
        ));

        cases.push((
            "list scope picker modal",
            list_with_modal(
                &config,
                &cwd,
                Modal::ScopePicker {
                    state: jackin_console::tui::components::scope_picker::ScopePickerState::new(),
                },
            ),
        ));

        let mut editor_text = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.tab_content_scroll_focused = true;
        editor.modal = Some(Modal::TextInput {
            target: crate::console::manager::state::TextInputTarget::Name,
            state: jackin_tui::components::TextInputState::new("Name", "ws"),
        });
        editor_text.stage = ManagerStage::Editor(editor);
        cases.push(("editor text input", editor_text));

        let mut editor_state = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(Modal::ContainerInfo {
            state: jackin_tui::components::ContainerInfoState::new(
                "Container",
                vec![jackin_tui::components::ContainerInfoRow::new(
                    "Run ID", "abc",
                )],
            ),
        });
        editor_state.stage = ManagerStage::Editor(editor);
        cases.push(("editor container info", editor_state));

        let mut editor_op_picker = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(Modal::OpPicker {
            state: Box::new(crate::console::widgets::op_picker::OpPickerState::new()),
        });
        editor_op_picker.stage = ManagerStage::Editor(editor);
        cases.push(("editor op picker", editor_op_picker));

        let mut editor_role_override = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(Modal::RoleOverridePicker {
            state: crate::selector::RolePickerState::new(vec![
                crate::selector::RoleSelector::parse("chainargos/agent-smith")
                    .expect("valid role selector"),
            ]),
        });
        editor_role_override.stage = ManagerStage::Editor(editor);
        cases.push(("editor role override picker", editor_role_override));

        let mut editor_auth_role = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(Modal::AuthRolePicker {
            state: crate::selector::RolePickerState::new(vec![
                crate::selector::RoleSelector::parse("chainargos/agent-smith")
                    .expect("valid role selector"),
            ]),
        });
        editor_auth_role.stage = ManagerStage::Editor(editor);
        cases.push(("editor auth role picker", editor_auth_role));

        let mut editor_auth_source = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(Modal::AuthSourcePicker {
            state: jackin_console::widgets::source_picker::SourcePickerState::new(
                "CLAUDE_CODE_OAUTH_TOKEN".into(),
                true,
            ),
        });
        editor_auth_source.stage = ManagerStage::Editor(editor);
        cases.push(("editor auth source picker", editor_auth_source));

        let mut editor_auth_form = ManagerState::from_config(&config, &cwd);
        let mut editor = EditorState::new_edit("ws".into(), WorkspaceConfig::default());
        editor.tab_bar_focused = false;
        editor.modal = Some(auth_form_modal());
        editor_auth_form.stage = ManagerStage::Editor(editor);
        cases.push(("editor auth form", editor_auth_form));

        let mut settings_mounts_confirm = ManagerState::from_config(&config, &cwd);
        let mut settings = SettingsState::from_config(&config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Mounts;
        settings.tab_bar_focused = false;
        settings.mounts.scroll_focused = true;
        settings.mounts.modal = Some(GlobalMountModal::Confirm {
            action: GlobalMountConfirm::Remove,
            state: jackin_tui::components::ConfirmState::new("Remove mount?"),
        });
        settings_mounts_confirm.stage = ManagerStage::Settings(settings);
        cases.push(("settings mounts confirm", settings_mounts_confirm));

        cases.push((
            "settings mounts text",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::Text {
                    target: crate::console::manager::state::GlobalMountTextTarget::AddName,
                    state: Box::new(jackin_tui::components::TextInputState::new(
                        "Mount name",
                        "repo",
                    )),
                },
            ),
        ));

        cases.push((
            "settings mounts file browser",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::FileBrowser {
                    state: Box::new(
                        jackin_console::widgets::file_browser::FileBrowserState::new_at(
                            cwd.clone(),
                            cwd.clone(),
                        ),
                    ),
                },
            ),
        ));

        cases.push((
            "settings mounts destination choice",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::MountDstChoice {
                    state:
                        jackin_console::tui::components::mount_dst_choice::MountDstChoiceState::new(
                            "/workspace",
                        ),
                },
            ),
        ));

        cases.push((
            "settings mounts scope picker",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::ScopePicker {
                    state: jackin_console::tui::components::scope_picker::ScopePickerState::new(),
                },
            ),
        ));

        cases.push((
            "settings mounts role picker",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::RolePicker {
                    state: crate::selector::RolePickerState::new(vec![
                        crate::selector::RoleSelector::parse("chainargos/agent-smith")
                            .expect("valid role selector"),
                    ]),
                },
            ),
        ));

        cases.push((
            "settings mounts preview save",
            settings_mounts_with_modal(
                &config,
                &cwd,
                GlobalMountModal::PreviewSave {
                    state: jackin_console::tui::components::confirm_save::ConfirmSaveState::new(
                        vec![ratatui::text::Line::from("Add global mount /workspace")],
                    ),
                },
            ),
        ));

        let mut settings_env_text = ManagerState::from_config(&config, &cwd);
        let mut settings = SettingsState::from_config(&config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Environments;
        settings.tab_bar_focused = false;
        settings.env.scroll_focused = true;
        settings.env.modal = Some(SettingsEnvModal::Text {
            target: SettingsEnvTextTarget::EnvKey {
                scope: SettingsEnvScope::Global,
            },
            state: Box::new(jackin_tui::components::TextInputState::new(
                "Environment key",
                "TOKEN",
            )),
        });
        settings_env_text.stage = ManagerStage::Settings(settings);
        cases.push(("settings env text", settings_env_text));

        cases.push((
            "settings env source picker",
            settings_env_with_modal(
                &config,
                &cwd,
                SettingsEnvModal::SourcePicker {
                    state: jackin_console::widgets::source_picker::SourcePickerState::new(
                        "TOKEN".into(),
                        true,
                    ),
                },
            ),
        ));

        cases.push((
            "settings env op picker",
            settings_env_with_modal(
                &config,
                &cwd,
                SettingsEnvModal::OpPicker {
                    state: Box::new(crate::console::widgets::op_picker::OpPickerState::new()),
                },
            ),
        ));

        cases.push((
            "settings env role picker",
            settings_env_with_modal(
                &config,
                &cwd,
                SettingsEnvModal::RolePicker {
                    state: crate::selector::RolePickerState::new(vec![
                        crate::selector::RoleSelector::parse("chainargos/agent-smith")
                            .expect("valid role selector"),
                    ]),
                },
            ),
        ));

        cases.push((
            "settings env scope picker",
            settings_env_with_modal(
                &config,
                &cwd,
                SettingsEnvModal::ScopePicker {
                    state: jackin_console::tui::components::scope_picker::ScopePickerState::new(),
                },
            ),
        ));

        cases.push((
            "settings env confirm",
            settings_env_with_modal(
                &config,
                &cwd,
                SettingsEnvModal::Confirm {
                    action: crate::console::manager::state::SettingsEnvConfirm::Delete,
                    state: jackin_tui::components::ConfirmState::new("Delete env var?"),
                },
            ),
        ));

        let mut settings_auth_text = ManagerState::from_config(&config, &cwd);
        let mut settings = SettingsState::from_config(&config);
        settings.active_tab = crate::console::manager::state::SettingsTab::Auth;
        settings.tab_bar_focused = false;
        settings.auth.scroll_focused = true;
        settings.auth.modal = Some(
            crate::console::manager::state::SettingsAuthModal::TextInput {
                state: Box::new(jackin_tui::components::TextInputState::new(
                    "Credential",
                    "token",
                )),
            },
        );
        settings_auth_text.stage = ManagerStage::Settings(settings);
        cases.push(("settings auth text", settings_auth_text));

        cases.push((
            "settings auth source picker",
            settings_auth_with_modal(
                &config,
                &cwd,
                crate::console::manager::state::SettingsAuthModal::SourcePicker {
                    state: jackin_console::widgets::source_picker::SourcePickerState::new(
                        "CLAUDE_CODE_OAUTH_TOKEN".into(),
                        true,
                    ),
                },
            ),
        ));

        cases.push((
            "settings auth op picker",
            settings_auth_with_modal(
                &config,
                &cwd,
                crate::console::manager::state::SettingsAuthModal::OpPicker {
                    state: Box::new(crate::console::widgets::op_picker::OpPickerState::new()),
                },
            ),
        ));

        let kind = crate::console::manager::auth_kind::AuthKind::Claude;
        cases.push((
            "settings auth form",
            settings_auth_with_modal(
                &config,
                &cwd,
                crate::console::manager::state::SettingsAuthModal::AuthForm {
                    target: crate::console::manager::state::AuthFormTarget::Workspace { kind },
                    state: Box::new(crate::console::widgets::auth_panel::AuthForm::new(kind)),
                    focus: crate::console::manager::state::AuthFormFocus::Mode,
                    literal_buffer: String::new(),
                },
            ),
        ));

        for (name, mut state) in cases {
            let buf = render_manager_buffer(&mut state, &config, &cwd, 100, 28);
            assert_eq!(
                green_border_cluster_count(&buf),
                1,
                "{name} must render exactly one PHOSPHOR_GREEN border cluster"
            );
        }
    }
}
